// Code generated by ent, DO NOT EDIT.

package fitnesscheckin

import (
	"platform/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldEQ(FieldDeletedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldEQ(FieldUserID, v))
}

// CheckinDate applies equality check predicate on the "checkin_date" field. It's identical to CheckinDateEQ.
func CheckinDate(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldEQ(FieldCheckinDate, v))
}

// DurationMinutes applies equality check predicate on the "duration_minutes" field. It's identical to DurationMinutesEQ.
func DurationMinutes(v int) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldEQ(FieldDurationMinutes, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldEQ(FieldContent, v))
}

// Calories applies equality check predicate on the "calories" field. It's identical to CaloriesEQ.
func Calories(v int) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldEQ(FieldCalories, v))
}

// Weight applies equality check predicate on the "weight" field. It's identical to WeightEQ.
func Weight(v float64) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldEQ(FieldWeight, v))
}

// WeightPublic applies equality check predicate on the "weight_public" field. It's identical to WeightPublicEQ.
func WeightPublic(v bool) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldEQ(FieldWeightPublic, v))
}

// Mood applies equality check predicate on the "mood" field. It's identical to MoodEQ.
func Mood(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldEQ(FieldMood, v))
}

// AuditDetail applies equality check predicate on the "audit_detail" field. It's identical to AuditDetailEQ.
func AuditDetail(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldEQ(FieldAuditDetail, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldNotNull(FieldDeletedAt))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldContainsFold(FieldUserID, v))
}

// CheckinDateEQ applies the EQ predicate on the "checkin_date" field.
func CheckinDateEQ(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldEQ(FieldCheckinDate, v))
}

// CheckinDateNEQ applies the NEQ predicate on the "checkin_date" field.
func CheckinDateNEQ(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldNEQ(FieldCheckinDate, v))
}

// CheckinDateIn applies the In predicate on the "checkin_date" field.
func CheckinDateIn(vs ...string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldIn(FieldCheckinDate, vs...))
}

// CheckinDateNotIn applies the NotIn predicate on the "checkin_date" field.
func CheckinDateNotIn(vs ...string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldNotIn(FieldCheckinDate, vs...))
}

// CheckinDateGT applies the GT predicate on the "checkin_date" field.
func CheckinDateGT(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldGT(FieldCheckinDate, v))
}

// CheckinDateGTE applies the GTE predicate on the "checkin_date" field.
func CheckinDateGTE(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldGTE(FieldCheckinDate, v))
}

// CheckinDateLT applies the LT predicate on the "checkin_date" field.
func CheckinDateLT(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldLT(FieldCheckinDate, v))
}

// CheckinDateLTE applies the LTE predicate on the "checkin_date" field.
func CheckinDateLTE(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldLTE(FieldCheckinDate, v))
}

// CheckinDateContains applies the Contains predicate on the "checkin_date" field.
func CheckinDateContains(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldContains(FieldCheckinDate, v))
}

// CheckinDateHasPrefix applies the HasPrefix predicate on the "checkin_date" field.
func CheckinDateHasPrefix(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldHasPrefix(FieldCheckinDate, v))
}

// CheckinDateHasSuffix applies the HasSuffix predicate on the "checkin_date" field.
func CheckinDateHasSuffix(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldHasSuffix(FieldCheckinDate, v))
}

// CheckinDateEqualFold applies the EqualFold predicate on the "checkin_date" field.
func CheckinDateEqualFold(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldEqualFold(FieldCheckinDate, v))
}

// CheckinDateContainsFold applies the ContainsFold predicate on the "checkin_date" field.
func CheckinDateContainsFold(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldContainsFold(FieldCheckinDate, v))
}

// ExerciseTypeEQ applies the EQ predicate on the "exercise_type" field.
func ExerciseTypeEQ(v ExerciseType) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldEQ(FieldExerciseType, v))
}

// ExerciseTypeNEQ applies the NEQ predicate on the "exercise_type" field.
func ExerciseTypeNEQ(v ExerciseType) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldNEQ(FieldExerciseType, v))
}

// ExerciseTypeIn applies the In predicate on the "exercise_type" field.
func ExerciseTypeIn(vs ...ExerciseType) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldIn(FieldExerciseType, vs...))
}

// ExerciseTypeNotIn applies the NotIn predicate on the "exercise_type" field.
func ExerciseTypeNotIn(vs ...ExerciseType) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldNotIn(FieldExerciseType, vs...))
}

// DurationMinutesEQ applies the EQ predicate on the "duration_minutes" field.
func DurationMinutesEQ(v int) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldEQ(FieldDurationMinutes, v))
}

// DurationMinutesNEQ applies the NEQ predicate on the "duration_minutes" field.
func DurationMinutesNEQ(v int) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldNEQ(FieldDurationMinutes, v))
}

// DurationMinutesIn applies the In predicate on the "duration_minutes" field.
func DurationMinutesIn(vs ...int) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldIn(FieldDurationMinutes, vs...))
}

// DurationMinutesNotIn applies the NotIn predicate on the "duration_minutes" field.
func DurationMinutesNotIn(vs ...int) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldNotIn(FieldDurationMinutes, vs...))
}

// DurationMinutesGT applies the GT predicate on the "duration_minutes" field.
func DurationMinutesGT(v int) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldGT(FieldDurationMinutes, v))
}

// DurationMinutesGTE applies the GTE predicate on the "duration_minutes" field.
func DurationMinutesGTE(v int) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldGTE(FieldDurationMinutes, v))
}

// DurationMinutesLT applies the LT predicate on the "duration_minutes" field.
func DurationMinutesLT(v int) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldLT(FieldDurationMinutes, v))
}

// DurationMinutesLTE applies the LTE predicate on the "duration_minutes" field.
func DurationMinutesLTE(v int) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldLTE(FieldDurationMinutes, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldHasSuffix(FieldContent, v))
}

// ContentIsNil applies the IsNil predicate on the "content" field.
func ContentIsNil() predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldIsNull(FieldContent))
}

// ContentNotNil applies the NotNil predicate on the "content" field.
func ContentNotNil() predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldNotNull(FieldContent))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldContainsFold(FieldContent, v))
}

// CaloriesEQ applies the EQ predicate on the "calories" field.
func CaloriesEQ(v int) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldEQ(FieldCalories, v))
}

// CaloriesNEQ applies the NEQ predicate on the "calories" field.
func CaloriesNEQ(v int) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldNEQ(FieldCalories, v))
}

// CaloriesIn applies the In predicate on the "calories" field.
func CaloriesIn(vs ...int) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldIn(FieldCalories, vs...))
}

// CaloriesNotIn applies the NotIn predicate on the "calories" field.
func CaloriesNotIn(vs ...int) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldNotIn(FieldCalories, vs...))
}

// CaloriesGT applies the GT predicate on the "calories" field.
func CaloriesGT(v int) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldGT(FieldCalories, v))
}

// CaloriesGTE applies the GTE predicate on the "calories" field.
func CaloriesGTE(v int) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldGTE(FieldCalories, v))
}

// CaloriesLT applies the LT predicate on the "calories" field.
func CaloriesLT(v int) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldLT(FieldCalories, v))
}

// CaloriesLTE applies the LTE predicate on the "calories" field.
func CaloriesLTE(v int) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldLTE(FieldCalories, v))
}

// CaloriesIsNil applies the IsNil predicate on the "calories" field.
func CaloriesIsNil() predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldIsNull(FieldCalories))
}

// CaloriesNotNil applies the NotNil predicate on the "calories" field.
func CaloriesNotNil() predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldNotNull(FieldCalories))
}

// WeightEQ applies the EQ predicate on the "weight" field.
func WeightEQ(v float64) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldEQ(FieldWeight, v))
}

// WeightNEQ applies the NEQ predicate on the "weight" field.
func WeightNEQ(v float64) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldNEQ(FieldWeight, v))
}

// WeightIn applies the In predicate on the "weight" field.
func WeightIn(vs ...float64) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldIn(FieldWeight, vs...))
}

// WeightNotIn applies the NotIn predicate on the "weight" field.
func WeightNotIn(vs ...float64) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldNotIn(FieldWeight, vs...))
}

// WeightGT applies the GT predicate on the "weight" field.
func WeightGT(v float64) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldGT(FieldWeight, v))
}

// WeightGTE applies the GTE predicate on the "weight" field.
func WeightGTE(v float64) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldGTE(FieldWeight, v))
}

// WeightLT applies the LT predicate on the "weight" field.
func WeightLT(v float64) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldLT(FieldWeight, v))
}

// WeightLTE applies the LTE predicate on the "weight" field.
func WeightLTE(v float64) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldLTE(FieldWeight, v))
}

// WeightIsNil applies the IsNil predicate on the "weight" field.
func WeightIsNil() predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldIsNull(FieldWeight))
}

// WeightNotNil applies the NotNil predicate on the "weight" field.
func WeightNotNil() predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldNotNull(FieldWeight))
}

// WeightPublicEQ applies the EQ predicate on the "weight_public" field.
func WeightPublicEQ(v bool) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldEQ(FieldWeightPublic, v))
}

// WeightPublicNEQ applies the NEQ predicate on the "weight_public" field.
func WeightPublicNEQ(v bool) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldNEQ(FieldWeightPublic, v))
}

// MoodEQ applies the EQ predicate on the "mood" field.
func MoodEQ(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldEQ(FieldMood, v))
}

// MoodNEQ applies the NEQ predicate on the "mood" field.
func MoodNEQ(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldNEQ(FieldMood, v))
}

// MoodIn applies the In predicate on the "mood" field.
func MoodIn(vs ...string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldIn(FieldMood, vs...))
}

// MoodNotIn applies the NotIn predicate on the "mood" field.
func MoodNotIn(vs ...string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldNotIn(FieldMood, vs...))
}

// MoodGT applies the GT predicate on the "mood" field.
func MoodGT(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldGT(FieldMood, v))
}

// MoodGTE applies the GTE predicate on the "mood" field.
func MoodGTE(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldGTE(FieldMood, v))
}

// MoodLT applies the LT predicate on the "mood" field.
func MoodLT(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldLT(FieldMood, v))
}

// MoodLTE applies the LTE predicate on the "mood" field.
func MoodLTE(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldLTE(FieldMood, v))
}

// MoodContains applies the Contains predicate on the "mood" field.
func MoodContains(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldContains(FieldMood, v))
}

// MoodHasPrefix applies the HasPrefix predicate on the "mood" field.
func MoodHasPrefix(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldHasPrefix(FieldMood, v))
}

// MoodHasSuffix applies the HasSuffix predicate on the "mood" field.
func MoodHasSuffix(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldHasSuffix(FieldMood, v))
}

// MoodIsNil applies the IsNil predicate on the "mood" field.
func MoodIsNil() predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldIsNull(FieldMood))
}

// MoodNotNil applies the NotNil predicate on the "mood" field.
func MoodNotNil() predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldNotNull(FieldMood))
}

// MoodEqualFold applies the EqualFold predicate on the "mood" field.
func MoodEqualFold(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldEqualFold(FieldMood, v))
}

// MoodContainsFold applies the ContainsFold predicate on the "mood" field.
func MoodContainsFold(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldContainsFold(FieldMood, v))
}

// AuditStatusEQ applies the EQ predicate on the "audit_status" field.
func AuditStatusEQ(v AuditStatus) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldEQ(FieldAuditStatus, v))
}

// AuditStatusNEQ applies the NEQ predicate on the "audit_status" field.
func AuditStatusNEQ(v AuditStatus) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldNEQ(FieldAuditStatus, v))
}

// AuditStatusIn applies the In predicate on the "audit_status" field.
func AuditStatusIn(vs ...AuditStatus) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldIn(FieldAuditStatus, vs...))
}

// AuditStatusNotIn applies the NotIn predicate on the "audit_status" field.
func AuditStatusNotIn(vs ...AuditStatus) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldNotIn(FieldAuditStatus, vs...))
}

// AuditDetailEQ applies the EQ predicate on the "audit_detail" field.
func AuditDetailEQ(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldEQ(FieldAuditDetail, v))
}

// AuditDetailNEQ applies the NEQ predicate on the "audit_detail" field.
func AuditDetailNEQ(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldNEQ(FieldAuditDetail, v))
}

// AuditDetailIn applies the In predicate on the "audit_detail" field.
func AuditDetailIn(vs ...string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldIn(FieldAuditDetail, vs...))
}

// AuditDetailNotIn applies the NotIn predicate on the "audit_detail" field.
func AuditDetailNotIn(vs ...string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldNotIn(FieldAuditDetail, vs...))
}

// AuditDetailGT applies the GT predicate on the "audit_detail" field.
func AuditDetailGT(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldGT(FieldAuditDetail, v))
}

// AuditDetailGTE applies the GTE predicate on the "audit_detail" field.
func AuditDetailGTE(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldGTE(FieldAuditDetail, v))
}

// AuditDetailLT applies the LT predicate on the "audit_detail" field.
func AuditDetailLT(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldLT(FieldAuditDetail, v))
}

// AuditDetailLTE applies the LTE predicate on the "audit_detail" field.
func AuditDetailLTE(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldLTE(FieldAuditDetail, v))
}

// AuditDetailContains applies the Contains predicate on the "audit_detail" field.
func AuditDetailContains(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldContains(FieldAuditDetail, v))
}

// AuditDetailHasPrefix applies the HasPrefix predicate on the "audit_detail" field.
func AuditDetailHasPrefix(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldHasPrefix(FieldAuditDetail, v))
}

// AuditDetailHasSuffix applies the HasSuffix predicate on the "audit_detail" field.
func AuditDetailHasSuffix(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldHasSuffix(FieldAuditDetail, v))
}

// AuditDetailIsNil applies the IsNil predicate on the "audit_detail" field.
func AuditDetailIsNil() predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldIsNull(FieldAuditDetail))
}

// AuditDetailNotNil applies the NotNil predicate on the "audit_detail" field.
func AuditDetailNotNil() predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldNotNull(FieldAuditDetail))
}

// AuditDetailEqualFold applies the EqualFold predicate on the "audit_detail" field.
func AuditDetailEqualFold(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldEqualFold(FieldAuditDetail, v))
}

// AuditDetailContainsFold applies the ContainsFold predicate on the "audit_detail" field.
func AuditDetailContainsFold(v string) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.FieldContainsFold(FieldAuditDetail, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FitnessCheckin) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FitnessCheckin) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FitnessCheckin) predicate.FitnessCheckin {
	return predicate.FitnessCheckin(sql.NotPredicates(p))
}
