// Code generated by ent, DO NOT EDIT.

package fitnessgroupinvitation

import (
	"platform/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldEQ(FieldDeletedAt, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldEQ(FieldGroupID, v))
}

// CreatorID applies equality check predicate on the "creator_id" field. It's identical to CreatorIDEQ.
func CreatorID(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldEQ(FieldCreatorID, v))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldEQ(FieldCode, v))
}

// QrFileID applies equality check predicate on the "qr_file_id" field. It's identical to QrFileIDEQ.
func QrFileID(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldEQ(FieldQrFileID, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldEQ(FieldExpiresAt, v))
}

// Active applies equality check predicate on the "active" field. It's identical to ActiveEQ.
func Active(v bool) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldEQ(FieldActive, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldNotNull(FieldDeletedAt))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldLTE(FieldGroupID, v))
}

// GroupIDContains applies the Contains predicate on the "group_id" field.
func GroupIDContains(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldContains(FieldGroupID, v))
}

// GroupIDHasPrefix applies the HasPrefix predicate on the "group_id" field.
func GroupIDHasPrefix(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldHasPrefix(FieldGroupID, v))
}

// GroupIDHasSuffix applies the HasSuffix predicate on the "group_id" field.
func GroupIDHasSuffix(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldHasSuffix(FieldGroupID, v))
}

// GroupIDEqualFold applies the EqualFold predicate on the "group_id" field.
func GroupIDEqualFold(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldEqualFold(FieldGroupID, v))
}

// GroupIDContainsFold applies the ContainsFold predicate on the "group_id" field.
func GroupIDContainsFold(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldContainsFold(FieldGroupID, v))
}

// CreatorIDEQ applies the EQ predicate on the "creator_id" field.
func CreatorIDEQ(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldEQ(FieldCreatorID, v))
}

// CreatorIDNEQ applies the NEQ predicate on the "creator_id" field.
func CreatorIDNEQ(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldNEQ(FieldCreatorID, v))
}

// CreatorIDIn applies the In predicate on the "creator_id" field.
func CreatorIDIn(vs ...string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldIn(FieldCreatorID, vs...))
}

// CreatorIDNotIn applies the NotIn predicate on the "creator_id" field.
func CreatorIDNotIn(vs ...string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldNotIn(FieldCreatorID, vs...))
}

// CreatorIDGT applies the GT predicate on the "creator_id" field.
func CreatorIDGT(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldGT(FieldCreatorID, v))
}

// CreatorIDGTE applies the GTE predicate on the "creator_id" field.
func CreatorIDGTE(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldGTE(FieldCreatorID, v))
}

// CreatorIDLT applies the LT predicate on the "creator_id" field.
func CreatorIDLT(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldLT(FieldCreatorID, v))
}

// CreatorIDLTE applies the LTE predicate on the "creator_id" field.
func CreatorIDLTE(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldLTE(FieldCreatorID, v))
}

// CreatorIDContains applies the Contains predicate on the "creator_id" field.
func CreatorIDContains(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldContains(FieldCreatorID, v))
}

// CreatorIDHasPrefix applies the HasPrefix predicate on the "creator_id" field.
func CreatorIDHasPrefix(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldHasPrefix(FieldCreatorID, v))
}

// CreatorIDHasSuffix applies the HasSuffix predicate on the "creator_id" field.
func CreatorIDHasSuffix(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldHasSuffix(FieldCreatorID, v))
}

// CreatorIDEqualFold applies the EqualFold predicate on the "creator_id" field.
func CreatorIDEqualFold(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldEqualFold(FieldCreatorID, v))
}

// CreatorIDContainsFold applies the ContainsFold predicate on the "creator_id" field.
func CreatorIDContainsFold(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldContainsFold(FieldCreatorID, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldContainsFold(FieldCode, v))
}

// QrFileIDEQ applies the EQ predicate on the "qr_file_id" field.
func QrFileIDEQ(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldEQ(FieldQrFileID, v))
}

// QrFileIDNEQ applies the NEQ predicate on the "qr_file_id" field.
func QrFileIDNEQ(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldNEQ(FieldQrFileID, v))
}

// QrFileIDIn applies the In predicate on the "qr_file_id" field.
func QrFileIDIn(vs ...string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldIn(FieldQrFileID, vs...))
}

// QrFileIDNotIn applies the NotIn predicate on the "qr_file_id" field.
func QrFileIDNotIn(vs ...string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldNotIn(FieldQrFileID, vs...))
}

// QrFileIDGT applies the GT predicate on the "qr_file_id" field.
func QrFileIDGT(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldGT(FieldQrFileID, v))
}

// QrFileIDGTE applies the GTE predicate on the "qr_file_id" field.
func QrFileIDGTE(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldGTE(FieldQrFileID, v))
}

// QrFileIDLT applies the LT predicate on the "qr_file_id" field.
func QrFileIDLT(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldLT(FieldQrFileID, v))
}

// QrFileIDLTE applies the LTE predicate on the "qr_file_id" field.
func QrFileIDLTE(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldLTE(FieldQrFileID, v))
}

// QrFileIDContains applies the Contains predicate on the "qr_file_id" field.
func QrFileIDContains(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldContains(FieldQrFileID, v))
}

// QrFileIDHasPrefix applies the HasPrefix predicate on the "qr_file_id" field.
func QrFileIDHasPrefix(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldHasPrefix(FieldQrFileID, v))
}

// QrFileIDHasSuffix applies the HasSuffix predicate on the "qr_file_id" field.
func QrFileIDHasSuffix(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldHasSuffix(FieldQrFileID, v))
}

// QrFileIDIsNil applies the IsNil predicate on the "qr_file_id" field.
func QrFileIDIsNil() predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldIsNull(FieldQrFileID))
}

// QrFileIDNotNil applies the NotNil predicate on the "qr_file_id" field.
func QrFileIDNotNil() predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldNotNull(FieldQrFileID))
}

// QrFileIDEqualFold applies the EqualFold predicate on the "qr_file_id" field.
func QrFileIDEqualFold(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldEqualFold(FieldQrFileID, v))
}

// QrFileIDContainsFold applies the ContainsFold predicate on the "qr_file_id" field.
func QrFileIDContainsFold(v string) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldContainsFold(FieldQrFileID, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldLTE(FieldExpiresAt, v))
}

// ActiveEQ applies the EQ predicate on the "active" field.
func ActiveEQ(v bool) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldEQ(FieldActive, v))
}

// ActiveNEQ applies the NEQ predicate on the "active" field.
func ActiveNEQ(v bool) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.FieldNEQ(FieldActive, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FitnessGroupInvitation) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FitnessGroupInvitation) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FitnessGroupInvitation) predicate.FitnessGroupInvitation {
	return predicate.FitnessGroupInvitation(sql.NotPredicates(p))
}
