// Code generated by ent, DO NOT EDIT.

package hook

import (
	"context"
	"fmt"
	"platform/ent"
)

// The FitnessCheckinFunc type is an adapter to allow the use of ordinary
// function as FitnessCheckin mutator.
type FitnessCheckinFunc func(context.Context, *ent.FitnessCheckinMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f FitnessCheckinFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.FitnessCheckinMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.FitnessCheckinMutation", m)
}

// The FitnessCheckinGroupFunc type is an adapter to allow the use of ordinary
// function as FitnessCheckinGroup mutator.
type FitnessCheckinGroupFunc func(context.Context, *ent.FitnessCheckinGroupMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f FitnessCheckinGroupFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.FitnessCheckinGroupMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.FitnessCheckinGroupMutation", m)
}

// The FitnessCheckinImageFunc type is an adapter to allow the use of ordinary
// function as FitnessCheckinImage mutator.
type FitnessCheckinImageFunc func(context.Context, *ent.FitnessCheckinImageMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f FitnessCheckinImageFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.FitnessCheckinImageMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.FitnessCheckinImageMutation", m)
}

// The FitnessConfigFunc type is an adapter to allow the use of ordinary
// function as FitnessConfig mutator.
type FitnessConfigFunc func(context.Context, *ent.FitnessConfigMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f FitnessConfigFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.FitnessConfigMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.FitnessConfigMutation", m)
}

// The FitnessContentReportFunc type is an adapter to allow the use of ordinary
// function as FitnessContentReport mutator.
type FitnessContentReportFunc func(context.Context, *ent.FitnessContentReportMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f FitnessContentReportFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.FitnessContentReportMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.FitnessContentReportMutation", m)
}

// The FitnessGroupFunc type is an adapter to allow the use of ordinary
// function as FitnessGroup mutator.
type FitnessGroupFunc func(context.Context, *ent.FitnessGroupMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f FitnessGroupFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.FitnessGroupMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.FitnessGroupMutation", m)
}

// The FitnessGroupInvitationFunc type is an adapter to allow the use of ordinary
// function as FitnessGroupInvitation mutator.
type FitnessGroupInvitationFunc func(context.Context, *ent.FitnessGroupInvitationMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f FitnessGroupInvitationFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.FitnessGroupInvitationMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.FitnessGroupInvitationMutation", m)
}

// The FitnessGroupMemberFunc type is an adapter to allow the use of ordinary
// function as FitnessGroupMember mutator.
type FitnessGroupMemberFunc func(context.Context, *ent.FitnessGroupMemberMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f FitnessGroupMemberFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.FitnessGroupMemberMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.FitnessGroupMemberMutation", m)
}

// The FitnessReminderLogFunc type is an adapter to allow the use of ordinary
// function as FitnessReminderLog mutator.
type FitnessReminderLogFunc func(context.Context, *ent.FitnessReminderLogMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f FitnessReminderLogFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.FitnessReminderLogMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.FitnessReminderLogMutation", m)
}

// The FitnessSubscriptionAuthorizationFunc type is an adapter to allow the use of ordinary
// function as FitnessSubscriptionAuthorization mutator.
type FitnessSubscriptionAuthorizationFunc func(context.Context, *ent.FitnessSubscriptionAuthorizationMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f FitnessSubscriptionAuthorizationFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.FitnessSubscriptionAuthorizationMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.FitnessSubscriptionAuthorizationMutation", m)
}

// The SysStorageFileFunc type is an adapter to allow the use of ordinary
// function as SysStorageFile mutator.
type SysStorageFileFunc func(context.Context, *ent.SysStorageFileMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f SysStorageFileFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.SysStorageFileMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.SysStorageFileMutation", m)
}

// The SysUserFunc type is an adapter to allow the use of ordinary
// function as SysUser mutator.
type SysUserFunc func(context.Context, *ent.SysUserMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f SysUserFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.SysUserMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.SysUserMutation", m)
}

// Condition is a hook condition function.
type Condition func(context.Context, ent.Mutation) bool

// And groups conditions with the AND operator.
func And(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		if !first(ctx, m) || !second(ctx, m) {
			return false
		}
		for _, cond := range rest {
			if !cond(ctx, m) {
				return false
			}
		}
		return true
	}
}

// Or groups conditions with the OR operator.
func Or(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		if first(ctx, m) || second(ctx, m) {
			return true
		}
		for _, cond := range rest {
			if cond(ctx, m) {
				return true
			}
		}
		return false
	}
}

// Not negates a given condition.
func Not(cond Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		return !cond(ctx, m)
	}
}

// HasOp is a condition testing mutation operation.
func HasOp(op ent.Op) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		return m.Op().Is(op)
	}
}

// HasAddedFields is a condition validating `.AddedField` on fields.
func HasAddedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if _, exists := m.AddedField(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.AddedField(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasClearedFields is a condition validating `.FieldCleared` on fields.
func HasClearedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if exists := m.FieldCleared(field); !exists {
			return false
		}
		for _, field := range fields {
			if exists := m.FieldCleared(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasFields is a condition validating `.Field` on fields.
func HasFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if _, exists := m.Field(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.Field(field); !exists {
				return false
			}
		}
		return true
	}
}

// If executes the given hook under condition.
//
//	hook.If(ComputeAverage, And(HasFields(...), HasAddedFields(...)))
func If(hk ent.Hook, cond Condition) ent.Hook {
	return func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if cond(ctx, m) {
				return hk(next).Mutate(ctx, m)
			}
			return next.Mutate(ctx, m)
		})
	}
}

// On executes the given hook only for the given operation.
//
//	hook.On(Log, ent.Delete|ent.Create)
func On(hk ent.Hook, op ent.Op) ent.Hook {
	return If(hk, HasOp(op))
}

// Unless skips the given hook only for the given operation.
//
//	hook.Unless(Log, ent.Update|ent.UpdateOne)
func Unless(hk ent.Hook, op ent.Op) ent.Hook {
	return If(hk, Not(HasOp(op)))
}

// FixedError is a hook returning a fixed error.
func FixedError(err error) ent.Hook {
	return func(ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(context.Context, ent.Mutation) (ent.Value, error) {
			return nil, err
		})
	}
}

// Reject returns a hook that rejects all operations that match op.
//
//	func (T) Hooks() []ent.Hook {
//		return []ent.Hook{
//			Reject(ent.Delete|ent.Update),
//		}
//	}
func Reject(op ent.Op) ent.Hook {
	hk := FixedError(fmt.Errorf("%s operation is not allowed", op))
	return On(hk, op)
}

// Chain acts as a list of hooks and is effectively immutable.
// Once created, it will always hold the same set of hooks in the same order.
type Chain struct {
	hooks []ent.Hook
}

// NewChain creates a new chain of hooks.
func NewChain(hooks ...ent.Hook) Chain {
	return Chain{append([]ent.Hook(nil), hooks...)}
}

// Hook chains the list of hooks and returns the final hook.
func (c Chain) Hook() ent.Hook {
	return func(mutator ent.Mutator) ent.Mutator {
		for i := len(c.hooks) - 1; i >= 0; i-- {
			mutator = c.hooks[i](mutator)
		}
		return mutator
	}
}

// Append extends a chain, adding the specified hook
// as the last ones in the mutation flow.
func (c Chain) Append(hooks ...ent.Hook) Chain {
	newHooks := make([]ent.Hook, 0, len(c.hooks)+len(hooks))
	newHooks = append(newHooks, c.hooks...)
	newHooks = append(newHooks, hooks...)
	return Chain{newHooks}
}

// Extend extends a chain, adding the specified chain
// as the last ones in the mutation flow.
func (c Chain) Extend(chain Chain) Chain {
	return c.Append(chain.hooks...)
}
