const base = location.pathname.replace(/\/ops(?:\/.*)?$/, '')
const state = { view: 'dashboard', page: 1, pageSize: 20, keyword: '', status: '' }
const views = [
  ['dashboard','◉','概览','OVERVIEW','今天发生了什么'],
  ['users','人','用户','USERS','用户与账号状态'],
  ['groups','组','小组','GROUPS','小组与成员规模'],
  ['checkins','✓','打卡内容','CONTENT','打卡与安全审核'],
  ['reports','!','举报','REPORTS','待处理内容举报'],
  ['reminders','信','消息记录','MESSAGES','订阅消息发送记录'],
  ['configs','⚙','系统配置','CONFIG','协议、公告与运动类型']
]
const app = document.querySelector('#app'), nav = document.querySelector('#nav')
const keyDialog = document.querySelector('#key-dialog'), keyInput = document.querySelector('#admin-key')

function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function esc(value=''){return String(value).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function date(value){return value?new Date(value*1000).toLocaleString('zh-CN',{hour12:false}):'—'}
function badge(value){return `<span class="badge ${esc(value)}">${esc(value||'—')}</span>`}
function avatar(file,name){return file?.url?`<img class="avatar" src="${esc(file.url)}">`:`<span class="avatar"></span>`}
function api(path,options={}){
  const key=localStorage.getItem('fitness-admin-key')||''
  return fetch(base+path,{...options,headers:{'Content-Type':'application/json','X-Admin-Key':key,...(options.headers||{})}})
    .then(async r=>{const data=await r.json();if(data.code!==0){if(data.code===102004)keyDialog.showModal();throw new Error(data.msg||`请求失败（${data.code}）`)}return data.data})
}
function renderNav(){nav.innerHTML=views.map(([id,icon,label])=>`<button class="nav-item ${state.view===id?'active':''}" data-view="${id}"><span>${icon}</span><label>${label}</label></button>`).join('');nav.querySelectorAll('button').forEach(el=>el.onclick=()=>{state.view=el.dataset.view;state.page=1;state.keyword='';state.status='';render()})}
function header(){const view=views.find(v=>v[0]===state.view);document.querySelector('#eyebrow').textContent=view[3];document.querySelector('#title').textContent=view[4]}
function toolbar(statuses=[]){return `<div class="toolbar"><input id="search" placeholder="搜索名称或关键词" value="${esc(state.keyword)}"><select id="status"><option value="">全部状态</option>${statuses.map(v=>`<option ${state.status===v?'selected':''}>${v}</option>`).join('')}</select><button id="do-search">查询</button><span class="spacer"></span></div>`}
function pager(data){return `<div class="pagination"><span>共 ${data.total} 条 · 第 ${data.page} 页</span><button data-page="${Math.max(1,data.page-1)}">上一页</button><button data-page="${data.page+1}" ${data.page*data.pageSize>=data.total?'disabled':''}>下一页</button></div>`}
function bindList(){document.querySelector('#do-search')?.addEventListener('click',()=>{state.keyword=document.querySelector('#search').value;state.status=document.querySelector('#status').value;state.page=1;render()});document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=Number(b.dataset.page);render()})}
async function dashboard(){const d=await api('/admin/dashboard');app.innerHTML=`<div class="stat-grid">${[['活跃用户',d.users],['活跃小组',d.groups],['今日打卡',d.todayCheckins],['待处理举报',d.pendingReports],['今日提醒',d.todayReminders]].map(([l,v])=>`<div class="stat"><span>${l}</span><strong>${v}</strong></div>`).join('')}</div><div class="panel" style="margin-top:18px"><div style="padding:28px"><h2 style="margin-top:0">运营提示</h2><p style="color:var(--muted)">这里展示的全部是数据库实时数据。优先处理内容举报和发送失败的订阅消息，再关注被禁用用户和违规小组。</p></div></div>`}
async function users(){const d=await api(`/admin/users?page=${state.page}&pageSize=${state.pageSize}&keyword=${encodeURIComponent(state.keyword)}&status=${state.status}`);app.innerHTML=toolbar(['active','disabled'])+`<div class="panel"><table><thead><tr><th>用户</th><th>微信标识</th><th>创建小组</th><th>提醒</th><th>注册时间</th><th>状态</th><th>操作</th></tr></thead><tbody>${d.list.map(x=>`<tr><td><div class="user-cell">${avatar(x.avatar,x.nickname)}<span class="cell-main">${esc(x.nickname)}</span></div></td><td><span class="cell-sub">${esc(x.openid)}</span></td><td>${x.createdGroupCount}</td><td>${x.reminderEnabled?'开启':'关闭'}</td><td>${date(x.createdAt)}</td><td>${badge(x.status)}</td><td><button class="small ${x.status==='active'?'danger':''}" data-user="${x.id}" data-next="${x.status==='active'?'disabled':'active'}">${x.status==='active'?'禁用':'启用'}</button></td></tr>`).join('')}</tbody></table>${pager(d)}</div>`;bindList();document.querySelectorAll('[data-user]').forEach(b=>b.onclick=async()=>{await api(`/admin/users/${b.dataset.user}/status`,{method:'PUT',body:JSON.stringify({status:b.dataset.next})});toast('用户状态已更新');render()})}
async function groups(){const d=await api(`/admin/groups?page=${state.page}&pageSize=${state.pageSize}&keyword=${encodeURIComponent(state.keyword)}&status=${state.status}`);app.innerHTML=toolbar(['active','dissolved','blocked'])+`<div class="panel"><table><thead><tr><th>小组</th><th>管理员</th><th>规模</th><th>周目标</th><th>创建时间</th><th>状态</th><th>操作</th></tr></thead><tbody>${d.list.map(x=>`<tr><td><div class="user-cell">${avatar(x.avatar,x.name)}<span><b>${esc(x.name)}</b><small class="cell-sub">${esc(x.description)}</small></span></div></td><td>${esc(x.ownerName)}</td><td>${x.memberCount} / ${x.memberLimit}</td><td>${x.weeklyTarget} 天</td><td>${date(x.createdAt)}</td><td>${badge(x.status)}</td><td>${x.status==='active'?`<button class="small danger" data-group="${x.id}">解散</button>`:'—'}</td></tr>`).join('')}</tbody></table>${pager(d)}</div>`;bindList();document.querySelectorAll('[data-group]').forEach(b=>b.onclick=async()=>{if(!confirm('确认解散这个小组？'))return;await api(`/admin/groups/${b.dataset.group}`,{method:'DELETE'});toast('小组已解散');render()})}
async function checkins(){const d=await api(`/admin/checkins?page=${state.page}&pageSize=${state.pageSize}&status=${state.status}`);app.innerHTML=toolbar(['pending','approved','rejected'])+`<div class="panel"><table><thead><tr><th>用户 / 日期</th><th>运动</th><th>内容</th><th>发布小组</th><th>审核</th><th>操作</th></tr></thead><tbody>${d.list.map(x=>{const c=x.checkin,s=c.imageAuditSummary||{};return `<tr><td><b>${esc(x.nickname)}</b><small class="cell-sub">${c.date}</small></td><td>${esc(c.exerciseType)} · ${c.durationMinutes} 分钟</td><td><b>${esc(c.mood)}</b><small class="cell-sub">${esc(c.content)}</small><div class="content-images">${(c.images||[]).map(i=>`<img src="${esc(i.url)}">`).join('')}</div></td><td>${(c.groupNames||[]).map(n=>`<span class="badge">${esc(n)}</span>`).join(' ')}</td><td>${badge(c.auditStatus)}${c.auditDetail?`<small class="cell-sub">${esc(c.auditDetail)}</small>`:''}<small class="cell-sub">图片：通过 ${s.approved||0} · 待审 ${s.pending||0} · 拒绝 ${s.rejected||0}</small></td><td><div class="actions">${c.auditStatus!=='approved'?`<button class="small" data-audit="${c.id}" data-result="approved">通过</button>`:''}${c.auditStatus!=='rejected'?`<button class="small ghost" data-audit="${c.id}" data-result="rejected">拒绝</button>`:''}<button class="small danger" data-checkin="${c.id}">删除</button></div></td></tr>`}).join('')}</tbody></table>${pager(d)}</div>`;bindList();document.querySelectorAll('[data-audit]').forEach(b=>b.onclick=async()=>{const approved=b.dataset.result==='approved';const detail=prompt(approved?'可填写审核备注（可留空）':'请填写拒绝原因',approved?'内容审核通过':'');if(detail===null||(!approved&&!detail.trim()))return;await api(`/admin/checkins/${b.dataset.audit}/audit`,{method:'PUT',body:JSON.stringify({status:b.dataset.result,detail:detail.trim()})});toast(approved?'内容已通过审核':'内容已拒绝');render()});document.querySelectorAll('[data-checkin]').forEach(b=>b.onclick=async()=>{if(!confirm('确认永久删除这条违规打卡？相关图片也会从对象存储删除。'))return;await api(`/admin/checkins/${b.dataset.checkin}`,{method:'DELETE'});toast('打卡及关联图片已删除');render()})}
async function reports(){const d=await api(`/admin/reports?page=${state.page}&pageSize=${state.pageSize}&status=${state.status}`);app.innerHTML=toolbar(['pending','resolved','rejected'])+`<div class="panel"><table><thead><tr><th>举报人</th><th>打卡 ID</th><th>原因</th><th>提交时间</th><th>状态</th><th>处理</th></tr></thead><tbody>${d.list.map(x=>`<tr><td>${esc(x.reporterName)}</td><td><span class="cell-sub">${esc(x.checkinId)}</span></td><td>${esc(x.reason)}${x.resolution?`<small class="cell-sub">处理：${esc(x.resolution)}</small>`:''}</td><td>${date(x.createdAt)}</td><td>${badge(x.status)}</td><td>${x.status==='pending'?`<div class="actions"><button class="small" data-report="${x.id}" data-result="resolved">成立</button><button class="small ghost" data-report="${x.id}" data-result="rejected">驳回</button></div>`:'—'}</td></tr>`).join('')}</tbody></table>${pager(d)}</div>`;bindList();document.querySelectorAll('[data-report]').forEach(b=>b.onclick=async()=>{const resolution=prompt('填写处理说明');if(!resolution)return;await api(`/admin/reports/${b.dataset.report}`,{method:'PUT',body:JSON.stringify({status:b.dataset.result,resolution})});toast('举报已处理');render()})}
async function reminders(){const d=await api(`/admin/reminders?page=${state.page}&pageSize=${state.pageSize}&status=${state.status}`);app.innerHTML=toolbar(['sent','failed','skipped'])+`<div class="panel"><table><thead><tr><th>接收用户</th><th>小组</th><th>类型</th><th>日期</th><th>状态</th><th>失败 / 跳过原因</th></tr></thead><tbody>${d.list.map(x=>`<tr><td>${esc(x.targetName)}</td><td>${esc(x.groupName)}</td><td>${esc(x.type)}</td><td>${esc(x.reminderDate)}<small class="cell-sub">${date(x.createdAt)}</small></td><td>${badge(x.status)}</td><td>${esc(x.failureReason||'—')}</td></tr>`).join('')}</tbody></table>${pager(d)}</div>`;bindList()}
async function configs(){const c=await api('/config');const items=[['announcement','全局公告'],['defaultReminderTime','新建小组默认提醒时间'],['userAgreement','用户协议'],['privacyPolicy','隐私政策'],['exerciseTypes','运动类型 JSON']];app.innerHTML=`<div class="config-grid">${items.map(([key,label])=>`<div class="config-card"><h3>${label}</h3><textarea id="config-${key}">${esc(c[key]||'')}</textarea><button data-config="${key}" style="margin-top:10px">保存</button></div>`).join('')}</div>`;document.querySelectorAll('[data-config]').forEach(b=>b.onclick=async()=>{await api(`/admin/configs/${b.dataset.config}`,{method:'PUT',body:JSON.stringify({value:document.querySelector(`#config-${b.dataset.config}`).value})});toast('配置已保存')})}
async function render(){renderNav();header();app.innerHTML='<div class="loading">正在读取真实业务数据…</div>';try{await ({dashboard,users,groups,checkins,reports,reminders,configs}[state.view])()}catch(e){app.innerHTML=`<div class="empty">${esc(e.message)}<br><button style="margin-top:16px" onclick="render()">重新加载</button></div>`}}
document.querySelector('#refresh').onclick=render
document.querySelector('#change-key').onclick=()=>{keyInput.value='';keyDialog.showModal()}
document.querySelector('#save-key').onclick=e=>{e.preventDefault();if(!keyInput.value)return;localStorage.setItem('fitness-admin-key',keyInput.value);keyDialog.close();render()}
if(!localStorage.getItem('fitness-admin-key'))keyDialog.showModal()
render()
