// Code generated by ent, DO NOT EDIT.

package sysuser

import (
	"platform/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.SysUser {
	return predicate.SysUser(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.SysUser {
	return predicate.SysUser(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.SysUser {
	return predicate.SysUser(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.SysUser {
	return predicate.SysUser(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.SysUser {
	return predicate.SysUser(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.SysUser {
	return predicate.SysUser(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.SysUser {
	return predicate.SysUser(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.SysUser {
	return predicate.SysUser(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.SysUser {
	return predicate.SysUser(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.SysUser {
	return predicate.SysUser(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.SysUser {
	return predicate.SysUser(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SysUser {
	return predicate.SysUser(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SysUser {
	return predicate.SysUser(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.SysUser {
	return predicate.SysUser(sql.FieldEQ(FieldDeletedAt, v))
}

// Openid applies equality check predicate on the "openid" field. It's identical to OpenidEQ.
func Openid(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldEQ(FieldOpenid, v))
}

// Unionid applies equality check predicate on the "unionid" field. It's identical to UnionidEQ.
func Unionid(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldEQ(FieldUnionid, v))
}

// Nickname applies equality check predicate on the "nickname" field. It's identical to NicknameEQ.
func Nickname(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldEQ(FieldNickname, v))
}

// AvatarFileID applies equality check predicate on the "avatar_file_id" field. It's identical to AvatarFileIDEQ.
func AvatarFileID(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldEQ(FieldAvatarFileID, v))
}

// ReminderEnabled applies equality check predicate on the "reminder_enabled" field. It's identical to ReminderEnabledEQ.
func ReminderEnabled(v bool) predicate.SysUser {
	return predicate.SysUser(sql.FieldEQ(FieldReminderEnabled, v))
}

// WeightPublic applies equality check predicate on the "weight_public" field. It's identical to WeightPublicEQ.
func WeightPublic(v bool) predicate.SysUser {
	return predicate.SysUser(sql.FieldEQ(FieldWeightPublic, v))
}

// CancelledAt applies equality check predicate on the "cancelled_at" field. It's identical to CancelledAtEQ.
func CancelledAt(v time.Time) predicate.SysUser {
	return predicate.SysUser(sql.FieldEQ(FieldCancelledAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SysUser {
	return predicate.SysUser(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SysUser {
	return predicate.SysUser(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SysUser {
	return predicate.SysUser(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SysUser {
	return predicate.SysUser(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SysUser {
	return predicate.SysUser(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SysUser {
	return predicate.SysUser(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SysUser {
	return predicate.SysUser(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SysUser {
	return predicate.SysUser(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.SysUser {
	return predicate.SysUser(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.SysUser {
	return predicate.SysUser(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SysUser {
	return predicate.SysUser(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SysUser {
	return predicate.SysUser(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SysUser {
	return predicate.SysUser(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SysUser {
	return predicate.SysUser(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SysUser {
	return predicate.SysUser(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SysUser {
	return predicate.SysUser(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SysUser {
	return predicate.SysUser(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SysUser {
	return predicate.SysUser(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.SysUser {
	return predicate.SysUser(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.SysUser {
	return predicate.SysUser(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.SysUser {
	return predicate.SysUser(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.SysUser {
	return predicate.SysUser(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.SysUser {
	return predicate.SysUser(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.SysUser {
	return predicate.SysUser(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.SysUser {
	return predicate.SysUser(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.SysUser {
	return predicate.SysUser(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.SysUser {
	return predicate.SysUser(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.SysUser {
	return predicate.SysUser(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.SysUser {
	return predicate.SysUser(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.SysUser {
	return predicate.SysUser(sql.FieldNotNull(FieldDeletedAt))
}

// OpenidEQ applies the EQ predicate on the "openid" field.
func OpenidEQ(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldEQ(FieldOpenid, v))
}

// OpenidNEQ applies the NEQ predicate on the "openid" field.
func OpenidNEQ(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldNEQ(FieldOpenid, v))
}

// OpenidIn applies the In predicate on the "openid" field.
func OpenidIn(vs ...string) predicate.SysUser {
	return predicate.SysUser(sql.FieldIn(FieldOpenid, vs...))
}

// OpenidNotIn applies the NotIn predicate on the "openid" field.
func OpenidNotIn(vs ...string) predicate.SysUser {
	return predicate.SysUser(sql.FieldNotIn(FieldOpenid, vs...))
}

// OpenidGT applies the GT predicate on the "openid" field.
func OpenidGT(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldGT(FieldOpenid, v))
}

// OpenidGTE applies the GTE predicate on the "openid" field.
func OpenidGTE(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldGTE(FieldOpenid, v))
}

// OpenidLT applies the LT predicate on the "openid" field.
func OpenidLT(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldLT(FieldOpenid, v))
}

// OpenidLTE applies the LTE predicate on the "openid" field.
func OpenidLTE(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldLTE(FieldOpenid, v))
}

// OpenidContains applies the Contains predicate on the "openid" field.
func OpenidContains(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldContains(FieldOpenid, v))
}

// OpenidHasPrefix applies the HasPrefix predicate on the "openid" field.
func OpenidHasPrefix(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldHasPrefix(FieldOpenid, v))
}

// OpenidHasSuffix applies the HasSuffix predicate on the "openid" field.
func OpenidHasSuffix(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldHasSuffix(FieldOpenid, v))
}

// OpenidEqualFold applies the EqualFold predicate on the "openid" field.
func OpenidEqualFold(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldEqualFold(FieldOpenid, v))
}

// OpenidContainsFold applies the ContainsFold predicate on the "openid" field.
func OpenidContainsFold(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldContainsFold(FieldOpenid, v))
}

// UnionidEQ applies the EQ predicate on the "unionid" field.
func UnionidEQ(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldEQ(FieldUnionid, v))
}

// UnionidNEQ applies the NEQ predicate on the "unionid" field.
func UnionidNEQ(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldNEQ(FieldUnionid, v))
}

// UnionidIn applies the In predicate on the "unionid" field.
func UnionidIn(vs ...string) predicate.SysUser {
	return predicate.SysUser(sql.FieldIn(FieldUnionid, vs...))
}

// UnionidNotIn applies the NotIn predicate on the "unionid" field.
func UnionidNotIn(vs ...string) predicate.SysUser {
	return predicate.SysUser(sql.FieldNotIn(FieldUnionid, vs...))
}

// UnionidGT applies the GT predicate on the "unionid" field.
func UnionidGT(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldGT(FieldUnionid, v))
}

// UnionidGTE applies the GTE predicate on the "unionid" field.
func UnionidGTE(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldGTE(FieldUnionid, v))
}

// UnionidLT applies the LT predicate on the "unionid" field.
func UnionidLT(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldLT(FieldUnionid, v))
}

// UnionidLTE applies the LTE predicate on the "unionid" field.
func UnionidLTE(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldLTE(FieldUnionid, v))
}

// UnionidContains applies the Contains predicate on the "unionid" field.
func UnionidContains(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldContains(FieldUnionid, v))
}

// UnionidHasPrefix applies the HasPrefix predicate on the "unionid" field.
func UnionidHasPrefix(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldHasPrefix(FieldUnionid, v))
}

// UnionidHasSuffix applies the HasSuffix predicate on the "unionid" field.
func UnionidHasSuffix(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldHasSuffix(FieldUnionid, v))
}

// UnionidIsNil applies the IsNil predicate on the "unionid" field.
func UnionidIsNil() predicate.SysUser {
	return predicate.SysUser(sql.FieldIsNull(FieldUnionid))
}

// UnionidNotNil applies the NotNil predicate on the "unionid" field.
func UnionidNotNil() predicate.SysUser {
	return predicate.SysUser(sql.FieldNotNull(FieldUnionid))
}

// UnionidEqualFold applies the EqualFold predicate on the "unionid" field.
func UnionidEqualFold(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldEqualFold(FieldUnionid, v))
}

// UnionidContainsFold applies the ContainsFold predicate on the "unionid" field.
func UnionidContainsFold(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldContainsFold(FieldUnionid, v))
}

// NicknameEQ applies the EQ predicate on the "nickname" field.
func NicknameEQ(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldEQ(FieldNickname, v))
}

// NicknameNEQ applies the NEQ predicate on the "nickname" field.
func NicknameNEQ(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldNEQ(FieldNickname, v))
}

// NicknameIn applies the In predicate on the "nickname" field.
func NicknameIn(vs ...string) predicate.SysUser {
	return predicate.SysUser(sql.FieldIn(FieldNickname, vs...))
}

// NicknameNotIn applies the NotIn predicate on the "nickname" field.
func NicknameNotIn(vs ...string) predicate.SysUser {
	return predicate.SysUser(sql.FieldNotIn(FieldNickname, vs...))
}

// NicknameGT applies the GT predicate on the "nickname" field.
func NicknameGT(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldGT(FieldNickname, v))
}

// NicknameGTE applies the GTE predicate on the "nickname" field.
func NicknameGTE(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldGTE(FieldNickname, v))
}

// NicknameLT applies the LT predicate on the "nickname" field.
func NicknameLT(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldLT(FieldNickname, v))
}

// NicknameLTE applies the LTE predicate on the "nickname" field.
func NicknameLTE(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldLTE(FieldNickname, v))
}

// NicknameContains applies the Contains predicate on the "nickname" field.
func NicknameContains(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldContains(FieldNickname, v))
}

// NicknameHasPrefix applies the HasPrefix predicate on the "nickname" field.
func NicknameHasPrefix(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldHasPrefix(FieldNickname, v))
}

// NicknameHasSuffix applies the HasSuffix predicate on the "nickname" field.
func NicknameHasSuffix(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldHasSuffix(FieldNickname, v))
}

// NicknameEqualFold applies the EqualFold predicate on the "nickname" field.
func NicknameEqualFold(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldEqualFold(FieldNickname, v))
}

// NicknameContainsFold applies the ContainsFold predicate on the "nickname" field.
func NicknameContainsFold(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldContainsFold(FieldNickname, v))
}

// AvatarFileIDEQ applies the EQ predicate on the "avatar_file_id" field.
func AvatarFileIDEQ(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldEQ(FieldAvatarFileID, v))
}

// AvatarFileIDNEQ applies the NEQ predicate on the "avatar_file_id" field.
func AvatarFileIDNEQ(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldNEQ(FieldAvatarFileID, v))
}

// AvatarFileIDIn applies the In predicate on the "avatar_file_id" field.
func AvatarFileIDIn(vs ...string) predicate.SysUser {
	return predicate.SysUser(sql.FieldIn(FieldAvatarFileID, vs...))
}

// AvatarFileIDNotIn applies the NotIn predicate on the "avatar_file_id" field.
func AvatarFileIDNotIn(vs ...string) predicate.SysUser {
	return predicate.SysUser(sql.FieldNotIn(FieldAvatarFileID, vs...))
}

// AvatarFileIDGT applies the GT predicate on the "avatar_file_id" field.
func AvatarFileIDGT(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldGT(FieldAvatarFileID, v))
}

// AvatarFileIDGTE applies the GTE predicate on the "avatar_file_id" field.
func AvatarFileIDGTE(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldGTE(FieldAvatarFileID, v))
}

// AvatarFileIDLT applies the LT predicate on the "avatar_file_id" field.
func AvatarFileIDLT(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldLT(FieldAvatarFileID, v))
}

// AvatarFileIDLTE applies the LTE predicate on the "avatar_file_id" field.
func AvatarFileIDLTE(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldLTE(FieldAvatarFileID, v))
}

// AvatarFileIDContains applies the Contains predicate on the "avatar_file_id" field.
func AvatarFileIDContains(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldContains(FieldAvatarFileID, v))
}

// AvatarFileIDHasPrefix applies the HasPrefix predicate on the "avatar_file_id" field.
func AvatarFileIDHasPrefix(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldHasPrefix(FieldAvatarFileID, v))
}

// AvatarFileIDHasSuffix applies the HasSuffix predicate on the "avatar_file_id" field.
func AvatarFileIDHasSuffix(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldHasSuffix(FieldAvatarFileID, v))
}

// AvatarFileIDIsNil applies the IsNil predicate on the "avatar_file_id" field.
func AvatarFileIDIsNil() predicate.SysUser {
	return predicate.SysUser(sql.FieldIsNull(FieldAvatarFileID))
}

// AvatarFileIDNotNil applies the NotNil predicate on the "avatar_file_id" field.
func AvatarFileIDNotNil() predicate.SysUser {
	return predicate.SysUser(sql.FieldNotNull(FieldAvatarFileID))
}

// AvatarFileIDEqualFold applies the EqualFold predicate on the "avatar_file_id" field.
func AvatarFileIDEqualFold(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldEqualFold(FieldAvatarFileID, v))
}

// AvatarFileIDContainsFold applies the ContainsFold predicate on the "avatar_file_id" field.
func AvatarFileIDContainsFold(v string) predicate.SysUser {
	return predicate.SysUser(sql.FieldContainsFold(FieldAvatarFileID, v))
}

// ReminderEnabledEQ applies the EQ predicate on the "reminder_enabled" field.
func ReminderEnabledEQ(v bool) predicate.SysUser {
	return predicate.SysUser(sql.FieldEQ(FieldReminderEnabled, v))
}

// ReminderEnabledNEQ applies the NEQ predicate on the "reminder_enabled" field.
func ReminderEnabledNEQ(v bool) predicate.SysUser {
	return predicate.SysUser(sql.FieldNEQ(FieldReminderEnabled, v))
}

// WeightPublicEQ applies the EQ predicate on the "weight_public" field.
func WeightPublicEQ(v bool) predicate.SysUser {
	return predicate.SysUser(sql.FieldEQ(FieldWeightPublic, v))
}

// WeightPublicNEQ applies the NEQ predicate on the "weight_public" field.
func WeightPublicNEQ(v bool) predicate.SysUser {
	return predicate.SysUser(sql.FieldNEQ(FieldWeightPublic, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.SysUser {
	return predicate.SysUser(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.SysUser {
	return predicate.SysUser(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.SysUser {
	return predicate.SysUser(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.SysUser {
	return predicate.SysUser(sql.FieldNotIn(FieldStatus, vs...))
}

// CancelledAtEQ applies the EQ predicate on the "cancelled_at" field.
func CancelledAtEQ(v time.Time) predicate.SysUser {
	return predicate.SysUser(sql.FieldEQ(FieldCancelledAt, v))
}

// CancelledAtNEQ applies the NEQ predicate on the "cancelled_at" field.
func CancelledAtNEQ(v time.Time) predicate.SysUser {
	return predicate.SysUser(sql.FieldNEQ(FieldCancelledAt, v))
}

// CancelledAtIn applies the In predicate on the "cancelled_at" field.
func CancelledAtIn(vs ...time.Time) predicate.SysUser {
	return predicate.SysUser(sql.FieldIn(FieldCancelledAt, vs...))
}

// CancelledAtNotIn applies the NotIn predicate on the "cancelled_at" field.
func CancelledAtNotIn(vs ...time.Time) predicate.SysUser {
	return predicate.SysUser(sql.FieldNotIn(FieldCancelledAt, vs...))
}

// CancelledAtGT applies the GT predicate on the "cancelled_at" field.
func CancelledAtGT(v time.Time) predicate.SysUser {
	return predicate.SysUser(sql.FieldGT(FieldCancelledAt, v))
}

// CancelledAtGTE applies the GTE predicate on the "cancelled_at" field.
func CancelledAtGTE(v time.Time) predicate.SysUser {
	return predicate.SysUser(sql.FieldGTE(FieldCancelledAt, v))
}

// CancelledAtLT applies the LT predicate on the "cancelled_at" field.
func CancelledAtLT(v time.Time) predicate.SysUser {
	return predicate.SysUser(sql.FieldLT(FieldCancelledAt, v))
}

// CancelledAtLTE applies the LTE predicate on the "cancelled_at" field.
func CancelledAtLTE(v time.Time) predicate.SysUser {
	return predicate.SysUser(sql.FieldLTE(FieldCancelledAt, v))
}

// CancelledAtIsNil applies the IsNil predicate on the "cancelled_at" field.
func CancelledAtIsNil() predicate.SysUser {
	return predicate.SysUser(sql.FieldIsNull(FieldCancelledAt))
}

// CancelledAtNotNil applies the NotNil predicate on the "cancelled_at" field.
func CancelledAtNotNil() predicate.SysUser {
	return predicate.SysUser(sql.FieldNotNull(FieldCancelledAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SysUser) predicate.SysUser {
	return predicate.SysUser(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SysUser) predicate.SysUser {
	return predicate.SysUser(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SysUser) predicate.SysUser {
	return predicate.SysUser(sql.NotPredicates(p))
}
