// Code generated by ent, DO NOT EDIT.

package fitnesscontentreport

import (
	"fmt"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the fitnesscontentreport type in the database.
	Label = "fitness_content_report"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldReporterUserID holds the string denoting the reporter_user_id field in the database.
	FieldReporterUserID = "reporter_user_id"
	// FieldCheckinID holds the string denoting the checkin_id field in the database.
	FieldCheckinID = "checkin_id"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldHandlerUserID holds the string denoting the handler_user_id field in the database.
	FieldHandlerUserID = "handler_user_id"
	// FieldResolution holds the string denoting the resolution field in the database.
	FieldResolution = "resolution"
	// Table holds the table name of the fitnesscontentreport in the database.
	Table = "fitness_content_reports"
)

// Columns holds all SQL columns for fitnesscontentreport fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldReporterUserID,
	FieldCheckinID,
	FieldReason,
	FieldStatus,
	FieldHandlerUserID,
	FieldResolution,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "platform/ent/runtime"
var (
	Hooks [2]ent.Hook
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// ReasonValidator is a validator for the "reason" field. It is called by the builders before save.
	ReasonValidator func(string) error
	// ResolutionValidator is a validator for the "resolution" field. It is called by the builders before save.
	ResolutionValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// Status defines the type for the "status" enum field.
type Status string

// StatusPending is the default value of the Status enum.
const DefaultStatus = StatusPending

// Status values.
const (
	StatusPending  Status = "pending"
	StatusResolved Status = "resolved"
	StatusRejected Status = "rejected"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPending, StatusResolved, StatusRejected:
		return nil
	default:
		return fmt.Errorf("fitnesscontentreport: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the FitnessContentReport queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByReporterUserID orders the results by the reporter_user_id field.
func ByReporterUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReporterUserID, opts...).ToFunc()
}

// ByCheckinID orders the results by the checkin_id field.
func ByCheckinID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCheckinID, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByHandlerUserID orders the results by the handler_user_id field.
func ByHandlerUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHandlerUserID, opts...).ToFunc()
}

// ByResolution orders the results by the resolution field.
func ByResolution(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResolution, opts...).ToFunc()
}
