// Code generated by ent, DO NOT EDIT.

package fitnesscontentreport

import (
	"platform/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldEQ(FieldDeletedAt, v))
}

// ReporterUserID applies equality check predicate on the "reporter_user_id" field. It's identical to ReporterUserIDEQ.
func ReporterUserID(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldEQ(FieldReporterUserID, v))
}

// CheckinID applies equality check predicate on the "checkin_id" field. It's identical to CheckinIDEQ.
func CheckinID(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldEQ(FieldCheckinID, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldEQ(FieldReason, v))
}

// HandlerUserID applies equality check predicate on the "handler_user_id" field. It's identical to HandlerUserIDEQ.
func HandlerUserID(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldEQ(FieldHandlerUserID, v))
}

// Resolution applies equality check predicate on the "resolution" field. It's identical to ResolutionEQ.
func Resolution(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldEQ(FieldResolution, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldNotNull(FieldDeletedAt))
}

// ReporterUserIDEQ applies the EQ predicate on the "reporter_user_id" field.
func ReporterUserIDEQ(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldEQ(FieldReporterUserID, v))
}

// ReporterUserIDNEQ applies the NEQ predicate on the "reporter_user_id" field.
func ReporterUserIDNEQ(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldNEQ(FieldReporterUserID, v))
}

// ReporterUserIDIn applies the In predicate on the "reporter_user_id" field.
func ReporterUserIDIn(vs ...string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldIn(FieldReporterUserID, vs...))
}

// ReporterUserIDNotIn applies the NotIn predicate on the "reporter_user_id" field.
func ReporterUserIDNotIn(vs ...string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldNotIn(FieldReporterUserID, vs...))
}

// ReporterUserIDGT applies the GT predicate on the "reporter_user_id" field.
func ReporterUserIDGT(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldGT(FieldReporterUserID, v))
}

// ReporterUserIDGTE applies the GTE predicate on the "reporter_user_id" field.
func ReporterUserIDGTE(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldGTE(FieldReporterUserID, v))
}

// ReporterUserIDLT applies the LT predicate on the "reporter_user_id" field.
func ReporterUserIDLT(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldLT(FieldReporterUserID, v))
}

// ReporterUserIDLTE applies the LTE predicate on the "reporter_user_id" field.
func ReporterUserIDLTE(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldLTE(FieldReporterUserID, v))
}

// ReporterUserIDContains applies the Contains predicate on the "reporter_user_id" field.
func ReporterUserIDContains(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldContains(FieldReporterUserID, v))
}

// ReporterUserIDHasPrefix applies the HasPrefix predicate on the "reporter_user_id" field.
func ReporterUserIDHasPrefix(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldHasPrefix(FieldReporterUserID, v))
}

// ReporterUserIDHasSuffix applies the HasSuffix predicate on the "reporter_user_id" field.
func ReporterUserIDHasSuffix(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldHasSuffix(FieldReporterUserID, v))
}

// ReporterUserIDEqualFold applies the EqualFold predicate on the "reporter_user_id" field.
func ReporterUserIDEqualFold(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldEqualFold(FieldReporterUserID, v))
}

// ReporterUserIDContainsFold applies the ContainsFold predicate on the "reporter_user_id" field.
func ReporterUserIDContainsFold(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldContainsFold(FieldReporterUserID, v))
}

// CheckinIDEQ applies the EQ predicate on the "checkin_id" field.
func CheckinIDEQ(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldEQ(FieldCheckinID, v))
}

// CheckinIDNEQ applies the NEQ predicate on the "checkin_id" field.
func CheckinIDNEQ(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldNEQ(FieldCheckinID, v))
}

// CheckinIDIn applies the In predicate on the "checkin_id" field.
func CheckinIDIn(vs ...string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldIn(FieldCheckinID, vs...))
}

// CheckinIDNotIn applies the NotIn predicate on the "checkin_id" field.
func CheckinIDNotIn(vs ...string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldNotIn(FieldCheckinID, vs...))
}

// CheckinIDGT applies the GT predicate on the "checkin_id" field.
func CheckinIDGT(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldGT(FieldCheckinID, v))
}

// CheckinIDGTE applies the GTE predicate on the "checkin_id" field.
func CheckinIDGTE(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldGTE(FieldCheckinID, v))
}

// CheckinIDLT applies the LT predicate on the "checkin_id" field.
func CheckinIDLT(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldLT(FieldCheckinID, v))
}

// CheckinIDLTE applies the LTE predicate on the "checkin_id" field.
func CheckinIDLTE(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldLTE(FieldCheckinID, v))
}

// CheckinIDContains applies the Contains predicate on the "checkin_id" field.
func CheckinIDContains(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldContains(FieldCheckinID, v))
}

// CheckinIDHasPrefix applies the HasPrefix predicate on the "checkin_id" field.
func CheckinIDHasPrefix(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldHasPrefix(FieldCheckinID, v))
}

// CheckinIDHasSuffix applies the HasSuffix predicate on the "checkin_id" field.
func CheckinIDHasSuffix(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldHasSuffix(FieldCheckinID, v))
}

// CheckinIDEqualFold applies the EqualFold predicate on the "checkin_id" field.
func CheckinIDEqualFold(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldEqualFold(FieldCheckinID, v))
}

// CheckinIDContainsFold applies the ContainsFold predicate on the "checkin_id" field.
func CheckinIDContainsFold(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldContainsFold(FieldCheckinID, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldContainsFold(FieldReason, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldNotIn(FieldStatus, vs...))
}

// HandlerUserIDEQ applies the EQ predicate on the "handler_user_id" field.
func HandlerUserIDEQ(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldEQ(FieldHandlerUserID, v))
}

// HandlerUserIDNEQ applies the NEQ predicate on the "handler_user_id" field.
func HandlerUserIDNEQ(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldNEQ(FieldHandlerUserID, v))
}

// HandlerUserIDIn applies the In predicate on the "handler_user_id" field.
func HandlerUserIDIn(vs ...string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldIn(FieldHandlerUserID, vs...))
}

// HandlerUserIDNotIn applies the NotIn predicate on the "handler_user_id" field.
func HandlerUserIDNotIn(vs ...string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldNotIn(FieldHandlerUserID, vs...))
}

// HandlerUserIDGT applies the GT predicate on the "handler_user_id" field.
func HandlerUserIDGT(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldGT(FieldHandlerUserID, v))
}

// HandlerUserIDGTE applies the GTE predicate on the "handler_user_id" field.
func HandlerUserIDGTE(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldGTE(FieldHandlerUserID, v))
}

// HandlerUserIDLT applies the LT predicate on the "handler_user_id" field.
func HandlerUserIDLT(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldLT(FieldHandlerUserID, v))
}

// HandlerUserIDLTE applies the LTE predicate on the "handler_user_id" field.
func HandlerUserIDLTE(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldLTE(FieldHandlerUserID, v))
}

// HandlerUserIDContains applies the Contains predicate on the "handler_user_id" field.
func HandlerUserIDContains(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldContains(FieldHandlerUserID, v))
}

// HandlerUserIDHasPrefix applies the HasPrefix predicate on the "handler_user_id" field.
func HandlerUserIDHasPrefix(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldHasPrefix(FieldHandlerUserID, v))
}

// HandlerUserIDHasSuffix applies the HasSuffix predicate on the "handler_user_id" field.
func HandlerUserIDHasSuffix(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldHasSuffix(FieldHandlerUserID, v))
}

// HandlerUserIDIsNil applies the IsNil predicate on the "handler_user_id" field.
func HandlerUserIDIsNil() predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldIsNull(FieldHandlerUserID))
}

// HandlerUserIDNotNil applies the NotNil predicate on the "handler_user_id" field.
func HandlerUserIDNotNil() predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldNotNull(FieldHandlerUserID))
}

// HandlerUserIDEqualFold applies the EqualFold predicate on the "handler_user_id" field.
func HandlerUserIDEqualFold(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldEqualFold(FieldHandlerUserID, v))
}

// HandlerUserIDContainsFold applies the ContainsFold predicate on the "handler_user_id" field.
func HandlerUserIDContainsFold(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldContainsFold(FieldHandlerUserID, v))
}

// ResolutionEQ applies the EQ predicate on the "resolution" field.
func ResolutionEQ(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldEQ(FieldResolution, v))
}

// ResolutionNEQ applies the NEQ predicate on the "resolution" field.
func ResolutionNEQ(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldNEQ(FieldResolution, v))
}

// ResolutionIn applies the In predicate on the "resolution" field.
func ResolutionIn(vs ...string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldIn(FieldResolution, vs...))
}

// ResolutionNotIn applies the NotIn predicate on the "resolution" field.
func ResolutionNotIn(vs ...string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldNotIn(FieldResolution, vs...))
}

// ResolutionGT applies the GT predicate on the "resolution" field.
func ResolutionGT(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldGT(FieldResolution, v))
}

// ResolutionGTE applies the GTE predicate on the "resolution" field.
func ResolutionGTE(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldGTE(FieldResolution, v))
}

// ResolutionLT applies the LT predicate on the "resolution" field.
func ResolutionLT(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldLT(FieldResolution, v))
}

// ResolutionLTE applies the LTE predicate on the "resolution" field.
func ResolutionLTE(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldLTE(FieldResolution, v))
}

// ResolutionContains applies the Contains predicate on the "resolution" field.
func ResolutionContains(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldContains(FieldResolution, v))
}

// ResolutionHasPrefix applies the HasPrefix predicate on the "resolution" field.
func ResolutionHasPrefix(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldHasPrefix(FieldResolution, v))
}

// ResolutionHasSuffix applies the HasSuffix predicate on the "resolution" field.
func ResolutionHasSuffix(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldHasSuffix(FieldResolution, v))
}

// ResolutionIsNil applies the IsNil predicate on the "resolution" field.
func ResolutionIsNil() predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldIsNull(FieldResolution))
}

// ResolutionNotNil applies the NotNil predicate on the "resolution" field.
func ResolutionNotNil() predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldNotNull(FieldResolution))
}

// ResolutionEqualFold applies the EqualFold predicate on the "resolution" field.
func ResolutionEqualFold(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldEqualFold(FieldResolution, v))
}

// ResolutionContainsFold applies the ContainsFold predicate on the "resolution" field.
func ResolutionContainsFold(v string) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.FieldContainsFold(FieldResolution, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FitnessContentReport) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FitnessContentReport) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FitnessContentReport) predicate.FitnessContentReport {
	return predicate.FitnessContentReport(sql.NotPredicates(p))
}
