// Code generated by ent, DO NOT EDIT.

package fitnessreminderlog

import (
	"platform/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldEQ(FieldDeletedAt, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldEQ(FieldGroupID, v))
}

// TargetUserID applies equality check predicate on the "target_user_id" field. It's identical to TargetUserIDEQ.
func TargetUserID(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldEQ(FieldTargetUserID, v))
}

// SenderUserID applies equality check predicate on the "sender_user_id" field. It's identical to SenderUserIDEQ.
func SenderUserID(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldEQ(FieldSenderUserID, v))
}

// ReminderDate applies equality check predicate on the "reminder_date" field. It's identical to ReminderDateEQ.
func ReminderDate(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldEQ(FieldReminderDate, v))
}

// FailureReason applies equality check predicate on the "failure_reason" field. It's identical to FailureReasonEQ.
func FailureReason(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldEQ(FieldFailureReason, v))
}

// WechatMsgID applies equality check predicate on the "wechat_msg_id" field. It's identical to WechatMsgIDEQ.
func WechatMsgID(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldEQ(FieldWechatMsgID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldNotNull(FieldDeletedAt))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldLTE(FieldGroupID, v))
}

// GroupIDContains applies the Contains predicate on the "group_id" field.
func GroupIDContains(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldContains(FieldGroupID, v))
}

// GroupIDHasPrefix applies the HasPrefix predicate on the "group_id" field.
func GroupIDHasPrefix(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldHasPrefix(FieldGroupID, v))
}

// GroupIDHasSuffix applies the HasSuffix predicate on the "group_id" field.
func GroupIDHasSuffix(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldHasSuffix(FieldGroupID, v))
}

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldIsNull(FieldGroupID))
}

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldNotNull(FieldGroupID))
}

// GroupIDEqualFold applies the EqualFold predicate on the "group_id" field.
func GroupIDEqualFold(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldEqualFold(FieldGroupID, v))
}

// GroupIDContainsFold applies the ContainsFold predicate on the "group_id" field.
func GroupIDContainsFold(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldContainsFold(FieldGroupID, v))
}

// TargetUserIDEQ applies the EQ predicate on the "target_user_id" field.
func TargetUserIDEQ(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldEQ(FieldTargetUserID, v))
}

// TargetUserIDNEQ applies the NEQ predicate on the "target_user_id" field.
func TargetUserIDNEQ(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldNEQ(FieldTargetUserID, v))
}

// TargetUserIDIn applies the In predicate on the "target_user_id" field.
func TargetUserIDIn(vs ...string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldIn(FieldTargetUserID, vs...))
}

// TargetUserIDNotIn applies the NotIn predicate on the "target_user_id" field.
func TargetUserIDNotIn(vs ...string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldNotIn(FieldTargetUserID, vs...))
}

// TargetUserIDGT applies the GT predicate on the "target_user_id" field.
func TargetUserIDGT(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldGT(FieldTargetUserID, v))
}

// TargetUserIDGTE applies the GTE predicate on the "target_user_id" field.
func TargetUserIDGTE(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldGTE(FieldTargetUserID, v))
}

// TargetUserIDLT applies the LT predicate on the "target_user_id" field.
func TargetUserIDLT(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldLT(FieldTargetUserID, v))
}

// TargetUserIDLTE applies the LTE predicate on the "target_user_id" field.
func TargetUserIDLTE(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldLTE(FieldTargetUserID, v))
}

// TargetUserIDContains applies the Contains predicate on the "target_user_id" field.
func TargetUserIDContains(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldContains(FieldTargetUserID, v))
}

// TargetUserIDHasPrefix applies the HasPrefix predicate on the "target_user_id" field.
func TargetUserIDHasPrefix(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldHasPrefix(FieldTargetUserID, v))
}

// TargetUserIDHasSuffix applies the HasSuffix predicate on the "target_user_id" field.
func TargetUserIDHasSuffix(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldHasSuffix(FieldTargetUserID, v))
}

// TargetUserIDEqualFold applies the EqualFold predicate on the "target_user_id" field.
func TargetUserIDEqualFold(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldEqualFold(FieldTargetUserID, v))
}

// TargetUserIDContainsFold applies the ContainsFold predicate on the "target_user_id" field.
func TargetUserIDContainsFold(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldContainsFold(FieldTargetUserID, v))
}

// SenderUserIDEQ applies the EQ predicate on the "sender_user_id" field.
func SenderUserIDEQ(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldEQ(FieldSenderUserID, v))
}

// SenderUserIDNEQ applies the NEQ predicate on the "sender_user_id" field.
func SenderUserIDNEQ(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldNEQ(FieldSenderUserID, v))
}

// SenderUserIDIn applies the In predicate on the "sender_user_id" field.
func SenderUserIDIn(vs ...string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldIn(FieldSenderUserID, vs...))
}

// SenderUserIDNotIn applies the NotIn predicate on the "sender_user_id" field.
func SenderUserIDNotIn(vs ...string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldNotIn(FieldSenderUserID, vs...))
}

// SenderUserIDGT applies the GT predicate on the "sender_user_id" field.
func SenderUserIDGT(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldGT(FieldSenderUserID, v))
}

// SenderUserIDGTE applies the GTE predicate on the "sender_user_id" field.
func SenderUserIDGTE(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldGTE(FieldSenderUserID, v))
}

// SenderUserIDLT applies the LT predicate on the "sender_user_id" field.
func SenderUserIDLT(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldLT(FieldSenderUserID, v))
}

// SenderUserIDLTE applies the LTE predicate on the "sender_user_id" field.
func SenderUserIDLTE(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldLTE(FieldSenderUserID, v))
}

// SenderUserIDContains applies the Contains predicate on the "sender_user_id" field.
func SenderUserIDContains(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldContains(FieldSenderUserID, v))
}

// SenderUserIDHasPrefix applies the HasPrefix predicate on the "sender_user_id" field.
func SenderUserIDHasPrefix(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldHasPrefix(FieldSenderUserID, v))
}

// SenderUserIDHasSuffix applies the HasSuffix predicate on the "sender_user_id" field.
func SenderUserIDHasSuffix(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldHasSuffix(FieldSenderUserID, v))
}

// SenderUserIDIsNil applies the IsNil predicate on the "sender_user_id" field.
func SenderUserIDIsNil() predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldIsNull(FieldSenderUserID))
}

// SenderUserIDNotNil applies the NotNil predicate on the "sender_user_id" field.
func SenderUserIDNotNil() predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldNotNull(FieldSenderUserID))
}

// SenderUserIDEqualFold applies the EqualFold predicate on the "sender_user_id" field.
func SenderUserIDEqualFold(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldEqualFold(FieldSenderUserID, v))
}

// SenderUserIDContainsFold applies the ContainsFold predicate on the "sender_user_id" field.
func SenderUserIDContainsFold(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldContainsFold(FieldSenderUserID, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldNotIn(FieldType, vs...))
}

// ReminderDateEQ applies the EQ predicate on the "reminder_date" field.
func ReminderDateEQ(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldEQ(FieldReminderDate, v))
}

// ReminderDateNEQ applies the NEQ predicate on the "reminder_date" field.
func ReminderDateNEQ(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldNEQ(FieldReminderDate, v))
}

// ReminderDateIn applies the In predicate on the "reminder_date" field.
func ReminderDateIn(vs ...string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldIn(FieldReminderDate, vs...))
}

// ReminderDateNotIn applies the NotIn predicate on the "reminder_date" field.
func ReminderDateNotIn(vs ...string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldNotIn(FieldReminderDate, vs...))
}

// ReminderDateGT applies the GT predicate on the "reminder_date" field.
func ReminderDateGT(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldGT(FieldReminderDate, v))
}

// ReminderDateGTE applies the GTE predicate on the "reminder_date" field.
func ReminderDateGTE(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldGTE(FieldReminderDate, v))
}

// ReminderDateLT applies the LT predicate on the "reminder_date" field.
func ReminderDateLT(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldLT(FieldReminderDate, v))
}

// ReminderDateLTE applies the LTE predicate on the "reminder_date" field.
func ReminderDateLTE(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldLTE(FieldReminderDate, v))
}

// ReminderDateContains applies the Contains predicate on the "reminder_date" field.
func ReminderDateContains(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldContains(FieldReminderDate, v))
}

// ReminderDateHasPrefix applies the HasPrefix predicate on the "reminder_date" field.
func ReminderDateHasPrefix(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldHasPrefix(FieldReminderDate, v))
}

// ReminderDateHasSuffix applies the HasSuffix predicate on the "reminder_date" field.
func ReminderDateHasSuffix(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldHasSuffix(FieldReminderDate, v))
}

// ReminderDateEqualFold applies the EqualFold predicate on the "reminder_date" field.
func ReminderDateEqualFold(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldEqualFold(FieldReminderDate, v))
}

// ReminderDateContainsFold applies the ContainsFold predicate on the "reminder_date" field.
func ReminderDateContainsFold(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldContainsFold(FieldReminderDate, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldNotIn(FieldStatus, vs...))
}

// FailureReasonEQ applies the EQ predicate on the "failure_reason" field.
func FailureReasonEQ(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldEQ(FieldFailureReason, v))
}

// FailureReasonNEQ applies the NEQ predicate on the "failure_reason" field.
func FailureReasonNEQ(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldNEQ(FieldFailureReason, v))
}

// FailureReasonIn applies the In predicate on the "failure_reason" field.
func FailureReasonIn(vs ...string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldIn(FieldFailureReason, vs...))
}

// FailureReasonNotIn applies the NotIn predicate on the "failure_reason" field.
func FailureReasonNotIn(vs ...string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldNotIn(FieldFailureReason, vs...))
}

// FailureReasonGT applies the GT predicate on the "failure_reason" field.
func FailureReasonGT(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldGT(FieldFailureReason, v))
}

// FailureReasonGTE applies the GTE predicate on the "failure_reason" field.
func FailureReasonGTE(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldGTE(FieldFailureReason, v))
}

// FailureReasonLT applies the LT predicate on the "failure_reason" field.
func FailureReasonLT(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldLT(FieldFailureReason, v))
}

// FailureReasonLTE applies the LTE predicate on the "failure_reason" field.
func FailureReasonLTE(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldLTE(FieldFailureReason, v))
}

// FailureReasonContains applies the Contains predicate on the "failure_reason" field.
func FailureReasonContains(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldContains(FieldFailureReason, v))
}

// FailureReasonHasPrefix applies the HasPrefix predicate on the "failure_reason" field.
func FailureReasonHasPrefix(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldHasPrefix(FieldFailureReason, v))
}

// FailureReasonHasSuffix applies the HasSuffix predicate on the "failure_reason" field.
func FailureReasonHasSuffix(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldHasSuffix(FieldFailureReason, v))
}

// FailureReasonIsNil applies the IsNil predicate on the "failure_reason" field.
func FailureReasonIsNil() predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldIsNull(FieldFailureReason))
}

// FailureReasonNotNil applies the NotNil predicate on the "failure_reason" field.
func FailureReasonNotNil() predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldNotNull(FieldFailureReason))
}

// FailureReasonEqualFold applies the EqualFold predicate on the "failure_reason" field.
func FailureReasonEqualFold(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldEqualFold(FieldFailureReason, v))
}

// FailureReasonContainsFold applies the ContainsFold predicate on the "failure_reason" field.
func FailureReasonContainsFold(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldContainsFold(FieldFailureReason, v))
}

// WechatMsgIDEQ applies the EQ predicate on the "wechat_msg_id" field.
func WechatMsgIDEQ(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldEQ(FieldWechatMsgID, v))
}

// WechatMsgIDNEQ applies the NEQ predicate on the "wechat_msg_id" field.
func WechatMsgIDNEQ(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldNEQ(FieldWechatMsgID, v))
}

// WechatMsgIDIn applies the In predicate on the "wechat_msg_id" field.
func WechatMsgIDIn(vs ...string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldIn(FieldWechatMsgID, vs...))
}

// WechatMsgIDNotIn applies the NotIn predicate on the "wechat_msg_id" field.
func WechatMsgIDNotIn(vs ...string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldNotIn(FieldWechatMsgID, vs...))
}

// WechatMsgIDGT applies the GT predicate on the "wechat_msg_id" field.
func WechatMsgIDGT(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldGT(FieldWechatMsgID, v))
}

// WechatMsgIDGTE applies the GTE predicate on the "wechat_msg_id" field.
func WechatMsgIDGTE(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldGTE(FieldWechatMsgID, v))
}

// WechatMsgIDLT applies the LT predicate on the "wechat_msg_id" field.
func WechatMsgIDLT(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldLT(FieldWechatMsgID, v))
}

// WechatMsgIDLTE applies the LTE predicate on the "wechat_msg_id" field.
func WechatMsgIDLTE(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldLTE(FieldWechatMsgID, v))
}

// WechatMsgIDContains applies the Contains predicate on the "wechat_msg_id" field.
func WechatMsgIDContains(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldContains(FieldWechatMsgID, v))
}

// WechatMsgIDHasPrefix applies the HasPrefix predicate on the "wechat_msg_id" field.
func WechatMsgIDHasPrefix(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldHasPrefix(FieldWechatMsgID, v))
}

// WechatMsgIDHasSuffix applies the HasSuffix predicate on the "wechat_msg_id" field.
func WechatMsgIDHasSuffix(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldHasSuffix(FieldWechatMsgID, v))
}

// WechatMsgIDIsNil applies the IsNil predicate on the "wechat_msg_id" field.
func WechatMsgIDIsNil() predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldIsNull(FieldWechatMsgID))
}

// WechatMsgIDNotNil applies the NotNil predicate on the "wechat_msg_id" field.
func WechatMsgIDNotNil() predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldNotNull(FieldWechatMsgID))
}

// WechatMsgIDEqualFold applies the EqualFold predicate on the "wechat_msg_id" field.
func WechatMsgIDEqualFold(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldEqualFold(FieldWechatMsgID, v))
}

// WechatMsgIDContainsFold applies the ContainsFold predicate on the "wechat_msg_id" field.
func WechatMsgIDContainsFold(v string) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.FieldContainsFold(FieldWechatMsgID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FitnessReminderLog) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FitnessReminderLog) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FitnessReminderLog) predicate.FitnessReminderLog {
	return predicate.FitnessReminderLog(sql.NotPredicates(p))
}
