// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"platform/ent/fitnessgroupmember"
	"platform/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FitnessGroupMemberDelete is the builder for deleting a FitnessGroupMember entity.
type FitnessGroupMemberDelete struct {
	config
	hooks    []Hook
	mutation *FitnessGroupMemberMutation
}

// Where appends a list predicates to the FitnessGroupMemberDelete builder.
func (_d *FitnessGroupMemberDelete) Where(ps ...predicate.FitnessGroupMember) *FitnessGroupMemberDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *FitnessGroupMemberDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *FitnessGroupMemberDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *FitnessGroupMemberDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(fitnessgroupmember.Table, sqlgraph.NewFieldSpec(fitnessgroupmember.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// FitnessGroupMemberDeleteOne is the builder for deleting a single FitnessGroupMember entity.
type FitnessGroupMemberDeleteOne struct {
	_d *FitnessGroupMemberDelete
}

// Where appends a list predicates to the FitnessGroupMemberDelete builder.
func (_d *FitnessGroupMemberDeleteOne) Where(ps ...predicate.FitnessGroupMember) *FitnessGroupMemberDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *FitnessGroupMemberDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{fitnessgroupmember.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *FitnessGroupMemberDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
