// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"platform/ent/fitnesscheckin"
	"platform/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FitnessCheckinUpdate is the builder for updating FitnessCheckin entities.
type FitnessCheckinUpdate struct {
	config
	hooks    []Hook
	mutation *FitnessCheckinMutation
}

// Where appends a list predicates to the FitnessCheckinUpdate builder.
func (_u *FitnessCheckinUpdate) Where(ps ...predicate.FitnessCheckin) *FitnessCheckinUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *FitnessCheckinUpdate) SetCreatedAt(v time.Time) *FitnessCheckinUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *FitnessCheckinUpdate) SetNillableCreatedAt(v *time.Time) *FitnessCheckinUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *FitnessCheckinUpdate) ClearCreatedAt() *FitnessCheckinUpdate {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FitnessCheckinUpdate) SetUpdatedAt(v time.Time) *FitnessCheckinUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *FitnessCheckinUpdate) SetNillableUpdatedAt(v *time.Time) *FitnessCheckinUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *FitnessCheckinUpdate) ClearUpdatedAt() *FitnessCheckinUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *FitnessCheckinUpdate) SetDeletedAt(v time.Time) *FitnessCheckinUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *FitnessCheckinUpdate) SetNillableDeletedAt(v *time.Time) *FitnessCheckinUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *FitnessCheckinUpdate) ClearDeletedAt() *FitnessCheckinUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *FitnessCheckinUpdate) SetUserID(v string) *FitnessCheckinUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *FitnessCheckinUpdate) SetNillableUserID(v *string) *FitnessCheckinUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCheckinDate sets the "checkin_date" field.
func (_u *FitnessCheckinUpdate) SetCheckinDate(v string) *FitnessCheckinUpdate {
	_u.mutation.SetCheckinDate(v)
	return _u
}

// SetNillableCheckinDate sets the "checkin_date" field if the given value is not nil.
func (_u *FitnessCheckinUpdate) SetNillableCheckinDate(v *string) *FitnessCheckinUpdate {
	if v != nil {
		_u.SetCheckinDate(*v)
	}
	return _u
}

// SetExerciseType sets the "exercise_type" field.
func (_u *FitnessCheckinUpdate) SetExerciseType(v fitnesscheckin.ExerciseType) *FitnessCheckinUpdate {
	_u.mutation.SetExerciseType(v)
	return _u
}

// SetNillableExerciseType sets the "exercise_type" field if the given value is not nil.
func (_u *FitnessCheckinUpdate) SetNillableExerciseType(v *fitnesscheckin.ExerciseType) *FitnessCheckinUpdate {
	if v != nil {
		_u.SetExerciseType(*v)
	}
	return _u
}

// SetDurationMinutes sets the "duration_minutes" field.
func (_u *FitnessCheckinUpdate) SetDurationMinutes(v int) *FitnessCheckinUpdate {
	_u.mutation.ResetDurationMinutes()
	_u.mutation.SetDurationMinutes(v)
	return _u
}

// SetNillableDurationMinutes sets the "duration_minutes" field if the given value is not nil.
func (_u *FitnessCheckinUpdate) SetNillableDurationMinutes(v *int) *FitnessCheckinUpdate {
	if v != nil {
		_u.SetDurationMinutes(*v)
	}
	return _u
}

// AddDurationMinutes adds value to the "duration_minutes" field.
func (_u *FitnessCheckinUpdate) AddDurationMinutes(v int) *FitnessCheckinUpdate {
	_u.mutation.AddDurationMinutes(v)
	return _u
}

// SetContent sets the "content" field.
func (_u *FitnessCheckinUpdate) SetContent(v string) *FitnessCheckinUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *FitnessCheckinUpdate) SetNillableContent(v *string) *FitnessCheckinUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *FitnessCheckinUpdate) ClearContent() *FitnessCheckinUpdate {
	_u.mutation.ClearContent()
	return _u
}

// SetCalories sets the "calories" field.
func (_u *FitnessCheckinUpdate) SetCalories(v int) *FitnessCheckinUpdate {
	_u.mutation.ResetCalories()
	_u.mutation.SetCalories(v)
	return _u
}

// SetNillableCalories sets the "calories" field if the given value is not nil.
func (_u *FitnessCheckinUpdate) SetNillableCalories(v *int) *FitnessCheckinUpdate {
	if v != nil {
		_u.SetCalories(*v)
	}
	return _u
}

// AddCalories adds value to the "calories" field.
func (_u *FitnessCheckinUpdate) AddCalories(v int) *FitnessCheckinUpdate {
	_u.mutation.AddCalories(v)
	return _u
}

// ClearCalories clears the value of the "calories" field.
func (_u *FitnessCheckinUpdate) ClearCalories() *FitnessCheckinUpdate {
	_u.mutation.ClearCalories()
	return _u
}

// SetWeight sets the "weight" field.
func (_u *FitnessCheckinUpdate) SetWeight(v float64) *FitnessCheckinUpdate {
	_u.mutation.ResetWeight()
	_u.mutation.SetWeight(v)
	return _u
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_u *FitnessCheckinUpdate) SetNillableWeight(v *float64) *FitnessCheckinUpdate {
	if v != nil {
		_u.SetWeight(*v)
	}
	return _u
}

// AddWeight adds value to the "weight" field.
func (_u *FitnessCheckinUpdate) AddWeight(v float64) *FitnessCheckinUpdate {
	_u.mutation.AddWeight(v)
	return _u
}

// ClearWeight clears the value of the "weight" field.
func (_u *FitnessCheckinUpdate) ClearWeight() *FitnessCheckinUpdate {
	_u.mutation.ClearWeight()
	return _u
}

// SetWeightPublic sets the "weight_public" field.
func (_u *FitnessCheckinUpdate) SetWeightPublic(v bool) *FitnessCheckinUpdate {
	_u.mutation.SetWeightPublic(v)
	return _u
}

// SetNillableWeightPublic sets the "weight_public" field if the given value is not nil.
func (_u *FitnessCheckinUpdate) SetNillableWeightPublic(v *bool) *FitnessCheckinUpdate {
	if v != nil {
		_u.SetWeightPublic(*v)
	}
	return _u
}

// SetMood sets the "mood" field.
func (_u *FitnessCheckinUpdate) SetMood(v string) *FitnessCheckinUpdate {
	_u.mutation.SetMood(v)
	return _u
}

// SetNillableMood sets the "mood" field if the given value is not nil.
func (_u *FitnessCheckinUpdate) SetNillableMood(v *string) *FitnessCheckinUpdate {
	if v != nil {
		_u.SetMood(*v)
	}
	return _u
}

// ClearMood clears the value of the "mood" field.
func (_u *FitnessCheckinUpdate) ClearMood() *FitnessCheckinUpdate {
	_u.mutation.ClearMood()
	return _u
}

// SetAuditStatus sets the "audit_status" field.
func (_u *FitnessCheckinUpdate) SetAuditStatus(v fitnesscheckin.AuditStatus) *FitnessCheckinUpdate {
	_u.mutation.SetAuditStatus(v)
	return _u
}

// SetNillableAuditStatus sets the "audit_status" field if the given value is not nil.
func (_u *FitnessCheckinUpdate) SetNillableAuditStatus(v *fitnesscheckin.AuditStatus) *FitnessCheckinUpdate {
	if v != nil {
		_u.SetAuditStatus(*v)
	}
	return _u
}

// SetAuditDetail sets the "audit_detail" field.
func (_u *FitnessCheckinUpdate) SetAuditDetail(v string) *FitnessCheckinUpdate {
	_u.mutation.SetAuditDetail(v)
	return _u
}

// SetNillableAuditDetail sets the "audit_detail" field if the given value is not nil.
func (_u *FitnessCheckinUpdate) SetNillableAuditDetail(v *string) *FitnessCheckinUpdate {
	if v != nil {
		_u.SetAuditDetail(*v)
	}
	return _u
}

// ClearAuditDetail clears the value of the "audit_detail" field.
func (_u *FitnessCheckinUpdate) ClearAuditDetail() *FitnessCheckinUpdate {
	_u.mutation.ClearAuditDetail()
	return _u
}

// Mutation returns the FitnessCheckinMutation object of the builder.
func (_u *FitnessCheckinUpdate) Mutation() *FitnessCheckinMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FitnessCheckinUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FitnessCheckinUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FitnessCheckinUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FitnessCheckinUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FitnessCheckinUpdate) check() error {
	if v, ok := _u.mutation.ExerciseType(); ok {
		if err := fitnesscheckin.ExerciseTypeValidator(v); err != nil {
			return &ValidationError{Name: "exercise_type", err: fmt.Errorf(`ent: validator failed for field "FitnessCheckin.exercise_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DurationMinutes(); ok {
		if err := fitnesscheckin.DurationMinutesValidator(v); err != nil {
			return &ValidationError{Name: "duration_minutes", err: fmt.Errorf(`ent: validator failed for field "FitnessCheckin.duration_minutes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := fitnesscheckin.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "FitnessCheckin.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Calories(); ok {
		if err := fitnesscheckin.CaloriesValidator(v); err != nil {
			return &ValidationError{Name: "calories", err: fmt.Errorf(`ent: validator failed for field "FitnessCheckin.calories": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Weight(); ok {
		if err := fitnesscheckin.WeightValidator(v); err != nil {
			return &ValidationError{Name: "weight", err: fmt.Errorf(`ent: validator failed for field "FitnessCheckin.weight": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Mood(); ok {
		if err := fitnesscheckin.MoodValidator(v); err != nil {
			return &ValidationError{Name: "mood", err: fmt.Errorf(`ent: validator failed for field "FitnessCheckin.mood": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuditStatus(); ok {
		if err := fitnesscheckin.AuditStatusValidator(v); err != nil {
			return &ValidationError{Name: "audit_status", err: fmt.Errorf(`ent: validator failed for field "FitnessCheckin.audit_status": %w`, err)}
		}
	}
	return nil
}

func (_u *FitnessCheckinUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(fitnesscheckin.Table, fitnesscheckin.Columns, sqlgraph.NewFieldSpec(fitnesscheckin.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(fitnesscheckin.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(fitnesscheckin.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(fitnesscheckin.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(fitnesscheckin.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(fitnesscheckin.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(fitnesscheckin.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(fitnesscheckin.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CheckinDate(); ok {
		_spec.SetField(fitnesscheckin.FieldCheckinDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExerciseType(); ok {
		_spec.SetField(fitnesscheckin.FieldExerciseType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DurationMinutes(); ok {
		_spec.SetField(fitnesscheckin.FieldDurationMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMinutes(); ok {
		_spec.AddField(fitnesscheckin.FieldDurationMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(fitnesscheckin.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(fitnesscheckin.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.Calories(); ok {
		_spec.SetField(fitnesscheckin.FieldCalories, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCalories(); ok {
		_spec.AddField(fitnesscheckin.FieldCalories, field.TypeInt, value)
	}
	if _u.mutation.CaloriesCleared() {
		_spec.ClearField(fitnesscheckin.FieldCalories, field.TypeInt)
	}
	if value, ok := _u.mutation.Weight(); ok {
		_spec.SetField(fitnesscheckin.FieldWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeight(); ok {
		_spec.AddField(fitnesscheckin.FieldWeight, field.TypeFloat64, value)
	}
	if _u.mutation.WeightCleared() {
		_spec.ClearField(fitnesscheckin.FieldWeight, field.TypeFloat64)
	}
	if value, ok := _u.mutation.WeightPublic(); ok {
		_spec.SetField(fitnesscheckin.FieldWeightPublic, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Mood(); ok {
		_spec.SetField(fitnesscheckin.FieldMood, field.TypeString, value)
	}
	if _u.mutation.MoodCleared() {
		_spec.ClearField(fitnesscheckin.FieldMood, field.TypeString)
	}
	if value, ok := _u.mutation.AuditStatus(); ok {
		_spec.SetField(fitnesscheckin.FieldAuditStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AuditDetail(); ok {
		_spec.SetField(fitnesscheckin.FieldAuditDetail, field.TypeString, value)
	}
	if _u.mutation.AuditDetailCleared() {
		_spec.ClearField(fitnesscheckin.FieldAuditDetail, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{fitnesscheckin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FitnessCheckinUpdateOne is the builder for updating a single FitnessCheckin entity.
type FitnessCheckinUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FitnessCheckinMutation
}

// SetCreatedAt sets the "created_at" field.
func (_u *FitnessCheckinUpdateOne) SetCreatedAt(v time.Time) *FitnessCheckinUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *FitnessCheckinUpdateOne) SetNillableCreatedAt(v *time.Time) *FitnessCheckinUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *FitnessCheckinUpdateOne) ClearCreatedAt() *FitnessCheckinUpdateOne {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FitnessCheckinUpdateOne) SetUpdatedAt(v time.Time) *FitnessCheckinUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *FitnessCheckinUpdateOne) SetNillableUpdatedAt(v *time.Time) *FitnessCheckinUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *FitnessCheckinUpdateOne) ClearUpdatedAt() *FitnessCheckinUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *FitnessCheckinUpdateOne) SetDeletedAt(v time.Time) *FitnessCheckinUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *FitnessCheckinUpdateOne) SetNillableDeletedAt(v *time.Time) *FitnessCheckinUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *FitnessCheckinUpdateOne) ClearDeletedAt() *FitnessCheckinUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *FitnessCheckinUpdateOne) SetUserID(v string) *FitnessCheckinUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *FitnessCheckinUpdateOne) SetNillableUserID(v *string) *FitnessCheckinUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCheckinDate sets the "checkin_date" field.
func (_u *FitnessCheckinUpdateOne) SetCheckinDate(v string) *FitnessCheckinUpdateOne {
	_u.mutation.SetCheckinDate(v)
	return _u
}

// SetNillableCheckinDate sets the "checkin_date" field if the given value is not nil.
func (_u *FitnessCheckinUpdateOne) SetNillableCheckinDate(v *string) *FitnessCheckinUpdateOne {
	if v != nil {
		_u.SetCheckinDate(*v)
	}
	return _u
}

// SetExerciseType sets the "exercise_type" field.
func (_u *FitnessCheckinUpdateOne) SetExerciseType(v fitnesscheckin.ExerciseType) *FitnessCheckinUpdateOne {
	_u.mutation.SetExerciseType(v)
	return _u
}

// SetNillableExerciseType sets the "exercise_type" field if the given value is not nil.
func (_u *FitnessCheckinUpdateOne) SetNillableExerciseType(v *fitnesscheckin.ExerciseType) *FitnessCheckinUpdateOne {
	if v != nil {
		_u.SetExerciseType(*v)
	}
	return _u
}

// SetDurationMinutes sets the "duration_minutes" field.
func (_u *FitnessCheckinUpdateOne) SetDurationMinutes(v int) *FitnessCheckinUpdateOne {
	_u.mutation.ResetDurationMinutes()
	_u.mutation.SetDurationMinutes(v)
	return _u
}

// SetNillableDurationMinutes sets the "duration_minutes" field if the given value is not nil.
func (_u *FitnessCheckinUpdateOne) SetNillableDurationMinutes(v *int) *FitnessCheckinUpdateOne {
	if v != nil {
		_u.SetDurationMinutes(*v)
	}
	return _u
}

// AddDurationMinutes adds value to the "duration_minutes" field.
func (_u *FitnessCheckinUpdateOne) AddDurationMinutes(v int) *FitnessCheckinUpdateOne {
	_u.mutation.AddDurationMinutes(v)
	return _u
}

// SetContent sets the "content" field.
func (_u *FitnessCheckinUpdateOne) SetContent(v string) *FitnessCheckinUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *FitnessCheckinUpdateOne) SetNillableContent(v *string) *FitnessCheckinUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *FitnessCheckinUpdateOne) ClearContent() *FitnessCheckinUpdateOne {
	_u.mutation.ClearContent()
	return _u
}

// SetCalories sets the "calories" field.
func (_u *FitnessCheckinUpdateOne) SetCalories(v int) *FitnessCheckinUpdateOne {
	_u.mutation.ResetCalories()
	_u.mutation.SetCalories(v)
	return _u
}

// SetNillableCalories sets the "calories" field if the given value is not nil.
func (_u *FitnessCheckinUpdateOne) SetNillableCalories(v *int) *FitnessCheckinUpdateOne {
	if v != nil {
		_u.SetCalories(*v)
	}
	return _u
}

// AddCalories adds value to the "calories" field.
func (_u *FitnessCheckinUpdateOne) AddCalories(v int) *FitnessCheckinUpdateOne {
	_u.mutation.AddCalories(v)
	return _u
}

// ClearCalories clears the value of the "calories" field.
func (_u *FitnessCheckinUpdateOne) ClearCalories() *FitnessCheckinUpdateOne {
	_u.mutation.ClearCalories()
	return _u
}

// SetWeight sets the "weight" field.
func (_u *FitnessCheckinUpdateOne) SetWeight(v float64) *FitnessCheckinUpdateOne {
	_u.mutation.ResetWeight()
	_u.mutation.SetWeight(v)
	return _u
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_u *FitnessCheckinUpdateOne) SetNillableWeight(v *float64) *FitnessCheckinUpdateOne {
	if v != nil {
		_u.SetWeight(*v)
	}
	return _u
}

// AddWeight adds value to the "weight" field.
func (_u *FitnessCheckinUpdateOne) AddWeight(v float64) *FitnessCheckinUpdateOne {
	_u.mutation.AddWeight(v)
	return _u
}

// ClearWeight clears the value of the "weight" field.
func (_u *FitnessCheckinUpdateOne) ClearWeight() *FitnessCheckinUpdateOne {
	_u.mutation.ClearWeight()
	return _u
}

// SetWeightPublic sets the "weight_public" field.
func (_u *FitnessCheckinUpdateOne) SetWeightPublic(v bool) *FitnessCheckinUpdateOne {
	_u.mutation.SetWeightPublic(v)
	return _u
}

// SetNillableWeightPublic sets the "weight_public" field if the given value is not nil.
func (_u *FitnessCheckinUpdateOne) SetNillableWeightPublic(v *bool) *FitnessCheckinUpdateOne {
	if v != nil {
		_u.SetWeightPublic(*v)
	}
	return _u
}

// SetMood sets the "mood" field.
func (_u *FitnessCheckinUpdateOne) SetMood(v string) *FitnessCheckinUpdateOne {
	_u.mutation.SetMood(v)
	return _u
}

// SetNillableMood sets the "mood" field if the given value is not nil.
func (_u *FitnessCheckinUpdateOne) SetNillableMood(v *string) *FitnessCheckinUpdateOne {
	if v != nil {
		_u.SetMood(*v)
	}
	return _u
}

// ClearMood clears the value of the "mood" field.
func (_u *FitnessCheckinUpdateOne) ClearMood() *FitnessCheckinUpdateOne {
	_u.mutation.ClearMood()
	return _u
}

// SetAuditStatus sets the "audit_status" field.
func (_u *FitnessCheckinUpdateOne) SetAuditStatus(v fitnesscheckin.AuditStatus) *FitnessCheckinUpdateOne {
	_u.mutation.SetAuditStatus(v)
	return _u
}

// SetNillableAuditStatus sets the "audit_status" field if the given value is not nil.
func (_u *FitnessCheckinUpdateOne) SetNillableAuditStatus(v *fitnesscheckin.AuditStatus) *FitnessCheckinUpdateOne {
	if v != nil {
		_u.SetAuditStatus(*v)
	}
	return _u
}

// SetAuditDetail sets the "audit_detail" field.
func (_u *FitnessCheckinUpdateOne) SetAuditDetail(v string) *FitnessCheckinUpdateOne {
	_u.mutation.SetAuditDetail(v)
	return _u
}

// SetNillableAuditDetail sets the "audit_detail" field if the given value is not nil.
func (_u *FitnessCheckinUpdateOne) SetNillableAuditDetail(v *string) *FitnessCheckinUpdateOne {
	if v != nil {
		_u.SetAuditDetail(*v)
	}
	return _u
}

// ClearAuditDetail clears the value of the "audit_detail" field.
func (_u *FitnessCheckinUpdateOne) ClearAuditDetail() *FitnessCheckinUpdateOne {
	_u.mutation.ClearAuditDetail()
	return _u
}

// Mutation returns the FitnessCheckinMutation object of the builder.
func (_u *FitnessCheckinUpdateOne) Mutation() *FitnessCheckinMutation {
	return _u.mutation
}

// Where appends a list predicates to the FitnessCheckinUpdate builder.
func (_u *FitnessCheckinUpdateOne) Where(ps ...predicate.FitnessCheckin) *FitnessCheckinUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FitnessCheckinUpdateOne) Select(field string, fields ...string) *FitnessCheckinUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FitnessCheckin entity.
func (_u *FitnessCheckinUpdateOne) Save(ctx context.Context) (*FitnessCheckin, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FitnessCheckinUpdateOne) SaveX(ctx context.Context) *FitnessCheckin {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FitnessCheckinUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FitnessCheckinUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FitnessCheckinUpdateOne) check() error {
	if v, ok := _u.mutation.ExerciseType(); ok {
		if err := fitnesscheckin.ExerciseTypeValidator(v); err != nil {
			return &ValidationError{Name: "exercise_type", err: fmt.Errorf(`ent: validator failed for field "FitnessCheckin.exercise_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DurationMinutes(); ok {
		if err := fitnesscheckin.DurationMinutesValidator(v); err != nil {
			return &ValidationError{Name: "duration_minutes", err: fmt.Errorf(`ent: validator failed for field "FitnessCheckin.duration_minutes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := fitnesscheckin.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "FitnessCheckin.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Calories(); ok {
		if err := fitnesscheckin.CaloriesValidator(v); err != nil {
			return &ValidationError{Name: "calories", err: fmt.Errorf(`ent: validator failed for field "FitnessCheckin.calories": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Weight(); ok {
		if err := fitnesscheckin.WeightValidator(v); err != nil {
			return &ValidationError{Name: "weight", err: fmt.Errorf(`ent: validator failed for field "FitnessCheckin.weight": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Mood(); ok {
		if err := fitnesscheckin.MoodValidator(v); err != nil {
			return &ValidationError{Name: "mood", err: fmt.Errorf(`ent: validator failed for field "FitnessCheckin.mood": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuditStatus(); ok {
		if err := fitnesscheckin.AuditStatusValidator(v); err != nil {
			return &ValidationError{Name: "audit_status", err: fmt.Errorf(`ent: validator failed for field "FitnessCheckin.audit_status": %w`, err)}
		}
	}
	return nil
}

func (_u *FitnessCheckinUpdateOne) sqlSave(ctx context.Context) (_node *FitnessCheckin, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(fitnesscheckin.Table, fitnesscheckin.Columns, sqlgraph.NewFieldSpec(fitnesscheckin.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FitnessCheckin.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, fitnesscheckin.FieldID)
		for _, f := range fields {
			if !fitnesscheckin.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != fitnesscheckin.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(fitnesscheckin.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(fitnesscheckin.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(fitnesscheckin.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(fitnesscheckin.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(fitnesscheckin.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(fitnesscheckin.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(fitnesscheckin.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CheckinDate(); ok {
		_spec.SetField(fitnesscheckin.FieldCheckinDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExerciseType(); ok {
		_spec.SetField(fitnesscheckin.FieldExerciseType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DurationMinutes(); ok {
		_spec.SetField(fitnesscheckin.FieldDurationMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMinutes(); ok {
		_spec.AddField(fitnesscheckin.FieldDurationMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(fitnesscheckin.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(fitnesscheckin.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.Calories(); ok {
		_spec.SetField(fitnesscheckin.FieldCalories, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCalories(); ok {
		_spec.AddField(fitnesscheckin.FieldCalories, field.TypeInt, value)
	}
	if _u.mutation.CaloriesCleared() {
		_spec.ClearField(fitnesscheckin.FieldCalories, field.TypeInt)
	}
	if value, ok := _u.mutation.Weight(); ok {
		_spec.SetField(fitnesscheckin.FieldWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeight(); ok {
		_spec.AddField(fitnesscheckin.FieldWeight, field.TypeFloat64, value)
	}
	if _u.mutation.WeightCleared() {
		_spec.ClearField(fitnesscheckin.FieldWeight, field.TypeFloat64)
	}
	if value, ok := _u.mutation.WeightPublic(); ok {
		_spec.SetField(fitnesscheckin.FieldWeightPublic, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Mood(); ok {
		_spec.SetField(fitnesscheckin.FieldMood, field.TypeString, value)
	}
	if _u.mutation.MoodCleared() {
		_spec.ClearField(fitnesscheckin.FieldMood, field.TypeString)
	}
	if value, ok := _u.mutation.AuditStatus(); ok {
		_spec.SetField(fitnesscheckin.FieldAuditStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AuditDetail(); ok {
		_spec.SetField(fitnesscheckin.FieldAuditDetail, field.TypeString, value)
	}
	if _u.mutation.AuditDetailCleared() {
		_spec.ClearField(fitnesscheckin.FieldAuditDetail, field.TypeString)
	}
	_node = &FitnessCheckin{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{fitnesscheckin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
