// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"platform/ent/fitnesssubscriptionauthorization"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// 小程序订阅消息授权表
type FitnessSubscriptionAuthorization struct {
	config `json:"-"`
	// ID of the ent.
	// 订阅授权ID
	ID string `json:"id,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt time.Time `json:"deleted_at,omitempty"`
	// 用户ID
	UserID string `json:"user_id,omitempty"`
	// 订阅消息模板ID
	TemplateID string `json:"template_id,omitempty"`
	// 是否启用
	Enabled bool `json:"enabled,omitempty"`
	// 可发送次数
	AvailableCount int `json:"available_count,omitempty"`
	// 最近授权时间
	AuthorizedAt time.Time `json:"authorized_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FitnessSubscriptionAuthorization) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case fitnesssubscriptionauthorization.FieldEnabled:
			values[i] = new(sql.NullBool)
		case fitnesssubscriptionauthorization.FieldAvailableCount:
			values[i] = new(sql.NullInt64)
		case fitnesssubscriptionauthorization.FieldID, fitnesssubscriptionauthorization.FieldUserID, fitnesssubscriptionauthorization.FieldTemplateID:
			values[i] = new(sql.NullString)
		case fitnesssubscriptionauthorization.FieldCreatedAt, fitnesssubscriptionauthorization.FieldUpdatedAt, fitnesssubscriptionauthorization.FieldDeletedAt, fitnesssubscriptionauthorization.FieldAuthorizedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FitnessSubscriptionAuthorization fields.
func (_m *FitnessSubscriptionAuthorization) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case fitnesssubscriptionauthorization.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case fitnesssubscriptionauthorization.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case fitnesssubscriptionauthorization.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case fitnesssubscriptionauthorization.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = value.Time
			}
		case fitnesssubscriptionauthorization.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.String
			}
		case fitnesssubscriptionauthorization.FieldTemplateID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field template_id", values[i])
			} else if value.Valid {
				_m.TemplateID = value.String
			}
		case fitnesssubscriptionauthorization.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case fitnesssubscriptionauthorization.FieldAvailableCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field available_count", values[i])
			} else if value.Valid {
				_m.AvailableCount = int(value.Int64)
			}
		case fitnesssubscriptionauthorization.FieldAuthorizedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field authorized_at", values[i])
			} else if value.Valid {
				_m.AuthorizedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FitnessSubscriptionAuthorization.
// This includes values selected through modifiers, order, etc.
func (_m *FitnessSubscriptionAuthorization) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this FitnessSubscriptionAuthorization.
// Note that you need to call FitnessSubscriptionAuthorization.Unwrap() before calling this method if this FitnessSubscriptionAuthorization
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *FitnessSubscriptionAuthorization) Update() *FitnessSubscriptionAuthorizationUpdateOne {
	return NewFitnessSubscriptionAuthorizationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the FitnessSubscriptionAuthorization entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *FitnessSubscriptionAuthorization) Unwrap() *FitnessSubscriptionAuthorization {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: FitnessSubscriptionAuthorization is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *FitnessSubscriptionAuthorization) String() string {
	var builder strings.Builder
	builder.WriteString("FitnessSubscriptionAuthorization(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(_m.DeletedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(_m.UserID)
	builder.WriteString(", ")
	builder.WriteString("template_id=")
	builder.WriteString(_m.TemplateID)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("available_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.AvailableCount))
	builder.WriteString(", ")
	builder.WriteString("authorized_at=")
	builder.WriteString(_m.AuthorizedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// FitnessSubscriptionAuthorizations is a parsable slice of FitnessSubscriptionAuthorization.
type FitnessSubscriptionAuthorizations []*FitnessSubscriptionAuthorization
