// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"platform/ent/fitnessgroupinvitation"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// 健身小组邀请表
type FitnessGroupInvitation struct {
	config `json:"-"`
	// ID of the ent.
	// 小组邀请ID
	ID string `json:"id,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt time.Time `json:"deleted_at,omitempty"`
	// 小组ID
	GroupID string `json:"group_id,omitempty"`
	// 创建用户ID
	CreatorID string `json:"creator_id,omitempty"`
	// 邀请码
	Code string `json:"code,omitempty"`
	// 小程序码存储文件ID
	QrFileID string `json:"qr_file_id,omitempty"`
	// 失效时间
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// 是否有效
	Active       bool `json:"active,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FitnessGroupInvitation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case fitnessgroupinvitation.FieldActive:
			values[i] = new(sql.NullBool)
		case fitnessgroupinvitation.FieldID, fitnessgroupinvitation.FieldGroupID, fitnessgroupinvitation.FieldCreatorID, fitnessgroupinvitation.FieldCode, fitnessgroupinvitation.FieldQrFileID:
			values[i] = new(sql.NullString)
		case fitnessgroupinvitation.FieldCreatedAt, fitnessgroupinvitation.FieldUpdatedAt, fitnessgroupinvitation.FieldDeletedAt, fitnessgroupinvitation.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FitnessGroupInvitation fields.
func (_m *FitnessGroupInvitation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case fitnessgroupinvitation.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case fitnessgroupinvitation.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case fitnessgroupinvitation.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case fitnessgroupinvitation.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = value.Time
			}
		case fitnessgroupinvitation.FieldGroupID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.String
			}
		case fitnessgroupinvitation.FieldCreatorID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field creator_id", values[i])
			} else if value.Valid {
				_m.CreatorID = value.String
			}
		case fitnessgroupinvitation.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case fitnessgroupinvitation.FieldQrFileID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field qr_file_id", values[i])
			} else if value.Valid {
				_m.QrFileID = value.String
			}
		case fitnessgroupinvitation.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case fitnessgroupinvitation.FieldActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field active", values[i])
			} else if value.Valid {
				_m.Active = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FitnessGroupInvitation.
// This includes values selected through modifiers, order, etc.
func (_m *FitnessGroupInvitation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this FitnessGroupInvitation.
// Note that you need to call FitnessGroupInvitation.Unwrap() before calling this method if this FitnessGroupInvitation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *FitnessGroupInvitation) Update() *FitnessGroupInvitationUpdateOne {
	return NewFitnessGroupInvitationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the FitnessGroupInvitation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *FitnessGroupInvitation) Unwrap() *FitnessGroupInvitation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: FitnessGroupInvitation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *FitnessGroupInvitation) String() string {
	var builder strings.Builder
	builder.WriteString("FitnessGroupInvitation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(_m.DeletedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(_m.GroupID)
	builder.WriteString(", ")
	builder.WriteString("creator_id=")
	builder.WriteString(_m.CreatorID)
	builder.WriteString(", ")
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("qr_file_id=")
	builder.WriteString(_m.QrFileID)
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("active=")
	builder.WriteString(fmt.Sprintf("%v", _m.Active))
	builder.WriteByte(')')
	return builder.String()
}

// FitnessGroupInvitations is a parsable slice of FitnessGroupInvitation.
type FitnessGroupInvitations []*FitnessGroupInvitation
