// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"platform/ent/fitnesssubscriptionauthorization"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FitnessSubscriptionAuthorizationCreate is the builder for creating a FitnessSubscriptionAuthorization entity.
type FitnessSubscriptionAuthorizationCreate struct {
	config
	mutation *FitnessSubscriptionAuthorizationMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *FitnessSubscriptionAuthorizationCreate) SetCreatedAt(v time.Time) *FitnessSubscriptionAuthorizationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *FitnessSubscriptionAuthorizationCreate) SetNillableCreatedAt(v *time.Time) *FitnessSubscriptionAuthorizationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *FitnessSubscriptionAuthorizationCreate) SetUpdatedAt(v time.Time) *FitnessSubscriptionAuthorizationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *FitnessSubscriptionAuthorizationCreate) SetNillableUpdatedAt(v *time.Time) *FitnessSubscriptionAuthorizationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *FitnessSubscriptionAuthorizationCreate) SetDeletedAt(v time.Time) *FitnessSubscriptionAuthorizationCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *FitnessSubscriptionAuthorizationCreate) SetNillableDeletedAt(v *time.Time) *FitnessSubscriptionAuthorizationCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *FitnessSubscriptionAuthorizationCreate) SetUserID(v string) *FitnessSubscriptionAuthorizationCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetTemplateID sets the "template_id" field.
func (_c *FitnessSubscriptionAuthorizationCreate) SetTemplateID(v string) *FitnessSubscriptionAuthorizationCreate {
	_c.mutation.SetTemplateID(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *FitnessSubscriptionAuthorizationCreate) SetEnabled(v bool) *FitnessSubscriptionAuthorizationCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *FitnessSubscriptionAuthorizationCreate) SetNillableEnabled(v *bool) *FitnessSubscriptionAuthorizationCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetAvailableCount sets the "available_count" field.
func (_c *FitnessSubscriptionAuthorizationCreate) SetAvailableCount(v int) *FitnessSubscriptionAuthorizationCreate {
	_c.mutation.SetAvailableCount(v)
	return _c
}

// SetNillableAvailableCount sets the "available_count" field if the given value is not nil.
func (_c *FitnessSubscriptionAuthorizationCreate) SetNillableAvailableCount(v *int) *FitnessSubscriptionAuthorizationCreate {
	if v != nil {
		_c.SetAvailableCount(*v)
	}
	return _c
}

// SetAuthorizedAt sets the "authorized_at" field.
func (_c *FitnessSubscriptionAuthorizationCreate) SetAuthorizedAt(v time.Time) *FitnessSubscriptionAuthorizationCreate {
	_c.mutation.SetAuthorizedAt(v)
	return _c
}

// SetNillableAuthorizedAt sets the "authorized_at" field if the given value is not nil.
func (_c *FitnessSubscriptionAuthorizationCreate) SetNillableAuthorizedAt(v *time.Time) *FitnessSubscriptionAuthorizationCreate {
	if v != nil {
		_c.SetAuthorizedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *FitnessSubscriptionAuthorizationCreate) SetID(v string) *FitnessSubscriptionAuthorizationCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *FitnessSubscriptionAuthorizationCreate) SetNillableID(v *string) *FitnessSubscriptionAuthorizationCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the FitnessSubscriptionAuthorizationMutation object of the builder.
func (_c *FitnessSubscriptionAuthorizationCreate) Mutation() *FitnessSubscriptionAuthorizationMutation {
	return _c.mutation
}

// Save creates the FitnessSubscriptionAuthorization in the database.
func (_c *FitnessSubscriptionAuthorizationCreate) Save(ctx context.Context) (*FitnessSubscriptionAuthorization, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FitnessSubscriptionAuthorizationCreate) SaveX(ctx context.Context) *FitnessSubscriptionAuthorization {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FitnessSubscriptionAuthorizationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FitnessSubscriptionAuthorizationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FitnessSubscriptionAuthorizationCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if fitnesssubscriptionauthorization.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized fitnesssubscriptionauthorization.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := fitnesssubscriptionauthorization.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := fitnesssubscriptionauthorization.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.AvailableCount(); !ok {
		v := fitnesssubscriptionauthorization.DefaultAvailableCount
		_c.mutation.SetAvailableCount(v)
	}
	if _, ok := _c.mutation.AuthorizedAt(); !ok {
		if fitnesssubscriptionauthorization.DefaultAuthorizedAt == nil {
			return fmt.Errorf("ent: uninitialized fitnesssubscriptionauthorization.DefaultAuthorizedAt (forgotten import ent/runtime?)")
		}
		v := fitnesssubscriptionauthorization.DefaultAuthorizedAt()
		_c.mutation.SetAuthorizedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		if fitnesssubscriptionauthorization.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized fitnesssubscriptionauthorization.DefaultID (forgotten import ent/runtime?)")
		}
		v := fitnesssubscriptionauthorization.DefaultID()
		_c.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *FitnessSubscriptionAuthorizationCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "FitnessSubscriptionAuthorization.user_id"`)}
	}
	if _, ok := _c.mutation.TemplateID(); !ok {
		return &ValidationError{Name: "template_id", err: errors.New(`ent: missing required field "FitnessSubscriptionAuthorization.template_id"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "FitnessSubscriptionAuthorization.enabled"`)}
	}
	if _, ok := _c.mutation.AvailableCount(); !ok {
		return &ValidationError{Name: "available_count", err: errors.New(`ent: missing required field "FitnessSubscriptionAuthorization.available_count"`)}
	}
	if v, ok := _c.mutation.AvailableCount(); ok {
		if err := fitnesssubscriptionauthorization.AvailableCountValidator(v); err != nil {
			return &ValidationError{Name: "available_count", err: fmt.Errorf(`ent: validator failed for field "FitnessSubscriptionAuthorization.available_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AuthorizedAt(); !ok {
		return &ValidationError{Name: "authorized_at", err: errors.New(`ent: missing required field "FitnessSubscriptionAuthorization.authorized_at"`)}
	}
	return nil
}

func (_c *FitnessSubscriptionAuthorizationCreate) sqlSave(ctx context.Context) (*FitnessSubscriptionAuthorization, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected FitnessSubscriptionAuthorization.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FitnessSubscriptionAuthorizationCreate) createSpec() (*FitnessSubscriptionAuthorization, *sqlgraph.CreateSpec) {
	var (
		_node = &FitnessSubscriptionAuthorization{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(fitnesssubscriptionauthorization.Table, sqlgraph.NewFieldSpec(fitnesssubscriptionauthorization.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(fitnesssubscriptionauthorization.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(fitnesssubscriptionauthorization.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(fitnesssubscriptionauthorization.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(fitnesssubscriptionauthorization.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.TemplateID(); ok {
		_spec.SetField(fitnesssubscriptionauthorization.FieldTemplateID, field.TypeString, value)
		_node.TemplateID = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(fitnesssubscriptionauthorization.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.AvailableCount(); ok {
		_spec.SetField(fitnesssubscriptionauthorization.FieldAvailableCount, field.TypeInt, value)
		_node.AvailableCount = value
	}
	if value, ok := _c.mutation.AuthorizedAt(); ok {
		_spec.SetField(fitnesssubscriptionauthorization.FieldAuthorizedAt, field.TypeTime, value)
		_node.AuthorizedAt = value
	}
	return _node, _spec
}

// FitnessSubscriptionAuthorizationCreateBulk is the builder for creating many FitnessSubscriptionAuthorization entities in bulk.
type FitnessSubscriptionAuthorizationCreateBulk struct {
	config
	err      error
	builders []*FitnessSubscriptionAuthorizationCreate
}

// Save creates the FitnessSubscriptionAuthorization entities in the database.
func (_c *FitnessSubscriptionAuthorizationCreateBulk) Save(ctx context.Context) ([]*FitnessSubscriptionAuthorization, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FitnessSubscriptionAuthorization, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FitnessSubscriptionAuthorizationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FitnessSubscriptionAuthorizationCreateBulk) SaveX(ctx context.Context) []*FitnessSubscriptionAuthorization {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FitnessSubscriptionAuthorizationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FitnessSubscriptionAuthorizationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
