// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"platform/ent/fitnesscontentreport"
	"platform/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FitnessContentReportUpdate is the builder for updating FitnessContentReport entities.
type FitnessContentReportUpdate struct {
	config
	hooks    []Hook
	mutation *FitnessContentReportMutation
}

// Where appends a list predicates to the FitnessContentReportUpdate builder.
func (_u *FitnessContentReportUpdate) Where(ps ...predicate.FitnessContentReport) *FitnessContentReportUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *FitnessContentReportUpdate) SetCreatedAt(v time.Time) *FitnessContentReportUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *FitnessContentReportUpdate) SetNillableCreatedAt(v *time.Time) *FitnessContentReportUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *FitnessContentReportUpdate) ClearCreatedAt() *FitnessContentReportUpdate {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FitnessContentReportUpdate) SetUpdatedAt(v time.Time) *FitnessContentReportUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *FitnessContentReportUpdate) SetNillableUpdatedAt(v *time.Time) *FitnessContentReportUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *FitnessContentReportUpdate) ClearUpdatedAt() *FitnessContentReportUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *FitnessContentReportUpdate) SetDeletedAt(v time.Time) *FitnessContentReportUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *FitnessContentReportUpdate) SetNillableDeletedAt(v *time.Time) *FitnessContentReportUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *FitnessContentReportUpdate) ClearDeletedAt() *FitnessContentReportUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetReporterUserID sets the "reporter_user_id" field.
func (_u *FitnessContentReportUpdate) SetReporterUserID(v string) *FitnessContentReportUpdate {
	_u.mutation.SetReporterUserID(v)
	return _u
}

// SetNillableReporterUserID sets the "reporter_user_id" field if the given value is not nil.
func (_u *FitnessContentReportUpdate) SetNillableReporterUserID(v *string) *FitnessContentReportUpdate {
	if v != nil {
		_u.SetReporterUserID(*v)
	}
	return _u
}

// SetCheckinID sets the "checkin_id" field.
func (_u *FitnessContentReportUpdate) SetCheckinID(v string) *FitnessContentReportUpdate {
	_u.mutation.SetCheckinID(v)
	return _u
}

// SetNillableCheckinID sets the "checkin_id" field if the given value is not nil.
func (_u *FitnessContentReportUpdate) SetNillableCheckinID(v *string) *FitnessContentReportUpdate {
	if v != nil {
		_u.SetCheckinID(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *FitnessContentReportUpdate) SetReason(v string) *FitnessContentReportUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *FitnessContentReportUpdate) SetNillableReason(v *string) *FitnessContentReportUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *FitnessContentReportUpdate) SetStatus(v fitnesscontentreport.Status) *FitnessContentReportUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *FitnessContentReportUpdate) SetNillableStatus(v *fitnesscontentreport.Status) *FitnessContentReportUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetHandlerUserID sets the "handler_user_id" field.
func (_u *FitnessContentReportUpdate) SetHandlerUserID(v string) *FitnessContentReportUpdate {
	_u.mutation.SetHandlerUserID(v)
	return _u
}

// SetNillableHandlerUserID sets the "handler_user_id" field if the given value is not nil.
func (_u *FitnessContentReportUpdate) SetNillableHandlerUserID(v *string) *FitnessContentReportUpdate {
	if v != nil {
		_u.SetHandlerUserID(*v)
	}
	return _u
}

// ClearHandlerUserID clears the value of the "handler_user_id" field.
func (_u *FitnessContentReportUpdate) ClearHandlerUserID() *FitnessContentReportUpdate {
	_u.mutation.ClearHandlerUserID()
	return _u
}

// SetResolution sets the "resolution" field.
func (_u *FitnessContentReportUpdate) SetResolution(v string) *FitnessContentReportUpdate {
	_u.mutation.SetResolution(v)
	return _u
}

// SetNillableResolution sets the "resolution" field if the given value is not nil.
func (_u *FitnessContentReportUpdate) SetNillableResolution(v *string) *FitnessContentReportUpdate {
	if v != nil {
		_u.SetResolution(*v)
	}
	return _u
}

// ClearResolution clears the value of the "resolution" field.
func (_u *FitnessContentReportUpdate) ClearResolution() *FitnessContentReportUpdate {
	_u.mutation.ClearResolution()
	return _u
}

// Mutation returns the FitnessContentReportMutation object of the builder.
func (_u *FitnessContentReportUpdate) Mutation() *FitnessContentReportMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FitnessContentReportUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FitnessContentReportUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FitnessContentReportUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FitnessContentReportUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FitnessContentReportUpdate) check() error {
	if v, ok := _u.mutation.Reason(); ok {
		if err := fitnesscontentreport.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "FitnessContentReport.reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := fitnesscontentreport.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "FitnessContentReport.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Resolution(); ok {
		if err := fitnesscontentreport.ResolutionValidator(v); err != nil {
			return &ValidationError{Name: "resolution", err: fmt.Errorf(`ent: validator failed for field "FitnessContentReport.resolution": %w`, err)}
		}
	}
	return nil
}

func (_u *FitnessContentReportUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(fitnesscontentreport.Table, fitnesscontentreport.Columns, sqlgraph.NewFieldSpec(fitnesscontentreport.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(fitnesscontentreport.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(fitnesscontentreport.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(fitnesscontentreport.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(fitnesscontentreport.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(fitnesscontentreport.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(fitnesscontentreport.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReporterUserID(); ok {
		_spec.SetField(fitnesscontentreport.FieldReporterUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CheckinID(); ok {
		_spec.SetField(fitnesscontentreport.FieldCheckinID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(fitnesscontentreport.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(fitnesscontentreport.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.HandlerUserID(); ok {
		_spec.SetField(fitnesscontentreport.FieldHandlerUserID, field.TypeString, value)
	}
	if _u.mutation.HandlerUserIDCleared() {
		_spec.ClearField(fitnesscontentreport.FieldHandlerUserID, field.TypeString)
	}
	if value, ok := _u.mutation.Resolution(); ok {
		_spec.SetField(fitnesscontentreport.FieldResolution, field.TypeString, value)
	}
	if _u.mutation.ResolutionCleared() {
		_spec.ClearField(fitnesscontentreport.FieldResolution, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{fitnesscontentreport.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FitnessContentReportUpdateOne is the builder for updating a single FitnessContentReport entity.
type FitnessContentReportUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FitnessContentReportMutation
}

// SetCreatedAt sets the "created_at" field.
func (_u *FitnessContentReportUpdateOne) SetCreatedAt(v time.Time) *FitnessContentReportUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *FitnessContentReportUpdateOne) SetNillableCreatedAt(v *time.Time) *FitnessContentReportUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *FitnessContentReportUpdateOne) ClearCreatedAt() *FitnessContentReportUpdateOne {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FitnessContentReportUpdateOne) SetUpdatedAt(v time.Time) *FitnessContentReportUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *FitnessContentReportUpdateOne) SetNillableUpdatedAt(v *time.Time) *FitnessContentReportUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *FitnessContentReportUpdateOne) ClearUpdatedAt() *FitnessContentReportUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *FitnessContentReportUpdateOne) SetDeletedAt(v time.Time) *FitnessContentReportUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *FitnessContentReportUpdateOne) SetNillableDeletedAt(v *time.Time) *FitnessContentReportUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *FitnessContentReportUpdateOne) ClearDeletedAt() *FitnessContentReportUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetReporterUserID sets the "reporter_user_id" field.
func (_u *FitnessContentReportUpdateOne) SetReporterUserID(v string) *FitnessContentReportUpdateOne {
	_u.mutation.SetReporterUserID(v)
	return _u
}

// SetNillableReporterUserID sets the "reporter_user_id" field if the given value is not nil.
func (_u *FitnessContentReportUpdateOne) SetNillableReporterUserID(v *string) *FitnessContentReportUpdateOne {
	if v != nil {
		_u.SetReporterUserID(*v)
	}
	return _u
}

// SetCheckinID sets the "checkin_id" field.
func (_u *FitnessContentReportUpdateOne) SetCheckinID(v string) *FitnessContentReportUpdateOne {
	_u.mutation.SetCheckinID(v)
	return _u
}

// SetNillableCheckinID sets the "checkin_id" field if the given value is not nil.
func (_u *FitnessContentReportUpdateOne) SetNillableCheckinID(v *string) *FitnessContentReportUpdateOne {
	if v != nil {
		_u.SetCheckinID(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *FitnessContentReportUpdateOne) SetReason(v string) *FitnessContentReportUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *FitnessContentReportUpdateOne) SetNillableReason(v *string) *FitnessContentReportUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *FitnessContentReportUpdateOne) SetStatus(v fitnesscontentreport.Status) *FitnessContentReportUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *FitnessContentReportUpdateOne) SetNillableStatus(v *fitnesscontentreport.Status) *FitnessContentReportUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetHandlerUserID sets the "handler_user_id" field.
func (_u *FitnessContentReportUpdateOne) SetHandlerUserID(v string) *FitnessContentReportUpdateOne {
	_u.mutation.SetHandlerUserID(v)
	return _u
}

// SetNillableHandlerUserID sets the "handler_user_id" field if the given value is not nil.
func (_u *FitnessContentReportUpdateOne) SetNillableHandlerUserID(v *string) *FitnessContentReportUpdateOne {
	if v != nil {
		_u.SetHandlerUserID(*v)
	}
	return _u
}

// ClearHandlerUserID clears the value of the "handler_user_id" field.
func (_u *FitnessContentReportUpdateOne) ClearHandlerUserID() *FitnessContentReportUpdateOne {
	_u.mutation.ClearHandlerUserID()
	return _u
}

// SetResolution sets the "resolution" field.
func (_u *FitnessContentReportUpdateOne) SetResolution(v string) *FitnessContentReportUpdateOne {
	_u.mutation.SetResolution(v)
	return _u
}

// SetNillableResolution sets the "resolution" field if the given value is not nil.
func (_u *FitnessContentReportUpdateOne) SetNillableResolution(v *string) *FitnessContentReportUpdateOne {
	if v != nil {
		_u.SetResolution(*v)
	}
	return _u
}

// ClearResolution clears the value of the "resolution" field.
func (_u *FitnessContentReportUpdateOne) ClearResolution() *FitnessContentReportUpdateOne {
	_u.mutation.ClearResolution()
	return _u
}

// Mutation returns the FitnessContentReportMutation object of the builder.
func (_u *FitnessContentReportUpdateOne) Mutation() *FitnessContentReportMutation {
	return _u.mutation
}

// Where appends a list predicates to the FitnessContentReportUpdate builder.
func (_u *FitnessContentReportUpdateOne) Where(ps ...predicate.FitnessContentReport) *FitnessContentReportUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FitnessContentReportUpdateOne) Select(field string, fields ...string) *FitnessContentReportUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FitnessContentReport entity.
func (_u *FitnessContentReportUpdateOne) Save(ctx context.Context) (*FitnessContentReport, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FitnessContentReportUpdateOne) SaveX(ctx context.Context) *FitnessContentReport {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FitnessContentReportUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FitnessContentReportUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FitnessContentReportUpdateOne) check() error {
	if v, ok := _u.mutation.Reason(); ok {
		if err := fitnesscontentreport.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "FitnessContentReport.reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := fitnesscontentreport.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "FitnessContentReport.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Resolution(); ok {
		if err := fitnesscontentreport.ResolutionValidator(v); err != nil {
			return &ValidationError{Name: "resolution", err: fmt.Errorf(`ent: validator failed for field "FitnessContentReport.resolution": %w`, err)}
		}
	}
	return nil
}

func (_u *FitnessContentReportUpdateOne) sqlSave(ctx context.Context) (_node *FitnessContentReport, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(fitnesscontentreport.Table, fitnesscontentreport.Columns, sqlgraph.NewFieldSpec(fitnesscontentreport.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FitnessContentReport.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, fitnesscontentreport.FieldID)
		for _, f := range fields {
			if !fitnesscontentreport.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != fitnesscontentreport.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(fitnesscontentreport.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(fitnesscontentreport.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(fitnesscontentreport.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(fitnesscontentreport.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(fitnesscontentreport.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(fitnesscontentreport.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReporterUserID(); ok {
		_spec.SetField(fitnesscontentreport.FieldReporterUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CheckinID(); ok {
		_spec.SetField(fitnesscontentreport.FieldCheckinID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(fitnesscontentreport.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(fitnesscontentreport.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.HandlerUserID(); ok {
		_spec.SetField(fitnesscontentreport.FieldHandlerUserID, field.TypeString, value)
	}
	if _u.mutation.HandlerUserIDCleared() {
		_spec.ClearField(fitnesscontentreport.FieldHandlerUserID, field.TypeString)
	}
	if value, ok := _u.mutation.Resolution(); ok {
		_spec.SetField(fitnesscontentreport.FieldResolution, field.TypeString, value)
	}
	if _u.mutation.ResolutionCleared() {
		_spec.ClearField(fitnesscontentreport.FieldResolution, field.TypeString)
	}
	_node = &FitnessContentReport{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{fitnesscontentreport.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
