// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"platform/ent/fitnesscheckinimage"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FitnessCheckinImageCreate is the builder for creating a FitnessCheckinImage entity.
type FitnessCheckinImageCreate struct {
	config
	mutation *FitnessCheckinImageMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *FitnessCheckinImageCreate) SetCreatedAt(v time.Time) *FitnessCheckinImageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *FitnessCheckinImageCreate) SetNillableCreatedAt(v *time.Time) *FitnessCheckinImageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *FitnessCheckinImageCreate) SetUpdatedAt(v time.Time) *FitnessCheckinImageCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *FitnessCheckinImageCreate) SetNillableUpdatedAt(v *time.Time) *FitnessCheckinImageCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *FitnessCheckinImageCreate) SetDeletedAt(v time.Time) *FitnessCheckinImageCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *FitnessCheckinImageCreate) SetNillableDeletedAt(v *time.Time) *FitnessCheckinImageCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCheckinID sets the "checkin_id" field.
func (_c *FitnessCheckinImageCreate) SetCheckinID(v string) *FitnessCheckinImageCreate {
	_c.mutation.SetCheckinID(v)
	return _c
}

// SetStorageFileID sets the "storage_file_id" field.
func (_c *FitnessCheckinImageCreate) SetStorageFileID(v string) *FitnessCheckinImageCreate {
	_c.mutation.SetStorageFileID(v)
	return _c
}

// SetSort sets the "sort" field.
func (_c *FitnessCheckinImageCreate) SetSort(v int) *FitnessCheckinImageCreate {
	_c.mutation.SetSort(v)
	return _c
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_c *FitnessCheckinImageCreate) SetNillableSort(v *int) *FitnessCheckinImageCreate {
	if v != nil {
		_c.SetSort(*v)
	}
	return _c
}

// SetAuditStatus sets the "audit_status" field.
func (_c *FitnessCheckinImageCreate) SetAuditStatus(v fitnesscheckinimage.AuditStatus) *FitnessCheckinImageCreate {
	_c.mutation.SetAuditStatus(v)
	return _c
}

// SetNillableAuditStatus sets the "audit_status" field if the given value is not nil.
func (_c *FitnessCheckinImageCreate) SetNillableAuditStatus(v *fitnesscheckinimage.AuditStatus) *FitnessCheckinImageCreate {
	if v != nil {
		_c.SetAuditStatus(*v)
	}
	return _c
}

// SetAuditTraceID sets the "audit_trace_id" field.
func (_c *FitnessCheckinImageCreate) SetAuditTraceID(v string) *FitnessCheckinImageCreate {
	_c.mutation.SetAuditTraceID(v)
	return _c
}

// SetNillableAuditTraceID sets the "audit_trace_id" field if the given value is not nil.
func (_c *FitnessCheckinImageCreate) SetNillableAuditTraceID(v *string) *FitnessCheckinImageCreate {
	if v != nil {
		_c.SetAuditTraceID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *FitnessCheckinImageCreate) SetID(v string) *FitnessCheckinImageCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *FitnessCheckinImageCreate) SetNillableID(v *string) *FitnessCheckinImageCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the FitnessCheckinImageMutation object of the builder.
func (_c *FitnessCheckinImageCreate) Mutation() *FitnessCheckinImageMutation {
	return _c.mutation
}

// Save creates the FitnessCheckinImage in the database.
func (_c *FitnessCheckinImageCreate) Save(ctx context.Context) (*FitnessCheckinImage, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FitnessCheckinImageCreate) SaveX(ctx context.Context) *FitnessCheckinImage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FitnessCheckinImageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FitnessCheckinImageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FitnessCheckinImageCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if fitnesscheckinimage.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized fitnesscheckinimage.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := fitnesscheckinimage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.Sort(); !ok {
		v := fitnesscheckinimage.DefaultSort
		_c.mutation.SetSort(v)
	}
	if _, ok := _c.mutation.AuditStatus(); !ok {
		v := fitnesscheckinimage.DefaultAuditStatus
		_c.mutation.SetAuditStatus(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		if fitnesscheckinimage.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized fitnesscheckinimage.DefaultID (forgotten import ent/runtime?)")
		}
		v := fitnesscheckinimage.DefaultID()
		_c.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *FitnessCheckinImageCreate) check() error {
	if _, ok := _c.mutation.CheckinID(); !ok {
		return &ValidationError{Name: "checkin_id", err: errors.New(`ent: missing required field "FitnessCheckinImage.checkin_id"`)}
	}
	if _, ok := _c.mutation.StorageFileID(); !ok {
		return &ValidationError{Name: "storage_file_id", err: errors.New(`ent: missing required field "FitnessCheckinImage.storage_file_id"`)}
	}
	if _, ok := _c.mutation.Sort(); !ok {
		return &ValidationError{Name: "sort", err: errors.New(`ent: missing required field "FitnessCheckinImage.sort"`)}
	}
	if _, ok := _c.mutation.AuditStatus(); !ok {
		return &ValidationError{Name: "audit_status", err: errors.New(`ent: missing required field "FitnessCheckinImage.audit_status"`)}
	}
	if v, ok := _c.mutation.AuditStatus(); ok {
		if err := fitnesscheckinimage.AuditStatusValidator(v); err != nil {
			return &ValidationError{Name: "audit_status", err: fmt.Errorf(`ent: validator failed for field "FitnessCheckinImage.audit_status": %w`, err)}
		}
	}
	return nil
}

func (_c *FitnessCheckinImageCreate) sqlSave(ctx context.Context) (*FitnessCheckinImage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected FitnessCheckinImage.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FitnessCheckinImageCreate) createSpec() (*FitnessCheckinImage, *sqlgraph.CreateSpec) {
	var (
		_node = &FitnessCheckinImage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(fitnesscheckinimage.Table, sqlgraph.NewFieldSpec(fitnesscheckinimage.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(fitnesscheckinimage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(fitnesscheckinimage.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(fitnesscheckinimage.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.CheckinID(); ok {
		_spec.SetField(fitnesscheckinimage.FieldCheckinID, field.TypeString, value)
		_node.CheckinID = value
	}
	if value, ok := _c.mutation.StorageFileID(); ok {
		_spec.SetField(fitnesscheckinimage.FieldStorageFileID, field.TypeString, value)
		_node.StorageFileID = value
	}
	if value, ok := _c.mutation.Sort(); ok {
		_spec.SetField(fitnesscheckinimage.FieldSort, field.TypeInt, value)
		_node.Sort = value
	}
	if value, ok := _c.mutation.AuditStatus(); ok {
		_spec.SetField(fitnesscheckinimage.FieldAuditStatus, field.TypeEnum, value)
		_node.AuditStatus = value
	}
	if value, ok := _c.mutation.AuditTraceID(); ok {
		_spec.SetField(fitnesscheckinimage.FieldAuditTraceID, field.TypeString, value)
		_node.AuditTraceID = value
	}
	return _node, _spec
}

// FitnessCheckinImageCreateBulk is the builder for creating many FitnessCheckinImage entities in bulk.
type FitnessCheckinImageCreateBulk struct {
	config
	err      error
	builders []*FitnessCheckinImageCreate
}

// Save creates the FitnessCheckinImage entities in the database.
func (_c *FitnessCheckinImageCreateBulk) Save(ctx context.Context) ([]*FitnessCheckinImage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FitnessCheckinImage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FitnessCheckinImageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FitnessCheckinImageCreateBulk) SaveX(ctx context.Context) []*FitnessCheckinImage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FitnessCheckinImageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FitnessCheckinImageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
