// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"platform/ent/fitnesscheckingroup"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// 打卡与小组关联表
type FitnessCheckinGroup struct {
	config `json:"-"`
	// ID of the ent.
	// 打卡小组关联ID
	ID string `json:"id,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt time.Time `json:"deleted_at,omitempty"`
	// 打卡ID
	CheckinID string `json:"checkin_id,omitempty"`
	// 小组ID
	GroupID      string `json:"group_id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FitnessCheckinGroup) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case fitnesscheckingroup.FieldID, fitnesscheckingroup.FieldCheckinID, fitnesscheckingroup.FieldGroupID:
			values[i] = new(sql.NullString)
		case fitnesscheckingroup.FieldCreatedAt, fitnesscheckingroup.FieldUpdatedAt, fitnesscheckingroup.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FitnessCheckinGroup fields.
func (_m *FitnessCheckinGroup) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case fitnesscheckingroup.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case fitnesscheckingroup.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case fitnesscheckingroup.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case fitnesscheckingroup.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = value.Time
			}
		case fitnesscheckingroup.FieldCheckinID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field checkin_id", values[i])
			} else if value.Valid {
				_m.CheckinID = value.String
			}
		case fitnesscheckingroup.FieldGroupID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FitnessCheckinGroup.
// This includes values selected through modifiers, order, etc.
func (_m *FitnessCheckinGroup) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this FitnessCheckinGroup.
// Note that you need to call FitnessCheckinGroup.Unwrap() before calling this method if this FitnessCheckinGroup
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *FitnessCheckinGroup) Update() *FitnessCheckinGroupUpdateOne {
	return NewFitnessCheckinGroupClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the FitnessCheckinGroup entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *FitnessCheckinGroup) Unwrap() *FitnessCheckinGroup {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: FitnessCheckinGroup is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *FitnessCheckinGroup) String() string {
	var builder strings.Builder
	builder.WriteString("FitnessCheckinGroup(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(_m.DeletedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("checkin_id=")
	builder.WriteString(_m.CheckinID)
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(_m.GroupID)
	builder.WriteByte(')')
	return builder.String()
}

// FitnessCheckinGroups is a parsable slice of FitnessCheckinGroup.
type FitnessCheckinGroups []*FitnessCheckinGroup
