// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"platform/ent/fitnessgroupinvitation"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FitnessGroupInvitationCreate is the builder for creating a FitnessGroupInvitation entity.
type FitnessGroupInvitationCreate struct {
	config
	mutation *FitnessGroupInvitationMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *FitnessGroupInvitationCreate) SetCreatedAt(v time.Time) *FitnessGroupInvitationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *FitnessGroupInvitationCreate) SetNillableCreatedAt(v *time.Time) *FitnessGroupInvitationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *FitnessGroupInvitationCreate) SetUpdatedAt(v time.Time) *FitnessGroupInvitationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *FitnessGroupInvitationCreate) SetNillableUpdatedAt(v *time.Time) *FitnessGroupInvitationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *FitnessGroupInvitationCreate) SetDeletedAt(v time.Time) *FitnessGroupInvitationCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *FitnessGroupInvitationCreate) SetNillableDeletedAt(v *time.Time) *FitnessGroupInvitationCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *FitnessGroupInvitationCreate) SetGroupID(v string) *FitnessGroupInvitationCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetCreatorID sets the "creator_id" field.
func (_c *FitnessGroupInvitationCreate) SetCreatorID(v string) *FitnessGroupInvitationCreate {
	_c.mutation.SetCreatorID(v)
	return _c
}

// SetCode sets the "code" field.
func (_c *FitnessGroupInvitationCreate) SetCode(v string) *FitnessGroupInvitationCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetQrFileID sets the "qr_file_id" field.
func (_c *FitnessGroupInvitationCreate) SetQrFileID(v string) *FitnessGroupInvitationCreate {
	_c.mutation.SetQrFileID(v)
	return _c
}

// SetNillableQrFileID sets the "qr_file_id" field if the given value is not nil.
func (_c *FitnessGroupInvitationCreate) SetNillableQrFileID(v *string) *FitnessGroupInvitationCreate {
	if v != nil {
		_c.SetQrFileID(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *FitnessGroupInvitationCreate) SetExpiresAt(v time.Time) *FitnessGroupInvitationCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetActive sets the "active" field.
func (_c *FitnessGroupInvitationCreate) SetActive(v bool) *FitnessGroupInvitationCreate {
	_c.mutation.SetActive(v)
	return _c
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_c *FitnessGroupInvitationCreate) SetNillableActive(v *bool) *FitnessGroupInvitationCreate {
	if v != nil {
		_c.SetActive(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *FitnessGroupInvitationCreate) SetID(v string) *FitnessGroupInvitationCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *FitnessGroupInvitationCreate) SetNillableID(v *string) *FitnessGroupInvitationCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the FitnessGroupInvitationMutation object of the builder.
func (_c *FitnessGroupInvitationCreate) Mutation() *FitnessGroupInvitationMutation {
	return _c.mutation
}

// Save creates the FitnessGroupInvitation in the database.
func (_c *FitnessGroupInvitationCreate) Save(ctx context.Context) (*FitnessGroupInvitation, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FitnessGroupInvitationCreate) SaveX(ctx context.Context) *FitnessGroupInvitation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FitnessGroupInvitationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FitnessGroupInvitationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FitnessGroupInvitationCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if fitnessgroupinvitation.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized fitnessgroupinvitation.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := fitnessgroupinvitation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.Active(); !ok {
		v := fitnessgroupinvitation.DefaultActive
		_c.mutation.SetActive(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		if fitnessgroupinvitation.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized fitnessgroupinvitation.DefaultID (forgotten import ent/runtime?)")
		}
		v := fitnessgroupinvitation.DefaultID()
		_c.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *FitnessGroupInvitationCreate) check() error {
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "FitnessGroupInvitation.group_id"`)}
	}
	if _, ok := _c.mutation.CreatorID(); !ok {
		return &ValidationError{Name: "creator_id", err: errors.New(`ent: missing required field "FitnessGroupInvitation.creator_id"`)}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "FitnessGroupInvitation.code"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "FitnessGroupInvitation.expires_at"`)}
	}
	if _, ok := _c.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "FitnessGroupInvitation.active"`)}
	}
	return nil
}

func (_c *FitnessGroupInvitationCreate) sqlSave(ctx context.Context) (*FitnessGroupInvitation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected FitnessGroupInvitation.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FitnessGroupInvitationCreate) createSpec() (*FitnessGroupInvitation, *sqlgraph.CreateSpec) {
	var (
		_node = &FitnessGroupInvitation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(fitnessgroupinvitation.Table, sqlgraph.NewFieldSpec(fitnessgroupinvitation.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(fitnessgroupinvitation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(fitnessgroupinvitation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(fitnessgroupinvitation.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(fitnessgroupinvitation.FieldGroupID, field.TypeString, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.CreatorID(); ok {
		_spec.SetField(fitnessgroupinvitation.FieldCreatorID, field.TypeString, value)
		_node.CreatorID = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(fitnessgroupinvitation.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.QrFileID(); ok {
		_spec.SetField(fitnessgroupinvitation.FieldQrFileID, field.TypeString, value)
		_node.QrFileID = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(fitnessgroupinvitation.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.Active(); ok {
		_spec.SetField(fitnessgroupinvitation.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	return _node, _spec
}

// FitnessGroupInvitationCreateBulk is the builder for creating many FitnessGroupInvitation entities in bulk.
type FitnessGroupInvitationCreateBulk struct {
	config
	err      error
	builders []*FitnessGroupInvitationCreate
}

// Save creates the FitnessGroupInvitation entities in the database.
func (_c *FitnessGroupInvitationCreateBulk) Save(ctx context.Context) ([]*FitnessGroupInvitation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FitnessGroupInvitation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FitnessGroupInvitationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FitnessGroupInvitationCreateBulk) SaveX(ctx context.Context) []*FitnessGroupInvitation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FitnessGroupInvitationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FitnessGroupInvitationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
