// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"platform/ent/fitnessreminderlog"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// 健身提醒发送日志表
type FitnessReminderLog struct {
	config `json:"-"`
	// ID of the ent.
	// 提醒日志ID
	ID string `json:"id,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt time.Time `json:"deleted_at,omitempty"`
	// 小组ID
	GroupID string `json:"group_id,omitempty"`
	// 接收用户ID
	TargetUserID string `json:"target_user_id,omitempty"`
	// 发起用户ID
	SenderUserID string `json:"sender_user_id,omitempty"`
	// 提醒类型
	Type fitnessreminderlog.Type `json:"type,omitempty"`
	// 提醒日期
	ReminderDate string `json:"reminder_date,omitempty"`
	// 发送状态
	Status fitnessreminderlog.Status `json:"status,omitempty"`
	// 失败原因
	FailureReason string `json:"failure_reason,omitempty"`
	// 微信消息ID
	WechatMsgID  string `json:"wechat_msg_id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FitnessReminderLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case fitnessreminderlog.FieldID, fitnessreminderlog.FieldGroupID, fitnessreminderlog.FieldTargetUserID, fitnessreminderlog.FieldSenderUserID, fitnessreminderlog.FieldType, fitnessreminderlog.FieldReminderDate, fitnessreminderlog.FieldStatus, fitnessreminderlog.FieldFailureReason, fitnessreminderlog.FieldWechatMsgID:
			values[i] = new(sql.NullString)
		case fitnessreminderlog.FieldCreatedAt, fitnessreminderlog.FieldUpdatedAt, fitnessreminderlog.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FitnessReminderLog fields.
func (_m *FitnessReminderLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case fitnessreminderlog.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case fitnessreminderlog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case fitnessreminderlog.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case fitnessreminderlog.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = value.Time
			}
		case fitnessreminderlog.FieldGroupID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.String
			}
		case fitnessreminderlog.FieldTargetUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_user_id", values[i])
			} else if value.Valid {
				_m.TargetUserID = value.String
			}
		case fitnessreminderlog.FieldSenderUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sender_user_id", values[i])
			} else if value.Valid {
				_m.SenderUserID = value.String
			}
		case fitnessreminderlog.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = fitnessreminderlog.Type(value.String)
			}
		case fitnessreminderlog.FieldReminderDate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reminder_date", values[i])
			} else if value.Valid {
				_m.ReminderDate = value.String
			}
		case fitnessreminderlog.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = fitnessreminderlog.Status(value.String)
			}
		case fitnessreminderlog.FieldFailureReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field failure_reason", values[i])
			} else if value.Valid {
				_m.FailureReason = value.String
			}
		case fitnessreminderlog.FieldWechatMsgID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field wechat_msg_id", values[i])
			} else if value.Valid {
				_m.WechatMsgID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FitnessReminderLog.
// This includes values selected through modifiers, order, etc.
func (_m *FitnessReminderLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this FitnessReminderLog.
// Note that you need to call FitnessReminderLog.Unwrap() before calling this method if this FitnessReminderLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *FitnessReminderLog) Update() *FitnessReminderLogUpdateOne {
	return NewFitnessReminderLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the FitnessReminderLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *FitnessReminderLog) Unwrap() *FitnessReminderLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: FitnessReminderLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *FitnessReminderLog) String() string {
	var builder strings.Builder
	builder.WriteString("FitnessReminderLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(_m.DeletedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(_m.GroupID)
	builder.WriteString(", ")
	builder.WriteString("target_user_id=")
	builder.WriteString(_m.TargetUserID)
	builder.WriteString(", ")
	builder.WriteString("sender_user_id=")
	builder.WriteString(_m.SenderUserID)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	builder.WriteString("reminder_date=")
	builder.WriteString(_m.ReminderDate)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("failure_reason=")
	builder.WriteString(_m.FailureReason)
	builder.WriteString(", ")
	builder.WriteString("wechat_msg_id=")
	builder.WriteString(_m.WechatMsgID)
	builder.WriteByte(')')
	return builder.String()
}

// FitnessReminderLogs is a parsable slice of FitnessReminderLog.
type FitnessReminderLogs []*FitnessReminderLog
