// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"platform/ent/fitnessreminderlog"
	"platform/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FitnessReminderLogUpdate is the builder for updating FitnessReminderLog entities.
type FitnessReminderLogUpdate struct {
	config
	hooks    []Hook
	mutation *FitnessReminderLogMutation
}

// Where appends a list predicates to the FitnessReminderLogUpdate builder.
func (_u *FitnessReminderLogUpdate) Where(ps ...predicate.FitnessReminderLog) *FitnessReminderLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *FitnessReminderLogUpdate) SetCreatedAt(v time.Time) *FitnessReminderLogUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *FitnessReminderLogUpdate) SetNillableCreatedAt(v *time.Time) *FitnessReminderLogUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *FitnessReminderLogUpdate) ClearCreatedAt() *FitnessReminderLogUpdate {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FitnessReminderLogUpdate) SetUpdatedAt(v time.Time) *FitnessReminderLogUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *FitnessReminderLogUpdate) SetNillableUpdatedAt(v *time.Time) *FitnessReminderLogUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *FitnessReminderLogUpdate) ClearUpdatedAt() *FitnessReminderLogUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *FitnessReminderLogUpdate) SetDeletedAt(v time.Time) *FitnessReminderLogUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *FitnessReminderLogUpdate) SetNillableDeletedAt(v *time.Time) *FitnessReminderLogUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *FitnessReminderLogUpdate) ClearDeletedAt() *FitnessReminderLogUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *FitnessReminderLogUpdate) SetGroupID(v string) *FitnessReminderLogUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *FitnessReminderLogUpdate) SetNillableGroupID(v *string) *FitnessReminderLogUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *FitnessReminderLogUpdate) ClearGroupID() *FitnessReminderLogUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetTargetUserID sets the "target_user_id" field.
func (_u *FitnessReminderLogUpdate) SetTargetUserID(v string) *FitnessReminderLogUpdate {
	_u.mutation.SetTargetUserID(v)
	return _u
}

// SetNillableTargetUserID sets the "target_user_id" field if the given value is not nil.
func (_u *FitnessReminderLogUpdate) SetNillableTargetUserID(v *string) *FitnessReminderLogUpdate {
	if v != nil {
		_u.SetTargetUserID(*v)
	}
	return _u
}

// SetSenderUserID sets the "sender_user_id" field.
func (_u *FitnessReminderLogUpdate) SetSenderUserID(v string) *FitnessReminderLogUpdate {
	_u.mutation.SetSenderUserID(v)
	return _u
}

// SetNillableSenderUserID sets the "sender_user_id" field if the given value is not nil.
func (_u *FitnessReminderLogUpdate) SetNillableSenderUserID(v *string) *FitnessReminderLogUpdate {
	if v != nil {
		_u.SetSenderUserID(*v)
	}
	return _u
}

// ClearSenderUserID clears the value of the "sender_user_id" field.
func (_u *FitnessReminderLogUpdate) ClearSenderUserID() *FitnessReminderLogUpdate {
	_u.mutation.ClearSenderUserID()
	return _u
}

// SetType sets the "type" field.
func (_u *FitnessReminderLogUpdate) SetType(v fitnessreminderlog.Type) *FitnessReminderLogUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *FitnessReminderLogUpdate) SetNillableType(v *fitnessreminderlog.Type) *FitnessReminderLogUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetReminderDate sets the "reminder_date" field.
func (_u *FitnessReminderLogUpdate) SetReminderDate(v string) *FitnessReminderLogUpdate {
	_u.mutation.SetReminderDate(v)
	return _u
}

// SetNillableReminderDate sets the "reminder_date" field if the given value is not nil.
func (_u *FitnessReminderLogUpdate) SetNillableReminderDate(v *string) *FitnessReminderLogUpdate {
	if v != nil {
		_u.SetReminderDate(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *FitnessReminderLogUpdate) SetStatus(v fitnessreminderlog.Status) *FitnessReminderLogUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *FitnessReminderLogUpdate) SetNillableStatus(v *fitnessreminderlog.Status) *FitnessReminderLogUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetFailureReason sets the "failure_reason" field.
func (_u *FitnessReminderLogUpdate) SetFailureReason(v string) *FitnessReminderLogUpdate {
	_u.mutation.SetFailureReason(v)
	return _u
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_u *FitnessReminderLogUpdate) SetNillableFailureReason(v *string) *FitnessReminderLogUpdate {
	if v != nil {
		_u.SetFailureReason(*v)
	}
	return _u
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (_u *FitnessReminderLogUpdate) ClearFailureReason() *FitnessReminderLogUpdate {
	_u.mutation.ClearFailureReason()
	return _u
}

// SetWechatMsgID sets the "wechat_msg_id" field.
func (_u *FitnessReminderLogUpdate) SetWechatMsgID(v string) *FitnessReminderLogUpdate {
	_u.mutation.SetWechatMsgID(v)
	return _u
}

// SetNillableWechatMsgID sets the "wechat_msg_id" field if the given value is not nil.
func (_u *FitnessReminderLogUpdate) SetNillableWechatMsgID(v *string) *FitnessReminderLogUpdate {
	if v != nil {
		_u.SetWechatMsgID(*v)
	}
	return _u
}

// ClearWechatMsgID clears the value of the "wechat_msg_id" field.
func (_u *FitnessReminderLogUpdate) ClearWechatMsgID() *FitnessReminderLogUpdate {
	_u.mutation.ClearWechatMsgID()
	return _u
}

// Mutation returns the FitnessReminderLogMutation object of the builder.
func (_u *FitnessReminderLogUpdate) Mutation() *FitnessReminderLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FitnessReminderLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FitnessReminderLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FitnessReminderLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FitnessReminderLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FitnessReminderLogUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := fitnessreminderlog.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "FitnessReminderLog.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := fitnessreminderlog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "FitnessReminderLog.status": %w`, err)}
		}
	}
	return nil
}

func (_u *FitnessReminderLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(fitnessreminderlog.Table, fitnessreminderlog.Columns, sqlgraph.NewFieldSpec(fitnessreminderlog.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(fitnessreminderlog.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(fitnessreminderlog.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(fitnessreminderlog.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(fitnessreminderlog.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(fitnessreminderlog.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(fitnessreminderlog.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(fitnessreminderlog.FieldGroupID, field.TypeString, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(fitnessreminderlog.FieldGroupID, field.TypeString)
	}
	if value, ok := _u.mutation.TargetUserID(); ok {
		_spec.SetField(fitnessreminderlog.FieldTargetUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SenderUserID(); ok {
		_spec.SetField(fitnessreminderlog.FieldSenderUserID, field.TypeString, value)
	}
	if _u.mutation.SenderUserIDCleared() {
		_spec.ClearField(fitnessreminderlog.FieldSenderUserID, field.TypeString)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(fitnessreminderlog.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ReminderDate(); ok {
		_spec.SetField(fitnessreminderlog.FieldReminderDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(fitnessreminderlog.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.FailureReason(); ok {
		_spec.SetField(fitnessreminderlog.FieldFailureReason, field.TypeString, value)
	}
	if _u.mutation.FailureReasonCleared() {
		_spec.ClearField(fitnessreminderlog.FieldFailureReason, field.TypeString)
	}
	if value, ok := _u.mutation.WechatMsgID(); ok {
		_spec.SetField(fitnessreminderlog.FieldWechatMsgID, field.TypeString, value)
	}
	if _u.mutation.WechatMsgIDCleared() {
		_spec.ClearField(fitnessreminderlog.FieldWechatMsgID, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{fitnessreminderlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FitnessReminderLogUpdateOne is the builder for updating a single FitnessReminderLog entity.
type FitnessReminderLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FitnessReminderLogMutation
}

// SetCreatedAt sets the "created_at" field.
func (_u *FitnessReminderLogUpdateOne) SetCreatedAt(v time.Time) *FitnessReminderLogUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *FitnessReminderLogUpdateOne) SetNillableCreatedAt(v *time.Time) *FitnessReminderLogUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *FitnessReminderLogUpdateOne) ClearCreatedAt() *FitnessReminderLogUpdateOne {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FitnessReminderLogUpdateOne) SetUpdatedAt(v time.Time) *FitnessReminderLogUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *FitnessReminderLogUpdateOne) SetNillableUpdatedAt(v *time.Time) *FitnessReminderLogUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *FitnessReminderLogUpdateOne) ClearUpdatedAt() *FitnessReminderLogUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *FitnessReminderLogUpdateOne) SetDeletedAt(v time.Time) *FitnessReminderLogUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *FitnessReminderLogUpdateOne) SetNillableDeletedAt(v *time.Time) *FitnessReminderLogUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *FitnessReminderLogUpdateOne) ClearDeletedAt() *FitnessReminderLogUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *FitnessReminderLogUpdateOne) SetGroupID(v string) *FitnessReminderLogUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *FitnessReminderLogUpdateOne) SetNillableGroupID(v *string) *FitnessReminderLogUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *FitnessReminderLogUpdateOne) ClearGroupID() *FitnessReminderLogUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetTargetUserID sets the "target_user_id" field.
func (_u *FitnessReminderLogUpdateOne) SetTargetUserID(v string) *FitnessReminderLogUpdateOne {
	_u.mutation.SetTargetUserID(v)
	return _u
}

// SetNillableTargetUserID sets the "target_user_id" field if the given value is not nil.
func (_u *FitnessReminderLogUpdateOne) SetNillableTargetUserID(v *string) *FitnessReminderLogUpdateOne {
	if v != nil {
		_u.SetTargetUserID(*v)
	}
	return _u
}

// SetSenderUserID sets the "sender_user_id" field.
func (_u *FitnessReminderLogUpdateOne) SetSenderUserID(v string) *FitnessReminderLogUpdateOne {
	_u.mutation.SetSenderUserID(v)
	return _u
}

// SetNillableSenderUserID sets the "sender_user_id" field if the given value is not nil.
func (_u *FitnessReminderLogUpdateOne) SetNillableSenderUserID(v *string) *FitnessReminderLogUpdateOne {
	if v != nil {
		_u.SetSenderUserID(*v)
	}
	return _u
}

// ClearSenderUserID clears the value of the "sender_user_id" field.
func (_u *FitnessReminderLogUpdateOne) ClearSenderUserID() *FitnessReminderLogUpdateOne {
	_u.mutation.ClearSenderUserID()
	return _u
}

// SetType sets the "type" field.
func (_u *FitnessReminderLogUpdateOne) SetType(v fitnessreminderlog.Type) *FitnessReminderLogUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *FitnessReminderLogUpdateOne) SetNillableType(v *fitnessreminderlog.Type) *FitnessReminderLogUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetReminderDate sets the "reminder_date" field.
func (_u *FitnessReminderLogUpdateOne) SetReminderDate(v string) *FitnessReminderLogUpdateOne {
	_u.mutation.SetReminderDate(v)
	return _u
}

// SetNillableReminderDate sets the "reminder_date" field if the given value is not nil.
func (_u *FitnessReminderLogUpdateOne) SetNillableReminderDate(v *string) *FitnessReminderLogUpdateOne {
	if v != nil {
		_u.SetReminderDate(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *FitnessReminderLogUpdateOne) SetStatus(v fitnessreminderlog.Status) *FitnessReminderLogUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *FitnessReminderLogUpdateOne) SetNillableStatus(v *fitnessreminderlog.Status) *FitnessReminderLogUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetFailureReason sets the "failure_reason" field.
func (_u *FitnessReminderLogUpdateOne) SetFailureReason(v string) *FitnessReminderLogUpdateOne {
	_u.mutation.SetFailureReason(v)
	return _u
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_u *FitnessReminderLogUpdateOne) SetNillableFailureReason(v *string) *FitnessReminderLogUpdateOne {
	if v != nil {
		_u.SetFailureReason(*v)
	}
	return _u
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (_u *FitnessReminderLogUpdateOne) ClearFailureReason() *FitnessReminderLogUpdateOne {
	_u.mutation.ClearFailureReason()
	return _u
}

// SetWechatMsgID sets the "wechat_msg_id" field.
func (_u *FitnessReminderLogUpdateOne) SetWechatMsgID(v string) *FitnessReminderLogUpdateOne {
	_u.mutation.SetWechatMsgID(v)
	return _u
}

// SetNillableWechatMsgID sets the "wechat_msg_id" field if the given value is not nil.
func (_u *FitnessReminderLogUpdateOne) SetNillableWechatMsgID(v *string) *FitnessReminderLogUpdateOne {
	if v != nil {
		_u.SetWechatMsgID(*v)
	}
	return _u
}

// ClearWechatMsgID clears the value of the "wechat_msg_id" field.
func (_u *FitnessReminderLogUpdateOne) ClearWechatMsgID() *FitnessReminderLogUpdateOne {
	_u.mutation.ClearWechatMsgID()
	return _u
}

// Mutation returns the FitnessReminderLogMutation object of the builder.
func (_u *FitnessReminderLogUpdateOne) Mutation() *FitnessReminderLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the FitnessReminderLogUpdate builder.
func (_u *FitnessReminderLogUpdateOne) Where(ps ...predicate.FitnessReminderLog) *FitnessReminderLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FitnessReminderLogUpdateOne) Select(field string, fields ...string) *FitnessReminderLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FitnessReminderLog entity.
func (_u *FitnessReminderLogUpdateOne) Save(ctx context.Context) (*FitnessReminderLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FitnessReminderLogUpdateOne) SaveX(ctx context.Context) *FitnessReminderLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FitnessReminderLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FitnessReminderLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FitnessReminderLogUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := fitnessreminderlog.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "FitnessReminderLog.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := fitnessreminderlog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "FitnessReminderLog.status": %w`, err)}
		}
	}
	return nil
}

func (_u *FitnessReminderLogUpdateOne) sqlSave(ctx context.Context) (_node *FitnessReminderLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(fitnessreminderlog.Table, fitnessreminderlog.Columns, sqlgraph.NewFieldSpec(fitnessreminderlog.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FitnessReminderLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, fitnessreminderlog.FieldID)
		for _, f := range fields {
			if !fitnessreminderlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != fitnessreminderlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(fitnessreminderlog.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(fitnessreminderlog.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(fitnessreminderlog.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(fitnessreminderlog.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(fitnessreminderlog.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(fitnessreminderlog.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(fitnessreminderlog.FieldGroupID, field.TypeString, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(fitnessreminderlog.FieldGroupID, field.TypeString)
	}
	if value, ok := _u.mutation.TargetUserID(); ok {
		_spec.SetField(fitnessreminderlog.FieldTargetUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SenderUserID(); ok {
		_spec.SetField(fitnessreminderlog.FieldSenderUserID, field.TypeString, value)
	}
	if _u.mutation.SenderUserIDCleared() {
		_spec.ClearField(fitnessreminderlog.FieldSenderUserID, field.TypeString)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(fitnessreminderlog.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ReminderDate(); ok {
		_spec.SetField(fitnessreminderlog.FieldReminderDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(fitnessreminderlog.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.FailureReason(); ok {
		_spec.SetField(fitnessreminderlog.FieldFailureReason, field.TypeString, value)
	}
	if _u.mutation.FailureReasonCleared() {
		_spec.ClearField(fitnessreminderlog.FieldFailureReason, field.TypeString)
	}
	if value, ok := _u.mutation.WechatMsgID(); ok {
		_spec.SetField(fitnessreminderlog.FieldWechatMsgID, field.TypeString, value)
	}
	if _u.mutation.WechatMsgIDCleared() {
		_spec.ClearField(fitnessreminderlog.FieldWechatMsgID, field.TypeString)
	}
	_node = &FitnessReminderLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{fitnessreminderlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
