// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"platform/ent/fitnessconfig"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FitnessConfigCreate is the builder for creating a FitnessConfig entity.
type FitnessConfigCreate struct {
	config
	mutation *FitnessConfigMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *FitnessConfigCreate) SetCreatedAt(v time.Time) *FitnessConfigCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *FitnessConfigCreate) SetNillableCreatedAt(v *time.Time) *FitnessConfigCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *FitnessConfigCreate) SetUpdatedAt(v time.Time) *FitnessConfigCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *FitnessConfigCreate) SetNillableUpdatedAt(v *time.Time) *FitnessConfigCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *FitnessConfigCreate) SetDeletedAt(v time.Time) *FitnessConfigCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *FitnessConfigCreate) SetNillableDeletedAt(v *time.Time) *FitnessConfigCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetKey sets the "key" field.
func (_c *FitnessConfigCreate) SetKey(v string) *FitnessConfigCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *FitnessConfigCreate) SetValue(v string) *FitnessConfigCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *FitnessConfigCreate) SetDescription(v string) *FitnessConfigCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *FitnessConfigCreate) SetNillableDescription(v *string) *FitnessConfigCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *FitnessConfigCreate) SetID(v string) *FitnessConfigCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *FitnessConfigCreate) SetNillableID(v *string) *FitnessConfigCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the FitnessConfigMutation object of the builder.
func (_c *FitnessConfigCreate) Mutation() *FitnessConfigMutation {
	return _c.mutation
}

// Save creates the FitnessConfig in the database.
func (_c *FitnessConfigCreate) Save(ctx context.Context) (*FitnessConfig, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FitnessConfigCreate) SaveX(ctx context.Context) *FitnessConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FitnessConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FitnessConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FitnessConfigCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if fitnessconfig.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized fitnessconfig.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := fitnessconfig.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		if fitnessconfig.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized fitnessconfig.DefaultID (forgotten import ent/runtime?)")
		}
		v := fitnessconfig.DefaultID()
		_c.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *FitnessConfigCreate) check() error {
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "FitnessConfig.key"`)}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "FitnessConfig.value"`)}
	}
	return nil
}

func (_c *FitnessConfigCreate) sqlSave(ctx context.Context) (*FitnessConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected FitnessConfig.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FitnessConfigCreate) createSpec() (*FitnessConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &FitnessConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(fitnessconfig.Table, sqlgraph.NewFieldSpec(fitnessconfig.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(fitnessconfig.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(fitnessconfig.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(fitnessconfig.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(fitnessconfig.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(fitnessconfig.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(fitnessconfig.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	return _node, _spec
}

// FitnessConfigCreateBulk is the builder for creating many FitnessConfig entities in bulk.
type FitnessConfigCreateBulk struct {
	config
	err      error
	builders []*FitnessConfigCreate
}

// Save creates the FitnessConfig entities in the database.
func (_c *FitnessConfigCreateBulk) Save(ctx context.Context) ([]*FitnessConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FitnessConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FitnessConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FitnessConfigCreateBulk) SaveX(ctx context.Context) []*FitnessConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FitnessConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FitnessConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
