// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"platform/ent/predicate"
	"platform/ent/sysstoragefile"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SysStorageFileUpdate is the builder for updating SysStorageFile entities.
type SysStorageFileUpdate struct {
	config
	hooks    []Hook
	mutation *SysStorageFileMutation
}

// Where appends a list predicates to the SysStorageFileUpdate builder.
func (_u *SysStorageFileUpdate) Where(ps ...predicate.SysStorageFile) *SysStorageFileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *SysStorageFileUpdate) SetCreatedAt(v time.Time) *SysStorageFileUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *SysStorageFileUpdate) SetNillableCreatedAt(v *time.Time) *SysStorageFileUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *SysStorageFileUpdate) ClearCreatedAt() *SysStorageFileUpdate {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SysStorageFileUpdate) SetUpdatedAt(v time.Time) *SysStorageFileUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *SysStorageFileUpdate) SetNillableUpdatedAt(v *time.Time) *SysStorageFileUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *SysStorageFileUpdate) ClearUpdatedAt() *SysStorageFileUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SysStorageFileUpdate) SetDeletedAt(v time.Time) *SysStorageFileUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SysStorageFileUpdate) SetNillableDeletedAt(v *time.Time) *SysStorageFileUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SysStorageFileUpdate) ClearDeletedAt() *SysStorageFileUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *SysStorageFileUpdate) SetName(v string) *SysStorageFileUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SysStorageFileUpdate) SetNillableName(v *string) *SysStorageFileUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *SysStorageFileUpdate) SetOwnerUserID(v string) *SysStorageFileUpdate {
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *SysStorageFileUpdate) SetNillableOwnerUserID(v *string) *SysStorageFileUpdate {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// ClearOwnerUserID clears the value of the "owner_user_id" field.
func (_u *SysStorageFileUpdate) ClearOwnerUserID() *SysStorageFileUpdate {
	_u.mutation.ClearOwnerUserID()
	return _u
}

// SetPurpose sets the "purpose" field.
func (_u *SysStorageFileUpdate) SetPurpose(v sysstoragefile.Purpose) *SysStorageFileUpdate {
	_u.mutation.SetPurpose(v)
	return _u
}

// SetNillablePurpose sets the "purpose" field if the given value is not nil.
func (_u *SysStorageFileUpdate) SetNillablePurpose(v *sysstoragefile.Purpose) *SysStorageFileUpdate {
	if v != nil {
		_u.SetPurpose(*v)
	}
	return _u
}

// SetAuditStatus sets the "audit_status" field.
func (_u *SysStorageFileUpdate) SetAuditStatus(v sysstoragefile.AuditStatus) *SysStorageFileUpdate {
	_u.mutation.SetAuditStatus(v)
	return _u
}

// SetNillableAuditStatus sets the "audit_status" field if the given value is not nil.
func (_u *SysStorageFileUpdate) SetNillableAuditStatus(v *sysstoragefile.AuditStatus) *SysStorageFileUpdate {
	if v != nil {
		_u.SetAuditStatus(*v)
	}
	return _u
}

// SetAuditTraceID sets the "audit_trace_id" field.
func (_u *SysStorageFileUpdate) SetAuditTraceID(v string) *SysStorageFileUpdate {
	_u.mutation.SetAuditTraceID(v)
	return _u
}

// SetNillableAuditTraceID sets the "audit_trace_id" field if the given value is not nil.
func (_u *SysStorageFileUpdate) SetNillableAuditTraceID(v *string) *SysStorageFileUpdate {
	if v != nil {
		_u.SetAuditTraceID(*v)
	}
	return _u
}

// ClearAuditTraceID clears the value of the "audit_trace_id" field.
func (_u *SysStorageFileUpdate) ClearAuditTraceID() *SysStorageFileUpdate {
	_u.mutation.ClearAuditTraceID()
	return _u
}

// SetTag sets the "tag" field.
func (_u *SysStorageFileUpdate) SetTag(v string) *SysStorageFileUpdate {
	_u.mutation.SetTag(v)
	return _u
}

// SetNillableTag sets the "tag" field if the given value is not nil.
func (_u *SysStorageFileUpdate) SetNillableTag(v *string) *SysStorageFileUpdate {
	if v != nil {
		_u.SetTag(*v)
	}
	return _u
}

// ClearTag clears the value of the "tag" field.
func (_u *SysStorageFileUpdate) ClearTag() *SysStorageFileUpdate {
	_u.mutation.ClearTag()
	return _u
}

// SetSize sets the "size" field.
func (_u *SysStorageFileUpdate) SetSize(v uint64) *SysStorageFileUpdate {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *SysStorageFileUpdate) SetNillableSize(v *uint64) *SysStorageFileUpdate {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *SysStorageFileUpdate) AddSize(v int64) *SysStorageFileUpdate {
	_u.mutation.AddSize(v)
	return _u
}

// SetType sets the "type" field.
func (_u *SysStorageFileUpdate) SetType(v sysstoragefile.Type) *SysStorageFileUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *SysStorageFileUpdate) SetNillableType(v *sysstoragefile.Type) *SysStorageFileUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetKey sets the "key" field.
func (_u *SysStorageFileUpdate) SetKey(v string) *SysStorageFileUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *SysStorageFileUpdate) SetNillableKey(v *string) *SysStorageFileUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// Mutation returns the SysStorageFileMutation object of the builder.
func (_u *SysStorageFileUpdate) Mutation() *SysStorageFileMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SysStorageFileUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SysStorageFileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SysStorageFileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SysStorageFileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SysStorageFileUpdate) check() error {
	if v, ok := _u.mutation.Purpose(); ok {
		if err := sysstoragefile.PurposeValidator(v); err != nil {
			return &ValidationError{Name: "purpose", err: fmt.Errorf(`ent: validator failed for field "SysStorageFile.purpose": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuditStatus(); ok {
		if err := sysstoragefile.AuditStatusValidator(v); err != nil {
			return &ValidationError{Name: "audit_status", err: fmt.Errorf(`ent: validator failed for field "SysStorageFile.audit_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := sysstoragefile.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "SysStorageFile.type": %w`, err)}
		}
	}
	return nil
}

func (_u *SysStorageFileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sysstoragefile.Table, sysstoragefile.Columns, sqlgraph.NewFieldSpec(sysstoragefile.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(sysstoragefile.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(sysstoragefile.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sysstoragefile.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(sysstoragefile.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(sysstoragefile.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(sysstoragefile.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(sysstoragefile.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.OwnerUserID(); ok {
		_spec.SetField(sysstoragefile.FieldOwnerUserID, field.TypeString, value)
	}
	if _u.mutation.OwnerUserIDCleared() {
		_spec.ClearField(sysstoragefile.FieldOwnerUserID, field.TypeString)
	}
	if value, ok := _u.mutation.Purpose(); ok {
		_spec.SetField(sysstoragefile.FieldPurpose, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AuditStatus(); ok {
		_spec.SetField(sysstoragefile.FieldAuditStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AuditTraceID(); ok {
		_spec.SetField(sysstoragefile.FieldAuditTraceID, field.TypeString, value)
	}
	if _u.mutation.AuditTraceIDCleared() {
		_spec.ClearField(sysstoragefile.FieldAuditTraceID, field.TypeString)
	}
	if value, ok := _u.mutation.Tag(); ok {
		_spec.SetField(sysstoragefile.FieldTag, field.TypeString, value)
	}
	if _u.mutation.TagCleared() {
		_spec.ClearField(sysstoragefile.FieldTag, field.TypeString)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(sysstoragefile.FieldSize, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(sysstoragefile.FieldSize, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(sysstoragefile.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(sysstoragefile.FieldKey, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sysstoragefile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SysStorageFileUpdateOne is the builder for updating a single SysStorageFile entity.
type SysStorageFileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SysStorageFileMutation
}

// SetCreatedAt sets the "created_at" field.
func (_u *SysStorageFileUpdateOne) SetCreatedAt(v time.Time) *SysStorageFileUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *SysStorageFileUpdateOne) SetNillableCreatedAt(v *time.Time) *SysStorageFileUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *SysStorageFileUpdateOne) ClearCreatedAt() *SysStorageFileUpdateOne {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SysStorageFileUpdateOne) SetUpdatedAt(v time.Time) *SysStorageFileUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *SysStorageFileUpdateOne) SetNillableUpdatedAt(v *time.Time) *SysStorageFileUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *SysStorageFileUpdateOne) ClearUpdatedAt() *SysStorageFileUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SysStorageFileUpdateOne) SetDeletedAt(v time.Time) *SysStorageFileUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SysStorageFileUpdateOne) SetNillableDeletedAt(v *time.Time) *SysStorageFileUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SysStorageFileUpdateOne) ClearDeletedAt() *SysStorageFileUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *SysStorageFileUpdateOne) SetName(v string) *SysStorageFileUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SysStorageFileUpdateOne) SetNillableName(v *string) *SysStorageFileUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *SysStorageFileUpdateOne) SetOwnerUserID(v string) *SysStorageFileUpdateOne {
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *SysStorageFileUpdateOne) SetNillableOwnerUserID(v *string) *SysStorageFileUpdateOne {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// ClearOwnerUserID clears the value of the "owner_user_id" field.
func (_u *SysStorageFileUpdateOne) ClearOwnerUserID() *SysStorageFileUpdateOne {
	_u.mutation.ClearOwnerUserID()
	return _u
}

// SetPurpose sets the "purpose" field.
func (_u *SysStorageFileUpdateOne) SetPurpose(v sysstoragefile.Purpose) *SysStorageFileUpdateOne {
	_u.mutation.SetPurpose(v)
	return _u
}

// SetNillablePurpose sets the "purpose" field if the given value is not nil.
func (_u *SysStorageFileUpdateOne) SetNillablePurpose(v *sysstoragefile.Purpose) *SysStorageFileUpdateOne {
	if v != nil {
		_u.SetPurpose(*v)
	}
	return _u
}

// SetAuditStatus sets the "audit_status" field.
func (_u *SysStorageFileUpdateOne) SetAuditStatus(v sysstoragefile.AuditStatus) *SysStorageFileUpdateOne {
	_u.mutation.SetAuditStatus(v)
	return _u
}

// SetNillableAuditStatus sets the "audit_status" field if the given value is not nil.
func (_u *SysStorageFileUpdateOne) SetNillableAuditStatus(v *sysstoragefile.AuditStatus) *SysStorageFileUpdateOne {
	if v != nil {
		_u.SetAuditStatus(*v)
	}
	return _u
}

// SetAuditTraceID sets the "audit_trace_id" field.
func (_u *SysStorageFileUpdateOne) SetAuditTraceID(v string) *SysStorageFileUpdateOne {
	_u.mutation.SetAuditTraceID(v)
	return _u
}

// SetNillableAuditTraceID sets the "audit_trace_id" field if the given value is not nil.
func (_u *SysStorageFileUpdateOne) SetNillableAuditTraceID(v *string) *SysStorageFileUpdateOne {
	if v != nil {
		_u.SetAuditTraceID(*v)
	}
	return _u
}

// ClearAuditTraceID clears the value of the "audit_trace_id" field.
func (_u *SysStorageFileUpdateOne) ClearAuditTraceID() *SysStorageFileUpdateOne {
	_u.mutation.ClearAuditTraceID()
	return _u
}

// SetTag sets the "tag" field.
func (_u *SysStorageFileUpdateOne) SetTag(v string) *SysStorageFileUpdateOne {
	_u.mutation.SetTag(v)
	return _u
}

// SetNillableTag sets the "tag" field if the given value is not nil.
func (_u *SysStorageFileUpdateOne) SetNillableTag(v *string) *SysStorageFileUpdateOne {
	if v != nil {
		_u.SetTag(*v)
	}
	return _u
}

// ClearTag clears the value of the "tag" field.
func (_u *SysStorageFileUpdateOne) ClearTag() *SysStorageFileUpdateOne {
	_u.mutation.ClearTag()
	return _u
}

// SetSize sets the "size" field.
func (_u *SysStorageFileUpdateOne) SetSize(v uint64) *SysStorageFileUpdateOne {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *SysStorageFileUpdateOne) SetNillableSize(v *uint64) *SysStorageFileUpdateOne {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *SysStorageFileUpdateOne) AddSize(v int64) *SysStorageFileUpdateOne {
	_u.mutation.AddSize(v)
	return _u
}

// SetType sets the "type" field.
func (_u *SysStorageFileUpdateOne) SetType(v sysstoragefile.Type) *SysStorageFileUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *SysStorageFileUpdateOne) SetNillableType(v *sysstoragefile.Type) *SysStorageFileUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetKey sets the "key" field.
func (_u *SysStorageFileUpdateOne) SetKey(v string) *SysStorageFileUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *SysStorageFileUpdateOne) SetNillableKey(v *string) *SysStorageFileUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// Mutation returns the SysStorageFileMutation object of the builder.
func (_u *SysStorageFileUpdateOne) Mutation() *SysStorageFileMutation {
	return _u.mutation
}

// Where appends a list predicates to the SysStorageFileUpdate builder.
func (_u *SysStorageFileUpdateOne) Where(ps ...predicate.SysStorageFile) *SysStorageFileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SysStorageFileUpdateOne) Select(field string, fields ...string) *SysStorageFileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SysStorageFile entity.
func (_u *SysStorageFileUpdateOne) Save(ctx context.Context) (*SysStorageFile, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SysStorageFileUpdateOne) SaveX(ctx context.Context) *SysStorageFile {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SysStorageFileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SysStorageFileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SysStorageFileUpdateOne) check() error {
	if v, ok := _u.mutation.Purpose(); ok {
		if err := sysstoragefile.PurposeValidator(v); err != nil {
			return &ValidationError{Name: "purpose", err: fmt.Errorf(`ent: validator failed for field "SysStorageFile.purpose": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuditStatus(); ok {
		if err := sysstoragefile.AuditStatusValidator(v); err != nil {
			return &ValidationError{Name: "audit_status", err: fmt.Errorf(`ent: validator failed for field "SysStorageFile.audit_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := sysstoragefile.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "SysStorageFile.type": %w`, err)}
		}
	}
	return nil
}

func (_u *SysStorageFileUpdateOne) sqlSave(ctx context.Context) (_node *SysStorageFile, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sysstoragefile.Table, sysstoragefile.Columns, sqlgraph.NewFieldSpec(sysstoragefile.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SysStorageFile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sysstoragefile.FieldID)
		for _, f := range fields {
			if !sysstoragefile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sysstoragefile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(sysstoragefile.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(sysstoragefile.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sysstoragefile.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(sysstoragefile.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(sysstoragefile.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(sysstoragefile.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(sysstoragefile.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.OwnerUserID(); ok {
		_spec.SetField(sysstoragefile.FieldOwnerUserID, field.TypeString, value)
	}
	if _u.mutation.OwnerUserIDCleared() {
		_spec.ClearField(sysstoragefile.FieldOwnerUserID, field.TypeString)
	}
	if value, ok := _u.mutation.Purpose(); ok {
		_spec.SetField(sysstoragefile.FieldPurpose, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AuditStatus(); ok {
		_spec.SetField(sysstoragefile.FieldAuditStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AuditTraceID(); ok {
		_spec.SetField(sysstoragefile.FieldAuditTraceID, field.TypeString, value)
	}
	if _u.mutation.AuditTraceIDCleared() {
		_spec.ClearField(sysstoragefile.FieldAuditTraceID, field.TypeString)
	}
	if value, ok := _u.mutation.Tag(); ok {
		_spec.SetField(sysstoragefile.FieldTag, field.TypeString, value)
	}
	if _u.mutation.TagCleared() {
		_spec.ClearField(sysstoragefile.FieldTag, field.TypeString)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(sysstoragefile.FieldSize, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(sysstoragefile.FieldSize, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(sysstoragefile.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(sysstoragefile.FieldKey, field.TypeString, value)
	}
	_node = &SysStorageFile{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sysstoragefile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
