// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"platform/ent/sysuser"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SysUserCreate is the builder for creating a SysUser entity.
type SysUserCreate struct {
	config
	mutation *SysUserMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *SysUserCreate) SetCreatedAt(v time.Time) *SysUserCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SysUserCreate) SetNillableCreatedAt(v *time.Time) *SysUserCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SysUserCreate) SetUpdatedAt(v time.Time) *SysUserCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SysUserCreate) SetNillableUpdatedAt(v *time.Time) *SysUserCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *SysUserCreate) SetDeletedAt(v time.Time) *SysUserCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *SysUserCreate) SetNillableDeletedAt(v *time.Time) *SysUserCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetOpenid sets the "openid" field.
func (_c *SysUserCreate) SetOpenid(v string) *SysUserCreate {
	_c.mutation.SetOpenid(v)
	return _c
}

// SetUnionid sets the "unionid" field.
func (_c *SysUserCreate) SetUnionid(v string) *SysUserCreate {
	_c.mutation.SetUnionid(v)
	return _c
}

// SetNillableUnionid sets the "unionid" field if the given value is not nil.
func (_c *SysUserCreate) SetNillableUnionid(v *string) *SysUserCreate {
	if v != nil {
		_c.SetUnionid(*v)
	}
	return _c
}

// SetNickname sets the "nickname" field.
func (_c *SysUserCreate) SetNickname(v string) *SysUserCreate {
	_c.mutation.SetNickname(v)
	return _c
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (_c *SysUserCreate) SetNillableNickname(v *string) *SysUserCreate {
	if v != nil {
		_c.SetNickname(*v)
	}
	return _c
}

// SetAvatarFileID sets the "avatar_file_id" field.
func (_c *SysUserCreate) SetAvatarFileID(v string) *SysUserCreate {
	_c.mutation.SetAvatarFileID(v)
	return _c
}

// SetNillableAvatarFileID sets the "avatar_file_id" field if the given value is not nil.
func (_c *SysUserCreate) SetNillableAvatarFileID(v *string) *SysUserCreate {
	if v != nil {
		_c.SetAvatarFileID(*v)
	}
	return _c
}

// SetReminderEnabled sets the "reminder_enabled" field.
func (_c *SysUserCreate) SetReminderEnabled(v bool) *SysUserCreate {
	_c.mutation.SetReminderEnabled(v)
	return _c
}

// SetNillableReminderEnabled sets the "reminder_enabled" field if the given value is not nil.
func (_c *SysUserCreate) SetNillableReminderEnabled(v *bool) *SysUserCreate {
	if v != nil {
		_c.SetReminderEnabled(*v)
	}
	return _c
}

// SetWeightPublic sets the "weight_public" field.
func (_c *SysUserCreate) SetWeightPublic(v bool) *SysUserCreate {
	_c.mutation.SetWeightPublic(v)
	return _c
}

// SetNillableWeightPublic sets the "weight_public" field if the given value is not nil.
func (_c *SysUserCreate) SetNillableWeightPublic(v *bool) *SysUserCreate {
	if v != nil {
		_c.SetWeightPublic(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SysUserCreate) SetStatus(v sysuser.Status) *SysUserCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SysUserCreate) SetNillableStatus(v *sysuser.Status) *SysUserCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCancelledAt sets the "cancelled_at" field.
func (_c *SysUserCreate) SetCancelledAt(v time.Time) *SysUserCreate {
	_c.mutation.SetCancelledAt(v)
	return _c
}

// SetNillableCancelledAt sets the "cancelled_at" field if the given value is not nil.
func (_c *SysUserCreate) SetNillableCancelledAt(v *time.Time) *SysUserCreate {
	if v != nil {
		_c.SetCancelledAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SysUserCreate) SetID(v string) *SysUserCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SysUserCreate) SetNillableID(v *string) *SysUserCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the SysUserMutation object of the builder.
func (_c *SysUserCreate) Mutation() *SysUserMutation {
	return _c.mutation
}

// Save creates the SysUser in the database.
func (_c *SysUserCreate) Save(ctx context.Context) (*SysUser, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SysUserCreate) SaveX(ctx context.Context) *SysUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SysUserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SysUserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SysUserCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if sysuser.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized sysuser.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := sysuser.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.Nickname(); !ok {
		v := sysuser.DefaultNickname
		_c.mutation.SetNickname(v)
	}
	if _, ok := _c.mutation.ReminderEnabled(); !ok {
		v := sysuser.DefaultReminderEnabled
		_c.mutation.SetReminderEnabled(v)
	}
	if _, ok := _c.mutation.WeightPublic(); !ok {
		v := sysuser.DefaultWeightPublic
		_c.mutation.SetWeightPublic(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := sysuser.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		if sysuser.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized sysuser.DefaultID (forgotten import ent/runtime?)")
		}
		v := sysuser.DefaultID()
		_c.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *SysUserCreate) check() error {
	if _, ok := _c.mutation.Openid(); !ok {
		return &ValidationError{Name: "openid", err: errors.New(`ent: missing required field "SysUser.openid"`)}
	}
	if _, ok := _c.mutation.Nickname(); !ok {
		return &ValidationError{Name: "nickname", err: errors.New(`ent: missing required field "SysUser.nickname"`)}
	}
	if v, ok := _c.mutation.Nickname(); ok {
		if err := sysuser.NicknameValidator(v); err != nil {
			return &ValidationError{Name: "nickname", err: fmt.Errorf(`ent: validator failed for field "SysUser.nickname": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ReminderEnabled(); !ok {
		return &ValidationError{Name: "reminder_enabled", err: errors.New(`ent: missing required field "SysUser.reminder_enabled"`)}
	}
	if _, ok := _c.mutation.WeightPublic(); !ok {
		return &ValidationError{Name: "weight_public", err: errors.New(`ent: missing required field "SysUser.weight_public"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SysUser.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := sysuser.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SysUser.status": %w`, err)}
		}
	}
	return nil
}

func (_c *SysUserCreate) sqlSave(ctx context.Context) (*SysUser, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected SysUser.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SysUserCreate) createSpec() (*SysUser, *sqlgraph.CreateSpec) {
	var (
		_node = &SysUser{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sysuser.Table, sqlgraph.NewFieldSpec(sysuser.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(sysuser.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(sysuser.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(sysuser.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.Openid(); ok {
		_spec.SetField(sysuser.FieldOpenid, field.TypeString, value)
		_node.Openid = value
	}
	if value, ok := _c.mutation.Unionid(); ok {
		_spec.SetField(sysuser.FieldUnionid, field.TypeString, value)
		_node.Unionid = value
	}
	if value, ok := _c.mutation.Nickname(); ok {
		_spec.SetField(sysuser.FieldNickname, field.TypeString, value)
		_node.Nickname = value
	}
	if value, ok := _c.mutation.AvatarFileID(); ok {
		_spec.SetField(sysuser.FieldAvatarFileID, field.TypeString, value)
		_node.AvatarFileID = value
	}
	if value, ok := _c.mutation.ReminderEnabled(); ok {
		_spec.SetField(sysuser.FieldReminderEnabled, field.TypeBool, value)
		_node.ReminderEnabled = value
	}
	if value, ok := _c.mutation.WeightPublic(); ok {
		_spec.SetField(sysuser.FieldWeightPublic, field.TypeBool, value)
		_node.WeightPublic = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(sysuser.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CancelledAt(); ok {
		_spec.SetField(sysuser.FieldCancelledAt, field.TypeTime, value)
		_node.CancelledAt = value
	}
	return _node, _spec
}

// SysUserCreateBulk is the builder for creating many SysUser entities in bulk.
type SysUserCreateBulk struct {
	config
	err      error
	builders []*SysUserCreate
}

// Save creates the SysUser entities in the database.
func (_c *SysUserCreateBulk) Save(ctx context.Context) ([]*SysUser, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SysUser, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SysUserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SysUserCreateBulk) SaveX(ctx context.Context) []*SysUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SysUserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SysUserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
