// Code generated by ent, DO NOT EDIT.

package fitnessgroup

import (
	"fmt"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the fitnessgroup type in the database.
	Label = "fitness_group"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldOwnerID holds the string denoting the owner_id field in the database.
	FieldOwnerID = "owner_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldAvatarFileID holds the string denoting the avatar_file_id field in the database.
	FieldAvatarFileID = "avatar_file_id"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldAnnouncement holds the string denoting the announcement field in the database.
	FieldAnnouncement = "announcement"
	// FieldWeeklyTarget holds the string denoting the weekly_target field in the database.
	FieldWeeklyTarget = "weekly_target"
	// FieldReminderTime holds the string denoting the reminder_time field in the database.
	FieldReminderTime = "reminder_time"
	// FieldRequireApproval holds the string denoting the require_approval field in the database.
	FieldRequireApproval = "require_approval"
	// FieldMemberLimit holds the string denoting the member_limit field in the database.
	FieldMemberLimit = "member_limit"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// Table holds the table name of the fitnessgroup in the database.
	Table = "fitness_groups"
)

// Columns holds all SQL columns for fitnessgroup fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldOwnerID,
	FieldName,
	FieldAvatarFileID,
	FieldDescription,
	FieldAnnouncement,
	FieldWeeklyTarget,
	FieldReminderTime,
	FieldRequireApproval,
	FieldMemberLimit,
	FieldStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "platform/ent/runtime"
var (
	Hooks [2]ent.Hook
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// AnnouncementValidator is a validator for the "announcement" field. It is called by the builders before save.
	AnnouncementValidator func(string) error
	// DefaultWeeklyTarget holds the default value on creation for the "weekly_target" field.
	DefaultWeeklyTarget int
	// WeeklyTargetValidator is a validator for the "weekly_target" field. It is called by the builders before save.
	WeeklyTargetValidator func(int) error
	// DefaultReminderTime holds the default value on creation for the "reminder_time" field.
	DefaultReminderTime string
	// DefaultRequireApproval holds the default value on creation for the "require_approval" field.
	DefaultRequireApproval bool
	// DefaultMemberLimit holds the default value on creation for the "member_limit" field.
	DefaultMemberLimit int
	// MemberLimitValidator is a validator for the "member_limit" field. It is called by the builders before save.
	MemberLimitValidator func(int) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive    Status = "active"
	StatusDissolved Status = "dissolved"
	StatusBlocked   Status = "blocked"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusDissolved, StatusBlocked:
		return nil
	default:
		return fmt.Errorf("fitnessgroup: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the FitnessGroup queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByOwnerID orders the results by the owner_id field.
func ByOwnerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByAvatarFileID orders the results by the avatar_file_id field.
func ByAvatarFileID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvatarFileID, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByAnnouncement orders the results by the announcement field.
func ByAnnouncement(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAnnouncement, opts...).ToFunc()
}

// ByWeeklyTarget orders the results by the weekly_target field.
func ByWeeklyTarget(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeeklyTarget, opts...).ToFunc()
}

// ByReminderTime orders the results by the reminder_time field.
func ByReminderTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReminderTime, opts...).ToFunc()
}

// ByRequireApproval orders the results by the require_approval field.
func ByRequireApproval(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequireApproval, opts...).ToFunc()
}

// ByMemberLimit orders the results by the member_limit field.
func ByMemberLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMemberLimit, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}
