// Code generated by ent, DO NOT EDIT.

package fitnessgroup

import (
	"platform/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldEQ(FieldDeletedAt, v))
}

// OwnerID applies equality check predicate on the "owner_id" field. It's identical to OwnerIDEQ.
func OwnerID(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldEQ(FieldOwnerID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldEQ(FieldName, v))
}

// AvatarFileID applies equality check predicate on the "avatar_file_id" field. It's identical to AvatarFileIDEQ.
func AvatarFileID(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldEQ(FieldAvatarFileID, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldEQ(FieldDescription, v))
}

// Announcement applies equality check predicate on the "announcement" field. It's identical to AnnouncementEQ.
func Announcement(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldEQ(FieldAnnouncement, v))
}

// WeeklyTarget applies equality check predicate on the "weekly_target" field. It's identical to WeeklyTargetEQ.
func WeeklyTarget(v int) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldEQ(FieldWeeklyTarget, v))
}

// ReminderTime applies equality check predicate on the "reminder_time" field. It's identical to ReminderTimeEQ.
func ReminderTime(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldEQ(FieldReminderTime, v))
}

// RequireApproval applies equality check predicate on the "require_approval" field. It's identical to RequireApprovalEQ.
func RequireApproval(v bool) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldEQ(FieldRequireApproval, v))
}

// MemberLimit applies equality check predicate on the "member_limit" field. It's identical to MemberLimitEQ.
func MemberLimit(v int) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldEQ(FieldMemberLimit, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldNotNull(FieldDeletedAt))
}

// OwnerIDEQ applies the EQ predicate on the "owner_id" field.
func OwnerIDEQ(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldEQ(FieldOwnerID, v))
}

// OwnerIDNEQ applies the NEQ predicate on the "owner_id" field.
func OwnerIDNEQ(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldNEQ(FieldOwnerID, v))
}

// OwnerIDIn applies the In predicate on the "owner_id" field.
func OwnerIDIn(vs ...string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldIn(FieldOwnerID, vs...))
}

// OwnerIDNotIn applies the NotIn predicate on the "owner_id" field.
func OwnerIDNotIn(vs ...string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldNotIn(FieldOwnerID, vs...))
}

// OwnerIDGT applies the GT predicate on the "owner_id" field.
func OwnerIDGT(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldGT(FieldOwnerID, v))
}

// OwnerIDGTE applies the GTE predicate on the "owner_id" field.
func OwnerIDGTE(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldGTE(FieldOwnerID, v))
}

// OwnerIDLT applies the LT predicate on the "owner_id" field.
func OwnerIDLT(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldLT(FieldOwnerID, v))
}

// OwnerIDLTE applies the LTE predicate on the "owner_id" field.
func OwnerIDLTE(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldLTE(FieldOwnerID, v))
}

// OwnerIDContains applies the Contains predicate on the "owner_id" field.
func OwnerIDContains(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldContains(FieldOwnerID, v))
}

// OwnerIDHasPrefix applies the HasPrefix predicate on the "owner_id" field.
func OwnerIDHasPrefix(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldHasPrefix(FieldOwnerID, v))
}

// OwnerIDHasSuffix applies the HasSuffix predicate on the "owner_id" field.
func OwnerIDHasSuffix(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldHasSuffix(FieldOwnerID, v))
}

// OwnerIDEqualFold applies the EqualFold predicate on the "owner_id" field.
func OwnerIDEqualFold(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldEqualFold(FieldOwnerID, v))
}

// OwnerIDContainsFold applies the ContainsFold predicate on the "owner_id" field.
func OwnerIDContainsFold(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldContainsFold(FieldOwnerID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldContainsFold(FieldName, v))
}

// AvatarFileIDEQ applies the EQ predicate on the "avatar_file_id" field.
func AvatarFileIDEQ(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldEQ(FieldAvatarFileID, v))
}

// AvatarFileIDNEQ applies the NEQ predicate on the "avatar_file_id" field.
func AvatarFileIDNEQ(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldNEQ(FieldAvatarFileID, v))
}

// AvatarFileIDIn applies the In predicate on the "avatar_file_id" field.
func AvatarFileIDIn(vs ...string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldIn(FieldAvatarFileID, vs...))
}

// AvatarFileIDNotIn applies the NotIn predicate on the "avatar_file_id" field.
func AvatarFileIDNotIn(vs ...string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldNotIn(FieldAvatarFileID, vs...))
}

// AvatarFileIDGT applies the GT predicate on the "avatar_file_id" field.
func AvatarFileIDGT(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldGT(FieldAvatarFileID, v))
}

// AvatarFileIDGTE applies the GTE predicate on the "avatar_file_id" field.
func AvatarFileIDGTE(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldGTE(FieldAvatarFileID, v))
}

// AvatarFileIDLT applies the LT predicate on the "avatar_file_id" field.
func AvatarFileIDLT(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldLT(FieldAvatarFileID, v))
}

// AvatarFileIDLTE applies the LTE predicate on the "avatar_file_id" field.
func AvatarFileIDLTE(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldLTE(FieldAvatarFileID, v))
}

// AvatarFileIDContains applies the Contains predicate on the "avatar_file_id" field.
func AvatarFileIDContains(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldContains(FieldAvatarFileID, v))
}

// AvatarFileIDHasPrefix applies the HasPrefix predicate on the "avatar_file_id" field.
func AvatarFileIDHasPrefix(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldHasPrefix(FieldAvatarFileID, v))
}

// AvatarFileIDHasSuffix applies the HasSuffix predicate on the "avatar_file_id" field.
func AvatarFileIDHasSuffix(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldHasSuffix(FieldAvatarFileID, v))
}

// AvatarFileIDIsNil applies the IsNil predicate on the "avatar_file_id" field.
func AvatarFileIDIsNil() predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldIsNull(FieldAvatarFileID))
}

// AvatarFileIDNotNil applies the NotNil predicate on the "avatar_file_id" field.
func AvatarFileIDNotNil() predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldNotNull(FieldAvatarFileID))
}

// AvatarFileIDEqualFold applies the EqualFold predicate on the "avatar_file_id" field.
func AvatarFileIDEqualFold(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldEqualFold(FieldAvatarFileID, v))
}

// AvatarFileIDContainsFold applies the ContainsFold predicate on the "avatar_file_id" field.
func AvatarFileIDContainsFold(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldContainsFold(FieldAvatarFileID, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldContainsFold(FieldDescription, v))
}

// AnnouncementEQ applies the EQ predicate on the "announcement" field.
func AnnouncementEQ(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldEQ(FieldAnnouncement, v))
}

// AnnouncementNEQ applies the NEQ predicate on the "announcement" field.
func AnnouncementNEQ(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldNEQ(FieldAnnouncement, v))
}

// AnnouncementIn applies the In predicate on the "announcement" field.
func AnnouncementIn(vs ...string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldIn(FieldAnnouncement, vs...))
}

// AnnouncementNotIn applies the NotIn predicate on the "announcement" field.
func AnnouncementNotIn(vs ...string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldNotIn(FieldAnnouncement, vs...))
}

// AnnouncementGT applies the GT predicate on the "announcement" field.
func AnnouncementGT(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldGT(FieldAnnouncement, v))
}

// AnnouncementGTE applies the GTE predicate on the "announcement" field.
func AnnouncementGTE(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldGTE(FieldAnnouncement, v))
}

// AnnouncementLT applies the LT predicate on the "announcement" field.
func AnnouncementLT(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldLT(FieldAnnouncement, v))
}

// AnnouncementLTE applies the LTE predicate on the "announcement" field.
func AnnouncementLTE(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldLTE(FieldAnnouncement, v))
}

// AnnouncementContains applies the Contains predicate on the "announcement" field.
func AnnouncementContains(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldContains(FieldAnnouncement, v))
}

// AnnouncementHasPrefix applies the HasPrefix predicate on the "announcement" field.
func AnnouncementHasPrefix(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldHasPrefix(FieldAnnouncement, v))
}

// AnnouncementHasSuffix applies the HasSuffix predicate on the "announcement" field.
func AnnouncementHasSuffix(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldHasSuffix(FieldAnnouncement, v))
}

// AnnouncementIsNil applies the IsNil predicate on the "announcement" field.
func AnnouncementIsNil() predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldIsNull(FieldAnnouncement))
}

// AnnouncementNotNil applies the NotNil predicate on the "announcement" field.
func AnnouncementNotNil() predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldNotNull(FieldAnnouncement))
}

// AnnouncementEqualFold applies the EqualFold predicate on the "announcement" field.
func AnnouncementEqualFold(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldEqualFold(FieldAnnouncement, v))
}

// AnnouncementContainsFold applies the ContainsFold predicate on the "announcement" field.
func AnnouncementContainsFold(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldContainsFold(FieldAnnouncement, v))
}

// WeeklyTargetEQ applies the EQ predicate on the "weekly_target" field.
func WeeklyTargetEQ(v int) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldEQ(FieldWeeklyTarget, v))
}

// WeeklyTargetNEQ applies the NEQ predicate on the "weekly_target" field.
func WeeklyTargetNEQ(v int) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldNEQ(FieldWeeklyTarget, v))
}

// WeeklyTargetIn applies the In predicate on the "weekly_target" field.
func WeeklyTargetIn(vs ...int) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldIn(FieldWeeklyTarget, vs...))
}

// WeeklyTargetNotIn applies the NotIn predicate on the "weekly_target" field.
func WeeklyTargetNotIn(vs ...int) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldNotIn(FieldWeeklyTarget, vs...))
}

// WeeklyTargetGT applies the GT predicate on the "weekly_target" field.
func WeeklyTargetGT(v int) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldGT(FieldWeeklyTarget, v))
}

// WeeklyTargetGTE applies the GTE predicate on the "weekly_target" field.
func WeeklyTargetGTE(v int) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldGTE(FieldWeeklyTarget, v))
}

// WeeklyTargetLT applies the LT predicate on the "weekly_target" field.
func WeeklyTargetLT(v int) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldLT(FieldWeeklyTarget, v))
}

// WeeklyTargetLTE applies the LTE predicate on the "weekly_target" field.
func WeeklyTargetLTE(v int) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldLTE(FieldWeeklyTarget, v))
}

// ReminderTimeEQ applies the EQ predicate on the "reminder_time" field.
func ReminderTimeEQ(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldEQ(FieldReminderTime, v))
}

// ReminderTimeNEQ applies the NEQ predicate on the "reminder_time" field.
func ReminderTimeNEQ(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldNEQ(FieldReminderTime, v))
}

// ReminderTimeIn applies the In predicate on the "reminder_time" field.
func ReminderTimeIn(vs ...string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldIn(FieldReminderTime, vs...))
}

// ReminderTimeNotIn applies the NotIn predicate on the "reminder_time" field.
func ReminderTimeNotIn(vs ...string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldNotIn(FieldReminderTime, vs...))
}

// ReminderTimeGT applies the GT predicate on the "reminder_time" field.
func ReminderTimeGT(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldGT(FieldReminderTime, v))
}

// ReminderTimeGTE applies the GTE predicate on the "reminder_time" field.
func ReminderTimeGTE(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldGTE(FieldReminderTime, v))
}

// ReminderTimeLT applies the LT predicate on the "reminder_time" field.
func ReminderTimeLT(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldLT(FieldReminderTime, v))
}

// ReminderTimeLTE applies the LTE predicate on the "reminder_time" field.
func ReminderTimeLTE(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldLTE(FieldReminderTime, v))
}

// ReminderTimeContains applies the Contains predicate on the "reminder_time" field.
func ReminderTimeContains(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldContains(FieldReminderTime, v))
}

// ReminderTimeHasPrefix applies the HasPrefix predicate on the "reminder_time" field.
func ReminderTimeHasPrefix(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldHasPrefix(FieldReminderTime, v))
}

// ReminderTimeHasSuffix applies the HasSuffix predicate on the "reminder_time" field.
func ReminderTimeHasSuffix(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldHasSuffix(FieldReminderTime, v))
}

// ReminderTimeEqualFold applies the EqualFold predicate on the "reminder_time" field.
func ReminderTimeEqualFold(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldEqualFold(FieldReminderTime, v))
}

// ReminderTimeContainsFold applies the ContainsFold predicate on the "reminder_time" field.
func ReminderTimeContainsFold(v string) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldContainsFold(FieldReminderTime, v))
}

// RequireApprovalEQ applies the EQ predicate on the "require_approval" field.
func RequireApprovalEQ(v bool) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldEQ(FieldRequireApproval, v))
}

// RequireApprovalNEQ applies the NEQ predicate on the "require_approval" field.
func RequireApprovalNEQ(v bool) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldNEQ(FieldRequireApproval, v))
}

// MemberLimitEQ applies the EQ predicate on the "member_limit" field.
func MemberLimitEQ(v int) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldEQ(FieldMemberLimit, v))
}

// MemberLimitNEQ applies the NEQ predicate on the "member_limit" field.
func MemberLimitNEQ(v int) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldNEQ(FieldMemberLimit, v))
}

// MemberLimitIn applies the In predicate on the "member_limit" field.
func MemberLimitIn(vs ...int) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldIn(FieldMemberLimit, vs...))
}

// MemberLimitNotIn applies the NotIn predicate on the "member_limit" field.
func MemberLimitNotIn(vs ...int) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldNotIn(FieldMemberLimit, vs...))
}

// MemberLimitGT applies the GT predicate on the "member_limit" field.
func MemberLimitGT(v int) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldGT(FieldMemberLimit, v))
}

// MemberLimitGTE applies the GTE predicate on the "member_limit" field.
func MemberLimitGTE(v int) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldGTE(FieldMemberLimit, v))
}

// MemberLimitLT applies the LT predicate on the "member_limit" field.
func MemberLimitLT(v int) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldLT(FieldMemberLimit, v))
}

// MemberLimitLTE applies the LTE predicate on the "member_limit" field.
func MemberLimitLTE(v int) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldLTE(FieldMemberLimit, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.FieldNotIn(FieldStatus, vs...))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FitnessGroup) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FitnessGroup) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FitnessGroup) predicate.FitnessGroup {
	return predicate.FitnessGroup(sql.NotPredicates(p))
}
